/**
 * Additional strategy templates — scalping, Ichimoku, DCA, grid trading, confluences
 */

import { StrategyTemplate } from './types';

export const ADDITIONAL_STRATEGY_TEMPLATES: StrategyTemplate[] = [
  {
    id: 'vwap-intraday',
    name: 'VWAP Intraday',
    description: 'Buy when price crosses above VWAP, sell when it drops below. A favorite of institutional day traders.',
    category: 'scalping',
    difficulty: 'intermediate',
    indicators: ['VWAP'],
    featured: true,
    nodes: [
      { id: 'vwap', type: 'indicator', position: { x: 100, y: 150 }, data: { label: 'VWAP', indicatorType: 'vwap', timeframe: '5' } },
      { id: 'price', type: 'environment', position: { x: 100, y: 280 }, data: { label: 'Price', environmentType: 'price', priceType: 'close' } },
      { id: 'cross-above', type: 'condition', position: { x: 350, y: 130 }, data: { label: 'Price Crosses Above VWAP', conditionType: 'crossover' } },
      { id: 'cross-below', type: 'condition', position: { x: 350, y: 280 }, data: { label: 'Price Crosses Below VWAP', conditionType: 'crossunder' } },
      { id: 'buy', type: 'action', position: { x: 600, y: 130 }, data: { label: 'Buy', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' } },
      { id: 'sell', type: 'action', position: { x: 600, y: 280 }, data: { label: 'Sell', actionType: 'order', direction: 'short', size: 10, sizeType: 'percent' } },
    ],
    edges: [
      { id: 'e1', source: 'price', sourceHandle: 'value', target: 'cross-above', targetHandle: 'input-a' },
      { id: 'e2', source: 'vwap', sourceHandle: 'value', target: 'cross-above', targetHandle: 'input-b' },
      { id: 'e3', source: 'price', sourceHandle: 'value', target: 'cross-below', targetHandle: 'input-a' },
      { id: 'e4', source: 'vwap', sourceHandle: 'value', target: 'cross-below', targetHandle: 'input-b' },
      { id: 'e5', source: 'cross-above', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
      { id: 'e6', source: 'cross-below', sourceHandle: 'output', target: 'sell', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'scalping-momentum',
    name: 'Scalping Momentum',
    description: 'Fast EMA crossover with RSI filter for quick momentum trades on short timeframes.',
    category: 'scalping',
    difficulty: 'advanced',
    indicators: ['EMA (5)', 'EMA (13)', 'RSI'],
    nodes: [
      { id: 'ema-5', type: 'indicator', position: { x: 100, y: 80 }, data: { label: 'EMA 5', indicatorType: 'ema', timeframe: '1', params: { period: 5 } } },
      { id: 'ema-13', type: 'indicator', position: { x: 100, y: 200 }, data: { label: 'EMA 13', indicatorType: 'ema', timeframe: '1', params: { period: 13 } } },
      { id: 'rsi', type: 'indicator', position: { x: 100, y: 320 }, data: { label: 'RSI (7)', indicatorType: 'rsi', timeframe: '1', params: { period: 7 } } },
      { id: 'const-50', type: 'math', position: { x: 100, y: 440 }, data: { label: '50', mathType: 'number', value: 50 } },
      { id: 'crossover', type: 'condition', position: { x: 350, y: 140 }, data: { label: 'EMA 5 > EMA 13', conditionType: 'crossover' } },
      { id: 'rsi-filter', type: 'condition', position: { x: 350, y: 370 }, data: { label: 'RSI > 50', conditionType: 'compare', operator: '>' } },
      { id: 'and', type: 'condition', position: { x: 560, y: 250 }, data: { label: 'AND', conditionType: 'and' } },
      { id: 'buy', type: 'action', position: { x: 760, y: 250 }, data: { label: 'Buy', actionType: 'order', direction: 'long', size: 5, sizeType: 'percent' } },
    ],
    edges: [
      { id: 'e1', source: 'ema-5', sourceHandle: 'value', target: 'crossover', targetHandle: 'input-a' },
      { id: 'e2', source: 'ema-13', sourceHandle: 'value', target: 'crossover', targetHandle: 'input-b' },
      { id: 'e3', source: 'rsi', sourceHandle: 'value', target: 'rsi-filter', targetHandle: 'input-a' },
      { id: 'e4', source: 'const-50', sourceHandle: 'output', target: 'rsi-filter', targetHandle: 'input-b' },
      { id: 'e5', source: 'crossover', sourceHandle: 'output', target: 'and', targetHandle: 'input-a' },
      { id: 'e6', source: 'rsi-filter', sourceHandle: 'output', target: 'and', targetHandle: 'input-b' },
      { id: 'e7', source: 'and', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'ichimoku-cloud',
    name: 'Ichimoku Cloud',
    description: 'Full Ichimoku system — buy when price is above the cloud and Tenkan crosses above Kijun.',
    category: 'trend',
    difficulty: 'advanced',
    indicators: ['Ichimoku'],
    nodes: [
      { id: 'ichi', type: 'indicator', position: { x: 100, y: 150 }, data: { label: 'Ichimoku', indicatorType: 'ichimoku', timeframe: '1D', params: { tenkan: 9, kijun: 26, senkou: 52 } } },
      { id: 'price', type: 'environment', position: { x: 100, y: 300 }, data: { label: 'Price', environmentType: 'price', priceType: 'close' } },
      { id: 'above-cloud', type: 'condition', position: { x: 380, y: 180 }, data: { label: 'Price > Cloud', conditionType: 'compare', operator: '>' } },
      { id: 'tenkan-cross', type: 'condition', position: { x: 380, y: 320 }, data: { label: 'TK Cross', conditionType: 'crossover' } },
      { id: 'and', type: 'condition', position: { x: 600, y: 250 }, data: { label: 'AND', conditionType: 'and' } },
      { id: 'buy', type: 'action', position: { x: 800, y: 250 }, data: { label: 'Buy', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' } },
    ],
    edges: [
      { id: 'e1', source: 'price', sourceHandle: 'value', target: 'above-cloud', targetHandle: 'input-a' },
      { id: 'e2', source: 'ichi', sourceHandle: 'senkou_a', target: 'above-cloud', targetHandle: 'input-b' },
      { id: 'e3', source: 'ichi', sourceHandle: 'tenkan', target: 'tenkan-cross', targetHandle: 'input-a' },
      { id: 'e3b', source: 'ichi', sourceHandle: 'kijun', target: 'tenkan-cross', targetHandle: 'input-b' },
      { id: 'e4', source: 'above-cloud', sourceHandle: 'output', target: 'and', targetHandle: 'input-a' },
      { id: 'e5', source: 'tenkan-cross', sourceHandle: 'output', target: 'and', targetHandle: 'input-b' },
      { id: 'e6', source: 'and', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'dca-bot',
    name: 'DCA Bot',
    description: 'Dollar-Cost Averaging strategy. Buys a fixed amount on a regular schedule regardless of price.',
    category: 'portfolio',
    difficulty: 'beginner',
    indicators: [],
    featured: true,
    nodes: [
      { id: 'schedule', type: 'trigger', position: { x: 100, y: 150 }, data: { label: 'Weekly Buy', triggerType: 'cronTrigger', cronExpression: '0 0 * * 1' } },
      { id: 'buy', type: 'action', position: { x: 380, y: 150 }, data: { label: 'Buy $100', actionType: 'order', direction: 'long', size: 100, sizeType: 'fixed' } },
    ],
    edges: [
      { id: 'e1', source: 'schedule', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'grid-trading',
    name: 'Grid Trading',
    description: 'Places buy and sell orders at predefined price levels, profiting from range-bound markets.',
    category: 'trading',
    difficulty: 'advanced',
    indicators: ['ATR'],
    nodes: [
      { id: 'atr', type: 'indicator', position: { x: 100, y: 150 }, data: { label: 'ATR (14)', indicatorType: 'atr', timeframe: '60', params: { period: 14 } } },
      { id: 'price', type: 'environment', position: { x: 100, y: 280 }, data: { label: 'Price', environmentType: 'price', priceType: 'mid' } },
      { id: 'grid-low', type: 'math', position: { x: 350, y: 100 }, data: { label: 'Grid Low', mathType: 'subtract' } },
      { id: 'grid-high', type: 'math', position: { x: 350, y: 250 }, data: { label: 'Grid High', mathType: 'add' } },
      { id: 'hit-low', type: 'condition', position: { x: 560, y: 100 }, data: { label: 'Hit Low Grid', conditionType: 'compare', operator: '<' } },
      { id: 'hit-high', type: 'condition', position: { x: 560, y: 250 }, data: { label: 'Hit High Grid', conditionType: 'compare', operator: '>' } },
      { id: 'buy', type: 'action', position: { x: 780, y: 100 }, data: { label: 'Grid Buy', actionType: 'order', direction: 'long', size: 5, sizeType: 'percent' } },
      { id: 'sell', type: 'action', position: { x: 780, y: 250 }, data: { label: 'Grid Sell', actionType: 'order', direction: 'short', size: 5, sizeType: 'percent' } },
    ],
    edges: [
      { id: 'e1', source: 'price', sourceHandle: 'value', target: 'grid-low', targetHandle: 'input-a' },
      { id: 'e2', source: 'atr', sourceHandle: 'value', target: 'grid-low', targetHandle: 'input-b' },
      { id: 'e3', source: 'price', sourceHandle: 'value', target: 'grid-high', targetHandle: 'input-a' },
      { id: 'e4', source: 'atr', sourceHandle: 'value', target: 'grid-high', targetHandle: 'input-b' },
      { id: 'e5', source: 'price', sourceHandle: 'value', target: 'hit-low', targetHandle: 'input-a' },
      { id: 'e6', source: 'grid-low', sourceHandle: 'output', target: 'hit-low', targetHandle: 'input-b' },
      { id: 'e7', source: 'price', sourceHandle: 'value', target: 'hit-high', targetHandle: 'input-a' },
      { id: 'e8', source: 'grid-high', sourceHandle: 'output', target: 'hit-high', targetHandle: 'input-b' },
      { id: 'e9', source: 'hit-low', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
      { id: 'e10', source: 'hit-high', sourceHandle: 'output', target: 'sell', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'rsi-bb-confluence',
    name: 'RSI + Bollinger Confluence',
    description: 'Mean reversion using RSI oversold + price touching lower Bollinger Band for high-confidence entries.',
    category: 'mean-reversion',
    difficulty: 'intermediate',
    indicators: ['RSI', 'Bollinger Bands'],
    nodes: [
      { id: 'rsi', type: 'indicator', position: { x: 100, y: 80 }, data: { label: 'RSI (14)', indicatorType: 'rsi', timeframe: '60', params: { period: 14 } } },
      { id: 'bb', type: 'indicator', position: { x: 100, y: 200 }, data: { label: 'BB (20)', indicatorType: 'bb', timeframe: '60', params: { period: 20, stdDev: 2 } } },
      { id: 'price', type: 'environment', position: { x: 100, y: 340 }, data: { label: 'Price', environmentType: 'price', priceType: 'close' } },
      { id: 'const-30', type: 'math', position: { x: 100, y: 450 }, data: { label: '30', mathType: 'number', value: 30 } },
      { id: 'rsi-low', type: 'condition', position: { x: 370, y: 100 }, data: { label: 'RSI < 30', conditionType: 'compare', operator: '<' } },
      { id: 'bb-touch', type: 'condition', position: { x: 370, y: 270 }, data: { label: 'Price < Lower BB', conditionType: 'compare', operator: '<' } },
      { id: 'and', type: 'condition', position: { x: 600, y: 180 }, data: { label: 'AND', conditionType: 'and' } },
      { id: 'buy', type: 'action', position: { x: 800, y: 180 }, data: { label: 'Buy', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' } },
    ],
    edges: [
      { id: 'e1', source: 'rsi', sourceHandle: 'value', target: 'rsi-low', targetHandle: 'input-a' },
      { id: 'e2', source: 'const-30', sourceHandle: 'output', target: 'rsi-low', targetHandle: 'input-b' },
      { id: 'e3', source: 'price', sourceHandle: 'value', target: 'bb-touch', targetHandle: 'input-a' },
      { id: 'e4', source: 'bb', sourceHandle: 'lower', target: 'bb-touch', targetHandle: 'input-b' },
      { id: 'e5', source: 'rsi-low', sourceHandle: 'output', target: 'and', targetHandle: 'input-a' },
      { id: 'e6', source: 'bb-touch', sourceHandle: 'output', target: 'and', targetHandle: 'input-b' },
      { id: 'e7', source: 'and', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'stochastic-divergence',
    name: 'Stochastic Divergence',
    description: 'Spot potential reversals when price makes new lows but Stochastic makes higher lows.',
    category: 'momentum',
    difficulty: 'intermediate',
    indicators: ['Stochastic'],
    nodes: [
      { id: 'stoch', type: 'indicator', position: { x: 100, y: 150 }, data: { label: 'Stochastic', indicatorType: 'stochastic', timeframe: '60', params: { kPeriod: 14, dPeriod: 3 } } },
      { id: 'const-20', type: 'math', position: { x: 100, y: 280 }, data: { label: '20', mathType: 'number', value: 20 } },
      { id: 'oversold', type: 'condition', position: { x: 370, y: 180 }, data: { label: 'Stoch < 20', conditionType: 'compare', operator: '<' } },
      { id: 'crossover', type: 'condition', position: { x: 370, y: 310 }, data: { label: 'K crosses D', conditionType: 'crossover' } },
      { id: 'and', type: 'condition', position: { x: 580, y: 240 }, data: { label: 'AND', conditionType: 'and' } },
      { id: 'buy', type: 'action', position: { x: 780, y: 240 }, data: { label: 'Buy', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' } },
    ],
    edges: [
      { id: 'e1', source: 'stoch', sourceHandle: 'main', target: 'oversold', targetHandle: 'input-a' },
      { id: 'e2', source: 'const-20', sourceHandle: 'output', target: 'oversold', targetHandle: 'input-b' },
      { id: 'e3', source: 'stoch', sourceHandle: 'main', target: 'crossover', targetHandle: 'input-a' },
      { id: 'e3b', source: 'stoch', sourceHandle: 'signal', target: 'crossover', targetHandle: 'input-b' },
      { id: 'e4', source: 'oversold', sourceHandle: 'output', target: 'and', targetHandle: 'input-a' },
      { id: 'e5', source: 'crossover', sourceHandle: 'output', target: 'and', targetHandle: 'input-b' },
      { id: 'e6', source: 'and', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'atr-volatility-breakout',
    name: 'ATR Volatility Breakout',
    description: 'Enter trades when price moves more than 2× ATR from the open, indicating a strong directional move.',
    category: 'breakout',
    difficulty: 'intermediate',
    indicators: ['ATR'],
    nodes: [
      { id: 'atr', type: 'indicator', position: { x: 100, y: 130 }, data: { label: 'ATR (14)', indicatorType: 'atr', timeframe: '60', params: { period: 14 } } },
      { id: 'mult', type: 'math', position: { x: 100, y: 260 }, data: { label: '×2', mathType: 'multiply', value: 2 } },
      { id: 'price', type: 'environment', position: { x: 100, y: 380 }, data: { label: 'Price Change', environmentType: 'price', priceType: 'close' } },
      { id: 'range', type: 'math', position: { x: 350, y: 190 }, data: { label: 'ATR × 2', mathType: 'multiply' } },
      { id: 'compare', type: 'condition', position: { x: 570, y: 260 }, data: { label: 'Move > 2×ATR', conditionType: 'compare', operator: '>' } },
      { id: 'buy', type: 'action', position: { x: 790, y: 260 }, data: { label: 'Buy Breakout', actionType: 'order', direction: 'long', size: 8, sizeType: 'percent' } },
    ],
    edges: [
      { id: 'e1', source: 'atr', sourceHandle: 'value', target: 'range', targetHandle: 'input-a' },
      { id: 'e2', source: 'mult', sourceHandle: 'output', target: 'range', targetHandle: 'input-b' },
      { id: 'e3', source: 'price', sourceHandle: 'value', target: 'compare', targetHandle: 'input-a' },
      { id: 'e4', source: 'range', sourceHandle: 'output', target: 'compare', targetHandle: 'input-b' },
      { id: 'e5', source: 'compare', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
];
