/**
 * Pine Script strategy templates for TradingView-style visual scripting
 */

import { StrategyTemplate } from './types';

export const PINE_SCRIPT_TEMPLATES: StrategyTemplate[] = [
  {
    id: 'pine-sma-crossover',
    name: 'SMA Crossover Script',
    description: 'Classic dual SMA crossover strategy in Pine Script. Generates buy/sell signals and plots both moving averages.',
    category: 'pinescript',
    difficulty: 'beginner',
    indicators: ['ta.sma'],
    featured: true,
    nodes: [
      { id: 'ps-setup', type: 'pineScript', position: { x: 100, y: 50 }, data: { label: 'strategy()', pineType: 'pine_strategy', scriptTitle: 'SMA Crossover', overlay: true } },
      { id: 'ps-len-fast', type: 'pineScript', position: { x: 100, y: 150 }, data: { label: 'input.int', pineType: 'pine_input_int', inputName: 'Fast Length', inputDefault: 10 } },
      { id: 'ps-len-slow', type: 'pineScript', position: { x: 100, y: 250 }, data: { label: 'input.int', pineType: 'pine_input_int', inputName: 'Slow Length', inputDefault: 20 } },
      { id: 'ps-close', type: 'pineScript', position: { x: 100, y: 350 }, data: { label: 'close', pineType: 'pine_close' } },
      { id: 'ps-sma-fast', type: 'pineScript', position: { x: 380, y: 150 }, data: { label: 'ta.sma', pineType: 'pine_ta_sma', source: 'close' } },
      { id: 'ps-sma-slow', type: 'pineScript', position: { x: 380, y: 280 }, data: { label: 'ta.sma', pineType: 'pine_ta_sma', source: 'close' } },
      { id: 'ps-cross-up', type: 'pineScript', position: { x: 630, y: 180 }, data: { label: 'ta.crossover', pineType: 'pine_ta_crossover' } },
      { id: 'ps-cross-dn', type: 'pineScript', position: { x: 630, y: 320 }, data: { label: 'ta.crossunder', pineType: 'pine_ta_crossunder' } },
      { id: 'ps-entry', type: 'pineScript', position: { x: 880, y: 180 }, data: { label: 'strategy.entry', pineType: 'pine_strategy_entry', entryId: 'Long', direction: 'long' } },
      { id: 'ps-close-pos', type: 'pineScript', position: { x: 880, y: 320 }, data: { label: 'strategy.close', pineType: 'pine_strategy_close', entryId: 'Long' } },
      { id: 'ps-plot-fast', type: 'pineScript', position: { x: 630, y: 60 }, data: { label: 'plot', pineType: 'pine_plot', plotTitle: 'Fast SMA', plotColor: '#2962FF', plotLineWidth: 2 } },
      { id: 'ps-plot-slow', type: 'pineScript', position: { x: 630, y: 440 }, data: { label: 'plot', pineType: 'pine_plot', plotTitle: 'Slow SMA', plotColor: '#FF6D00', plotLineWidth: 2 } },
    ],
    edges: [
      { id: 'pe1', source: 'ps-close', target: 'ps-sma-fast', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe2', source: 'ps-len-fast', target: 'ps-sma-fast', sourceHandle: 'output', targetHandle: 'input-b' },
      { id: 'pe3', source: 'ps-close', target: 'ps-sma-slow', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe4', source: 'ps-len-slow', target: 'ps-sma-slow', sourceHandle: 'output', targetHandle: 'input-b' },
      { id: 'pe5', source: 'ps-sma-fast', target: 'ps-cross-up', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe6', source: 'ps-sma-slow', target: 'ps-cross-up', sourceHandle: 'output', targetHandle: 'input-b' },
      { id: 'pe7', source: 'ps-sma-fast', target: 'ps-cross-dn', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe8', source: 'ps-sma-slow', target: 'ps-cross-dn', sourceHandle: 'output', targetHandle: 'input-b' },
      { id: 'pe9', source: 'ps-cross-up', target: 'ps-entry', sourceHandle: 'output', targetHandle: 'input' },
      { id: 'pe10', source: 'ps-cross-dn', target: 'ps-close-pos', sourceHandle: 'output', targetHandle: 'input' },
      { id: 'pe11', source: 'ps-sma-fast', target: 'ps-plot-fast', sourceHandle: 'output', targetHandle: 'input' },
      { id: 'pe12', source: 'ps-sma-slow', target: 'ps-plot-slow', sourceHandle: 'output', targetHandle: 'input' },
    ],
  },
  {
    id: 'pine-rsi-strategy',
    name: 'RSI Overbought/Oversold',
    description: 'Buy when RSI drops below 30, sell when it rises above 70. Includes horizontal reference lines and background coloring.',
    category: 'pinescript',
    difficulty: 'beginner',
    indicators: ['ta.rsi'],
    featured: true,
    nodes: [
      { id: 'ps-setup', type: 'pineScript', position: { x: 100, y: 50 }, data: { label: 'strategy()', pineType: 'pine_strategy', scriptTitle: 'RSI Strategy', overlay: true } },
      { id: 'ps-len', type: 'pineScript', position: { x: 100, y: 150 }, data: { label: 'input.int', pineType: 'pine_input_int', inputName: 'RSI Length', inputDefault: 14 } },
      { id: 'ps-close', type: 'pineScript', position: { x: 100, y: 260 }, data: { label: 'close', pineType: 'pine_close' } },
      { id: 'ps-rsi', type: 'pineScript', position: { x: 380, y: 180 }, data: { label: 'ta.rsi', pineType: 'pine_ta_rsi', source: 'close' } },
      { id: 'ps-cmp-low', type: 'pineScript', position: { x: 630, y: 130 }, data: { label: 'Compare', pineType: 'pine_compare', operator: '<' } },
      { id: 'ps-cmp-high', type: 'pineScript', position: { x: 630, y: 280 }, data: { label: 'Compare', pineType: 'pine_compare', operator: '>' } },
      { id: 'ps-entry', type: 'pineScript', position: { x: 880, y: 130 }, data: { label: 'strategy.entry', pineType: 'pine_strategy_entry', entryId: 'Long', direction: 'long' } },
      { id: 'ps-close-pos', type: 'pineScript', position: { x: 880, y: 280 }, data: { label: 'strategy.close', pineType: 'pine_strategy_close', entryId: 'Long' } },
      { id: 'ps-plot', type: 'pineScript', position: { x: 380, y: 340 }, data: { label: 'plot', pineType: 'pine_plot', plotTitle: 'RSI', plotColor: '#7C4DFF', plotLineWidth: 2 } },
    ],
    edges: [
      { id: 'pe1', source: 'ps-close', target: 'ps-rsi', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe2', source: 'ps-len', target: 'ps-rsi', sourceHandle: 'output', targetHandle: 'input-b' },
      { id: 'pe3', source: 'ps-rsi', target: 'ps-cmp-low', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe4', source: 'ps-rsi', target: 'ps-cmp-high', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe5', source: 'ps-cmp-low', target: 'ps-entry', sourceHandle: 'output', targetHandle: 'input' },
      { id: 'pe6', source: 'ps-cmp-high', target: 'ps-close-pos', sourceHandle: 'output', targetHandle: 'input' },
      { id: 'pe7', source: 'ps-rsi', target: 'ps-plot', sourceHandle: 'output', targetHandle: 'input' },
    ],
  },
  {
    id: 'pine-macd-strategy',
    name: 'MACD Strategy',
    description: 'MACD line / signal line crossover strategy with histogram plotting. Classic momentum approach.',
    category: 'pinescript',
    difficulty: 'intermediate',
    indicators: ['ta.macd'],
    nodes: [
      { id: 'ps-setup', type: 'pineScript', position: { x: 100, y: 50 }, data: { label: 'strategy()', pineType: 'pine_strategy', scriptTitle: 'MACD Strategy', overlay: false } },
      { id: 'ps-close', type: 'pineScript', position: { x: 100, y: 180 }, data: { label: 'close', pineType: 'pine_close' } },
      { id: 'ps-macd', type: 'pineScript', position: { x: 380, y: 180 }, data: { label: 'ta.macd', pineType: 'pine_ta_macd', source: 'close' } },
      { id: 'ps-cross-up', type: 'pineScript', position: { x: 630, y: 130 }, data: { label: 'ta.crossover', pineType: 'pine_ta_crossover' } },
      { id: 'ps-cross-dn', type: 'pineScript', position: { x: 630, y: 280 }, data: { label: 'ta.crossunder', pineType: 'pine_ta_crossunder' } },
      { id: 'ps-entry', type: 'pineScript', position: { x: 880, y: 130 }, data: { label: 'strategy.entry', pineType: 'pine_strategy_entry', entryId: 'Long', direction: 'long' } },
      { id: 'ps-close-pos', type: 'pineScript', position: { x: 880, y: 280 }, data: { label: 'strategy.close', pineType: 'pine_strategy_close', entryId: 'Long' } },
    ],
    edges: [
      { id: 'pe1', source: 'ps-close', target: 'ps-macd', sourceHandle: 'output', targetHandle: 'input' },
      { id: 'pe2', source: 'ps-macd', target: 'ps-cross-up', sourceHandle: 'macd', targetHandle: 'input-a' },
      { id: 'pe3', source: 'ps-macd', target: 'ps-cross-up', sourceHandle: 'signal', targetHandle: 'input-b' },
      { id: 'pe4', source: 'ps-macd', target: 'ps-cross-dn', sourceHandle: 'macd', targetHandle: 'input-a' },
      { id: 'pe5', source: 'ps-macd', target: 'ps-cross-dn', sourceHandle: 'signal', targetHandle: 'input-b' },
      { id: 'pe6', source: 'ps-cross-up', target: 'ps-entry', sourceHandle: 'output', targetHandle: 'input' },
      { id: 'pe7', source: 'ps-cross-dn', target: 'ps-close-pos', sourceHandle: 'output', targetHandle: 'input' },
    ],
  },
  {
    id: 'pine-bb-squeeze',
    name: 'Bollinger Bands Squeeze',
    description: 'Detects low-volatility squeezes using Bollinger Bands and ATR, enters on breakout above upper band.',
    category: 'pinescript',
    difficulty: 'intermediate',
    indicators: ['ta.bb', 'ta.atr'],
    nodes: [
      { id: 'ps-setup', type: 'pineScript', position: { x: 100, y: 50 }, data: { label: 'strategy()', pineType: 'pine_strategy', scriptTitle: 'BB Squeeze', overlay: true } },
      { id: 'ps-len', type: 'pineScript', position: { x: 100, y: 150 }, data: { label: 'input.int', pineType: 'pine_input_int', inputName: 'BB Length', inputDefault: 20 } },
      { id: 'ps-close', type: 'pineScript', position: { x: 100, y: 260 }, data: { label: 'close', pineType: 'pine_close' } },
      { id: 'ps-bb', type: 'pineScript', position: { x: 380, y: 180 }, data: { label: 'ta.bb', pineType: 'pine_ta_bb', period: 20, source: 'close' } },
      { id: 'ps-cmp', type: 'pineScript', position: { x: 630, y: 180 }, data: { label: 'Compare', pineType: 'pine_compare', operator: '>' } },
      { id: 'ps-entry', type: 'pineScript', position: { x: 880, y: 180 }, data: { label: 'strategy.entry', pineType: 'pine_strategy_entry', entryId: 'Long', direction: 'long' } },
    ],
    edges: [
      { id: 'pe1', source: 'ps-close', target: 'ps-bb', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe2', source: 'ps-len', target: 'ps-bb', sourceHandle: 'output', targetHandle: 'input-b' },
      { id: 'pe3', source: 'ps-close', target: 'ps-cmp', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe4', source: 'ps-bb', target: 'ps-cmp', sourceHandle: 'upper', targetHandle: 'input-b' },
      { id: 'pe5', source: 'ps-cmp', target: 'ps-entry', sourceHandle: 'output', targetHandle: 'input' },
    ],
  },
  {
    id: 'pine-multi-indicator',
    name: 'Multi-Indicator Confluence',
    description: 'Combines EMA trend filter + RSI oversold + VWAP support for high-probability entries.',
    category: 'pinescript',
    difficulty: 'advanced',
    indicators: ['ta.ema', 'ta.rsi', 'ta.vwap'],
    featured: true,
    nodes: [
      { id: 'ps-setup', type: 'pineScript', position: { x: 100, y: 50 }, data: { label: 'strategy()', pineType: 'pine_strategy', scriptTitle: 'Multi-Indicator', overlay: true } },
      { id: 'ps-close', type: 'pineScript', position: { x: 100, y: 180 }, data: { label: 'close', pineType: 'pine_close' } },
      { id: 'ps-ema', type: 'pineScript', position: { x: 350, y: 100 }, data: { label: 'ta.ema', pineType: 'pine_ta_ema', period: 50, source: 'close' } },
      { id: 'ps-rsi', type: 'pineScript', position: { x: 350, y: 230 }, data: { label: 'ta.rsi', pineType: 'pine_ta_rsi', period: 14, source: 'close' } },
      { id: 'ps-vwap', type: 'pineScript', position: { x: 350, y: 360 }, data: { label: 'ta.vwap', pineType: 'pine_ta_vwap', source: 'close' } },
      { id: 'ps-cmp-ema', type: 'pineScript', position: { x: 600, y: 100 }, data: { label: 'Compare', pineType: 'pine_compare', operator: '>' } },
      { id: 'ps-cmp-rsi', type: 'pineScript', position: { x: 600, y: 230 }, data: { label: 'Compare', pineType: 'pine_compare', operator: '<' } },
      { id: 'ps-cmp-vwap', type: 'pineScript', position: { x: 600, y: 360 }, data: { label: 'Compare', pineType: 'pine_compare', operator: '>' } },
      { id: 'ps-and-1', type: 'pineScript', position: { x: 830, y: 160 }, data: { label: 'and', pineType: 'pine_and' } },
      { id: 'ps-and-2', type: 'pineScript', position: { x: 1000, y: 250 }, data: { label: 'and', pineType: 'pine_and' } },
      { id: 'ps-entry', type: 'pineScript', position: { x: 1200, y: 250 }, data: { label: 'strategy.entry', pineType: 'pine_strategy_entry', entryId: 'Long', direction: 'long' } },
    ],
    edges: [
      { id: 'pe1', source: 'ps-close', target: 'ps-ema', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe2', source: 'ps-close', target: 'ps-rsi', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe3', source: 'ps-close', target: 'ps-cmp-ema', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe4', source: 'ps-ema', target: 'ps-cmp-ema', sourceHandle: 'output', targetHandle: 'input-b' },
      { id: 'pe5', source: 'ps-rsi', target: 'ps-cmp-rsi', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe6', source: 'ps-close', target: 'ps-cmp-vwap', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe7', source: 'ps-vwap', target: 'ps-cmp-vwap', sourceHandle: 'output', targetHandle: 'input-b' },
      { id: 'pe8', source: 'ps-cmp-ema', target: 'ps-and-1', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe9', source: 'ps-cmp-rsi', target: 'ps-and-1', sourceHandle: 'output', targetHandle: 'input-b' },
      { id: 'pe10', source: 'ps-and-1', target: 'ps-and-2', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe11', source: 'ps-cmp-vwap', target: 'ps-and-2', sourceHandle: 'output', targetHandle: 'input-b' },
      { id: 'pe12', source: 'ps-and-2', target: 'ps-entry', sourceHandle: 'output', targetHandle: 'input' },
    ],
  },
  {
    id: 'pine-alert-system',
    name: 'Alert System Script',
    description: 'RSI-based alert indicator with plotshape markers and alertcondition for TradingView notifications.',
    category: 'pinescript',
    difficulty: 'beginner',
    indicators: ['ta.rsi'],
    nodes: [
      { id: 'ps-setup', type: 'pineScript', position: { x: 100, y: 50 }, data: { label: 'indicator()', pineType: 'pine_indicator', scriptTitle: 'RSI Alerts', overlay: true } },
      { id: 'ps-close', type: 'pineScript', position: { x: 100, y: 180 }, data: { label: 'close', pineType: 'pine_close' } },
      { id: 'ps-rsi', type: 'pineScript', position: { x: 350, y: 180 }, data: { label: 'ta.rsi', pineType: 'pine_ta_rsi', period: 14, source: 'close' } },
      { id: 'ps-cmp', type: 'pineScript', position: { x: 600, y: 180 }, data: { label: 'Compare', pineType: 'pine_compare', operator: '<' } },
      { id: 'ps-shape', type: 'pineScript', position: { x: 850, y: 130 }, data: { label: 'plotshape', pineType: 'pine_plotshape', plotColor: '#4CAF50' } },
      { id: 'ps-alert', type: 'pineScript', position: { x: 850, y: 260 }, data: { label: 'alertcondition', pineType: 'pine_alertcondition', alertMessage: 'RSI oversold — potential buy signal!' } },
      { id: 'ps-bgcolor', type: 'pineScript', position: { x: 850, y: 380 }, data: { label: 'bgcolor', pineType: 'pine_bgcolor', plotColor: '#4CAF50' } },
    ],
    edges: [
      { id: 'pe1', source: 'ps-close', target: 'ps-rsi', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe2', source: 'ps-rsi', target: 'ps-cmp', sourceHandle: 'output', targetHandle: 'input-a' },
      { id: 'pe3', source: 'ps-cmp', target: 'ps-shape', sourceHandle: 'output', targetHandle: 'input' },
      { id: 'pe4', source: 'ps-cmp', target: 'ps-alert', sourceHandle: 'output', targetHandle: 'input' },
      { id: 'pe5', source: 'ps-cmp', target: 'ps-bgcolor', sourceHandle: 'output', targetHandle: 'input' },
    ],
  },
];
