/**
 * Core strategy templates — trend, momentum, mean-reversion, breakout, portfolio, hedging, risk-management
 */

import { StrategyTemplate } from './types';

export const STRATEGY_TEMPLATES: StrategyTemplate[] = [
  {
    // Phase E reference template — RSI(14) mean-reversion on SPY with
    // stop-loss + take-profit + RSI-overbought exit. Carries a
    // `backtestSpec` so the Backtest button routes through the canonical
    // /api/backtest/run engine (same path agents use), guaranteeing
    // matching numbers across UI ↔ agent.
    id: 'rsi-mean-reversion-spy',
    name: 'RSI(14) Mean Reversion · SPY',
    description: 'Buy SPY when RSI(14) drops below 30 (oversold). Exit on RSI > 70, stop-loss -3%, take-profit +6%. Runs through the canonical backtest engine for byte-for-byte parity with the agent path.',
    category: 'mean-reversion',
    difficulty: 'beginner',
    indicators: ['RSI(14)'],
    featured: true,
    backtestSpec: {
      strategy: 'rsi_meanrev',
      params: { rsi_period: 14, oversold: 30, overbought: 70 },
      symbol: 'SPY',
      start: '2018-01-01',
      end: '2023-12-31',
      interval: '1d',
      initial_cash: 10_000,
      commission: 0.002,
    },
    nodes: [
      {
        id: 'rsi',
        type: 'indicator',
        position: { x: 80, y: 220 },
        data: { label: 'RSI(14)', indicatorType: 'rsi', timeframe: '1D', params: { period: 14 } },
      },
      {
        id: 'oversold-30',
        type: 'math',
        position: { x: 80, y: 360 },
        data: { label: '30', mathType: 'number', value: 30 },
      },
      {
        id: 'overbought-70',
        type: 'math',
        position: { x: 80, y: 80 },
        data: { label: '70', mathType: 'number', value: 70 },
      },
      {
        id: 'cond-oversold',
        type: 'condition',
        position: { x: 360, y: 280 },
        data: { label: 'RSI < 30', conditionType: 'compare', operator: '<' },
      },
      {
        id: 'cond-overbought',
        type: 'condition',
        position: { x: 360, y: 120 },
        data: { label: 'RSI > 70', conditionType: 'compare', operator: '>' },
      },
      {
        id: 'buy',
        type: 'action',
        position: { x: 660, y: 280 },
        data: {
          label: 'Buy 10%',
          actionType: 'order',
          direction: 'long',
          orderType: 'market',
          size: 10,
          sizeType: 'percent',
        },
      },
      {
        id: 'stop-loss',
        type: 'action',
        position: { x: 940, y: 220 },
        data: { label: 'Stop Loss -3%', actionType: 'stopLoss', stopDistance: 'percent', stopPercent: 3 },
      },
      {
        id: 'take-profit',
        type: 'action',
        position: { x: 940, y: 340 },
        data: { label: 'Take Profit +6%', actionType: 'takeProfit', profitDistance: 'percent', profitPercent: 6 },
      },
      {
        id: 'exit',
        type: 'action',
        position: { x: 660, y: 120 },
        data: { label: 'Close on RSI>70', actionType: 'closePosition' },
      },
    ],
    edges: [
      // Entry: RSI < 30  → Buy
      { id: 'e1', source: 'rsi', sourceHandle: 'value', target: 'cond-oversold', targetHandle: 'input-a' },
      { id: 'e2', source: 'oversold-30', sourceHandle: 'output', target: 'cond-oversold', targetHandle: 'input-b' },
      { id: 'e3', source: 'cond-oversold', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
      // Risk legs chain off the entry
      { id: 'e4', source: 'buy', sourceHandle: 'output', target: 'stop-loss', targetHandle: 'trigger' },
      { id: 'e5', source: 'buy', sourceHandle: 'output', target: 'take-profit', targetHandle: 'trigger' },
      // Exit: RSI > 70  → Close
      { id: 'e6', source: 'rsi', sourceHandle: 'value', target: 'cond-overbought', targetHandle: 'input-a' },
      { id: 'e7', source: 'overbought-70', sourceHandle: 'output', target: 'cond-overbought', targetHandle: 'input-b' },
      { id: 'e8', source: 'cond-overbought', sourceHandle: 'output', target: 'exit', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'sma-crossover',
    name: 'SMA Crossover',
    description: 'Classic moving average crossover strategy. Buy when fast MA crosses above slow MA.',
    category: 'trend',
    difficulty: 'beginner',
    indicators: ['SMA (Fast)', 'SMA (Slow)'],
    featured: true,
    nodes: [
      {
        id: 'sma-fast',
        type: 'indicator',
        position: { x: 100, y: 100 },
        data: { label: 'SMA (Fast)', indicatorType: 'sma', timeframe: '60', params: { period: 10 } },
      },
      {
        id: 'sma-slow',
        type: 'indicator',
        position: { x: 100, y: 220 },
        data: { label: 'SMA (Slow)', indicatorType: 'sma', timeframe: '60', params: { period: 20 } },
      },
      {
        id: 'crossover',
        type: 'condition',
        position: { x: 350, y: 160 },
        data: { label: 'Crossover', conditionType: 'crossover' },
      },
      {
        id: 'buy',
        type: 'action',
        position: { x: 600, y: 160 },
        data: { label: 'Buy', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' },
      },
    ],
    edges: [
      { id: 'e1', source: 'sma-fast', sourceHandle: 'value', target: 'crossover', targetHandle: 'input-a' },
      { id: 'e2', source: 'sma-slow', sourceHandle: 'value', target: 'crossover', targetHandle: 'input-b' },
      { id: 'e3', source: 'crossover', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'rsi-oversold',
    name: 'RSI Oversold',
    description: 'Mean reversion strategy. Buy when RSI drops below 30 (oversold).',
    category: 'mean-reversion',
    difficulty: 'beginner',
    indicators: ['RSI'],
    nodes: [
      {
        id: 'rsi',
        type: 'indicator',
        position: { x: 100, y: 150 },
        data: { label: 'RSI', indicatorType: 'rsi', timeframe: '60', params: { period: 14 } },
      },
      {
        id: 'constant-30',
        type: 'math',
        position: { x: 100, y: 280 },
        data: { label: '30', mathType: 'number', value: 30 },
      },
      {
        id: 'threshold',
        type: 'condition',
        position: { x: 350, y: 180 },
        data: { label: 'RSI < 30', conditionType: 'compare', operator: '<' },
      },
      {
        id: 'buy',
        type: 'action',
        position: { x: 600, y: 180 },
        data: { label: 'Buy', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' },
      },
    ],
    edges: [
      { id: 'e1', source: 'rsi', sourceHandle: 'value', target: 'threshold', targetHandle: 'input-a' },
      { id: 'e2', source: 'constant-30', sourceHandle: 'output', target: 'threshold', targetHandle: 'input-b' },
      { id: 'e3', source: 'threshold', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'macd-signal',
    name: 'MACD Signal Cross',
    description: 'Momentum strategy using MACD line crossing signal line.',
    category: 'momentum',
    difficulty: 'intermediate',
    indicators: ['MACD'],
    featured: true,
    nodes: [
      {
        id: 'macd',
        type: 'indicator',
        position: { x: 100, y: 150 },
        data: { label: 'MACD', indicatorType: 'macd', timeframe: '60', params: { fastPeriod: 12, slowPeriod: 26, signalPeriod: 9 } },
      },
      {
        id: 'crossover',
        type: 'condition',
        position: { x: 350, y: 150 },
        data: { label: 'MACD Crossover', conditionType: 'crossover' },
      },
      {
        id: 'buy',
        type: 'action',
        position: { x: 600, y: 150 },
        data: { label: 'Buy', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' },
      },
    ],
    edges: [
      { id: 'e1', source: 'macd', sourceHandle: 'line', target: 'crossover', targetHandle: 'input-a' },
      { id: 'e2', source: 'macd', sourceHandle: 'signal', target: 'crossover', targetHandle: 'input-b' },
      { id: 'e3', source: 'crossover', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'bb-breakout',
    name: 'Bollinger Band Breakout',
    description: 'Breakout strategy. Buy when price breaks above upper Bollinger Band.',
    category: 'breakout',
    difficulty: 'intermediate',
    indicators: ['Bollinger Bands'],
    nodes: [
      {
        id: 'bb',
        type: 'indicator',
        position: { x: 100, y: 150 },
        data: { label: 'Bollinger Bands', indicatorType: 'bb', timeframe: '60', params: { period: 20, stdDev: 2 } },
      },
      {
        id: 'price',
        type: 'environment',
        position: { x: 100, y: 280 },
        data: { label: 'Price', environmentType: 'price', priceType: 'mid' },
      },
      {
        id: 'compare',
        type: 'condition',
        position: { x: 350, y: 200 },
        data: { label: 'Price > Upper', conditionType: 'compare', operator: '>' },
      },
      {
        id: 'buy',
        type: 'action',
        position: { x: 600, y: 200 },
        data: { label: 'Buy', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' },
      },
    ],
    edges: [
      { id: 'e1', source: 'price', sourceHandle: 'value', target: 'compare', targetHandle: 'input-a' },
      { id: 'e2', source: 'bb', sourceHandle: 'upper', target: 'compare', targetHandle: 'input-b' },
      { id: 'e3', source: 'compare', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'triple-ema',
    name: 'Triple EMA',
    description: 'Advanced trend following with 3 EMAs for confirmation.',
    category: 'trend',
    difficulty: 'advanced',
    indicators: ['EMA (Fast)', 'EMA (Medium)', 'EMA (Slow)'],
    nodes: [
      {
        id: 'ema-fast',
        type: 'indicator',
        position: { x: 100, y: 80 },
        data: { label: 'EMA 9', indicatorType: 'ema', timeframe: '60', params: { period: 9 } },
      },
      {
        id: 'ema-medium',
        type: 'indicator',
        position: { x: 100, y: 200 },
        data: { label: 'EMA 21', indicatorType: 'ema', timeframe: '60', params: { period: 21 } },
      },
      {
        id: 'ema-slow',
        type: 'indicator',
        position: { x: 100, y: 320 },
        data: { label: 'EMA 55', indicatorType: 'ema', timeframe: '60', params: { period: 55 } },
      },
      {
        id: 'cross1',
        type: 'condition',
        position: { x: 350, y: 140 },
        data: { label: 'Fast > Medium', conditionType: 'compare', operator: '>' },
      },
      {
        id: 'cross2',
        type: 'condition',
        position: { x: 350, y: 260 },
        data: { label: 'Medium > Slow', conditionType: 'compare', operator: '>' },
      },
      {
        id: 'and',
        type: 'condition',
        position: { x: 550, y: 200 },
        data: { label: 'AND', conditionType: 'and' },
      },
      {
        id: 'buy',
        type: 'action',
        position: { x: 750, y: 200 },
        data: { label: 'Buy', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' },
      },
    ],
    edges: [
      { id: 'e1', source: 'ema-fast', sourceHandle: 'value', target: 'cross1', targetHandle: 'input-a' },
      { id: 'e2', source: 'ema-medium', sourceHandle: 'value', target: 'cross1', targetHandle: 'input-b' },
      { id: 'e3', source: 'ema-medium', sourceHandle: 'value', target: 'cross2', targetHandle: 'input-a' },
      { id: 'e4', source: 'ema-slow', sourceHandle: 'value', target: 'cross2', targetHandle: 'input-b' },
      { id: 'e5', source: 'cross1', sourceHandle: 'output', target: 'and', targetHandle: 'input-a' },
      { id: 'e6', source: 'cross2', sourceHandle: 'output', target: 'and', targetHandle: 'input-b' },
      { id: 'e7', source: 'and', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'statistical-arbitrage',
    name: 'Statistical Arbitrage',
    description: 'Pairs trading strategy. Exploit deviations in price relationships between correlated assets.',
    category: 'trading',
    difficulty: 'advanced',
    indicators: ['Asset Spread'],
    nodes: [
      {
        id: 'spread-ind',
        type: 'indicator',
        position: { x: 100, y: 150 },
        data: { label: 'Asset Spread', indicatorType: 'spread', timeframe: '60', params: { calculationType: 'ratio' } },
      },
      {
        id: 'constant-1_05',
        type: 'math',
        position: { x: 100, y: 280 },
        data: { label: '1.05', mathType: 'number', value: 1.05 },
      },
      {
        id: 'constant-0_95',
        type: 'math',
        position: { x: 100, y: 410 },
        data: { label: '0.95', mathType: 'number', value: 0.95 },
      },
      {
        id: 'compare-high',
        type: 'condition',
        position: { x: 350, y: 180 },
        data: { label: 'Spread > 1.05', conditionType: 'compare', operator: '>' },
      },
      {
        id: 'compare-low',
        type: 'condition',
        position: { x: 350, y: 310 },
        data: { label: 'Spread < 0.95', conditionType: 'compare', operator: '<' },
      },
      {
        id: 'short-pair',
        type: 'action',
        position: { x: 600, y: 180 },
        data: { label: 'Short Pair', actionType: 'order', direction: 'short', size: 10, sizeType: 'percent' },
      },
      {
        id: 'long-pair',
        type: 'action',
        position: { x: 600, y: 310 },
        data: { label: 'Long Pair', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' },
      },
    ],
    edges: [
      { id: 'e1', source: 'spread-ind', sourceHandle: 'value', target: 'compare-high', targetHandle: 'input-a' },
      { id: 'e2', source: 'constant-1_05', sourceHandle: 'output', target: 'compare-high', targetHandle: 'input-b' },
      { id: 'e3', source: 'spread-ind', sourceHandle: 'value', target: 'compare-low', targetHandle: 'input-a' },
      { id: 'e4', source: 'constant-0_95', sourceHandle: 'output', target: 'compare-low', targetHandle: 'input-b' },
      { id: 'e5', source: 'compare-high', sourceHandle: 'output', target: 'short-pair', targetHandle: 'trigger' },
      { id: 'e6', source: 'compare-low', sourceHandle: 'output', target: 'long-pair', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'hmm-regime-switching',
    name: 'HMM Regime-Switching',
    description: 'Detects market regimes using Hidden Markov Models and adapts strategy accordingly. Alternate between trending and mean-reversion.',
    category: 'trading',
    difficulty: 'advanced',
    indicators: ['HMM Regime'],
    nodes: [
      {
        id: 'hmm',
        type: 'indicator',
        position: { x: 100, y: 150 },
        data: { label: 'HMM Regime', indicatorType: 'hmm_regime', timeframe: '1D', params: { n_states: 2, feature: 'returns' } },
      },
      {
        id: 'constant-0',
        type: 'math',
        position: { x: 100, y: 280 },
        data: { label: '0 (Bull)', mathType: 'number', value: 0 },
      },
      {
        id: 'constant-1',
        type: 'math',
        position: { x: 100, y: 410 },
        data: { label: '1 (Bear)', mathType: 'number', value: 1 },
      },
      {
        id: 'is-bull',
        type: 'condition',
        position: { x: 350, y: 180 },
        data: { label: 'Is Bull Regime', conditionType: 'compare', operator: '==' },
      },
      {
        id: 'is-bear',
        type: 'condition',
        position: { x: 350, y: 310 },
        data: { label: 'Is Bear Regime', conditionType: 'compare', operator: '==' },
      },
      {
        id: 'buy',
        type: 'action',
        position: { x: 600, y: 180 },
        data: { label: 'Buy Asset', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' },
      },
      {
        id: 'sell',
        type: 'action',
        position: { x: 600, y: 310 },
        data: { label: 'Sell Asset', actionType: 'order', direction: 'short', size: 10, sizeType: 'percent' },
      },
    ],
    edges: [
      { id: 'e1', source: 'hmm', sourceHandle: 'value', target: 'is-bull', targetHandle: 'input-a' },
      { id: 'e2', source: 'constant-0', sourceHandle: 'output', target: 'is-bull', targetHandle: 'input-b' },
      { id: 'e3', source: 'hmm', sourceHandle: 'value', target: 'is-bear', targetHandle: 'input-a' },
      { id: 'e4', source: 'constant-1', sourceHandle: 'output', target: 'is-bear', targetHandle: 'input-b' },
      { id: 'e5', source: 'is-bull', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
      { id: 'e6', source: 'is-bear', sourceHandle: 'output', target: 'sell', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'diversification-allocation',
    name: 'Diversification & Allocation',
    description: 'Spread investments across asset classes and regions to reduce risk.',
    category: 'portfolio',
    difficulty: 'intermediate',
    indicators: [],
    nodes: [
      {
        id: 'heartbeat',
        type: 'trigger',
        position: { x: 100, y: 150 },
        data: { label: 'Monthly Run', triggerType: 'cronTrigger', cronExpression: '0 0 1 * *' },
      },
      {
        id: 'alloc-1',
        type: 'risk',
        position: { x: 350, y: 50 },
        data: { label: 'Stocks (60%)', riskType: 'portfolioAllocation', targetPercentage: 60 },
      },
      {
        id: 'alloc-2',
        type: 'risk',
        position: { x: 350, y: 150 },
        data: { label: 'Bonds (30%)', riskType: 'portfolioAllocation', targetPercentage: 30 },
      },
      {
        id: 'alloc-3',
        type: 'risk',
        position: { x: 350, y: 250 },
        data: { label: 'Gold (10%)', riskType: 'portfolioAllocation', targetPercentage: 10 },
      },
      {
        id: 'rebalance',
        type: 'action',
        position: { x: 600, y: 150 },
        data: { label: 'Rebalance Portfolio', actionType: 'portfolio_rebalance', rebalanceThresholdPercent: 5 },
      },
    ],
    edges: [
      { id: 'e1', source: 'heartbeat', sourceHandle: 'output', target: 'rebalance', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'portfolio-rebalancing',
    name: 'Portfolio Rebalancing',
    description: 'Restore original asset-allocation weights when performance divergence occurs.',
    category: 'portfolio',
    difficulty: 'beginner',
    indicators: [],
    nodes: [
      {
        id: 'heartbeat',
        type: 'trigger',
        position: { x: 100, y: 150 },
        data: { label: 'Weekly Check', triggerType: 'cronTrigger', cronExpression: '0 0 * * 5' },
      },
      {
        id: 'rebalance',
        type: 'action',
        position: { x: 350, y: 150 },
        data: { label: 'Rebalance (Threshold: 5%)', actionType: 'portfolio_rebalance', rebalanceThresholdPercent: 5 },
      },
    ],
    edges: [
      { id: 'e1', source: 'heartbeat', sourceHandle: 'output', target: 'rebalance', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'protective-put',
    name: 'Protective Put',
    description: 'Buy put options to cap downside in anticipated volatility or major events.',
    category: 'hedging',
    difficulty: 'intermediate',
    indicators: ['ATR'],
    nodes: [
      {
        id: 'atr',
        type: 'indicator',
        position: { x: 100, y: 150 },
        data: { label: 'ATR', indicatorType: 'atr', timeframe: '1D', params: { period: 14 } },
      },
      {
        id: 'constant',
        type: 'math',
        position: { x: 100, y: 280 },
        data: { label: 'High Volatility Threshold', mathType: 'number', value: 5.0 },
      },
      {
        id: 'compare',
        type: 'condition',
        position: { x: 350, y: 180 },
        data: { label: 'ATR > Threshold', conditionType: 'compare', operator: '>' },
      },
      {
        id: 'buy-put',
        type: 'action',
        position: { x: 600, y: 180 },
        data: { label: 'Buy Put', actionType: 'options_order', optionType: 'put', direction: 'buy', strike: 'OTM', size: 1 },
      },
    ],
    edges: [
      { id: 'e1', source: 'atr', sourceHandle: 'value', target: 'compare', targetHandle: 'input-a' },
      { id: 'e2', source: 'constant', sourceHandle: 'output', target: 'compare', targetHandle: 'input-b' },
      { id: 'e3', source: 'compare', sourceHandle: 'output', target: 'buy-put', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'options-collar',
    name: 'Options Collar',
    description: 'Combine long stock, long put and short call to reduce hedge cost. Caps upside but provides low-cost downside protection.',
    category: 'hedging',
    difficulty: 'advanced',
    indicators: [],
    nodes: [
      {
        id: 'heartbeat',
        type: 'trigger',
        position: { x: 100, y: 150 },
        data: { label: 'Monthly Rollover', triggerType: 'cronTrigger', cronExpression: '0 0 1 * *' },
      },
      {
        id: 'buy-put',
        type: 'action',
        position: { x: 350, y: 80 },
        data: { label: 'Buy Protective Put', actionType: 'options_order', optionType: 'put', direction: 'buy', strike: 'OTM', size: 1 },
      },
      {
        id: 'sell-call',
        type: 'action',
        position: { x: 350, y: 220 },
        data: { label: 'Sell Covered Call', actionType: 'options_order', optionType: 'call', direction: 'sell', strike: 'OTM', size: 1 },
      },
    ],
    edges: [
      { id: 'e1', source: 'heartbeat', sourceHandle: 'output', target: 'buy-put', targetHandle: 'trigger' },
      { id: 'e2', source: 'heartbeat', sourceHandle: 'output', target: 'sell-call', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'trailing-stop-loss',
    name: 'Trailing Stop Loss',
    description: 'Automatic orders to cut losses or lock in gains. Suitable for all traders for simple risk management.',
    category: 'risk-management',
    difficulty: 'beginner',
    indicators: ['SMA (Fast)', 'SMA (Slow)'],
    nodes: [
      {
        id: 'sma-fast',
        type: 'indicator',
        position: { x: 100, y: 100 },
        data: { label: 'SMA (Fast)', indicatorType: 'sma', timeframe: '60', params: { period: 10 } },
      },
      {
        id: 'sma-slow',
        type: 'indicator',
        position: { x: 100, y: 220 },
        data: { label: 'SMA (Slow)', indicatorType: 'sma', timeframe: '60', params: { period: 20 } },
      },
      {
        id: 'crossover',
        type: 'condition',
        position: { x: 350, y: 160 },
        data: { label: 'Crossover', conditionType: 'crossover' },
      },
      {
        id: 'buy',
        type: 'action',
        position: { x: 600, y: 160 },
        data: { label: 'Buy', actionType: 'order', direction: 'long', size: 10, sizeType: 'percent' },
      },
      {
        id: 'trailing-stop',
        type: 'action',
        position: { x: 800, y: 160 },
        data: { label: 'Set Trailing Stop', actionType: 'trailingStop', trailingDistance: 5 },
      },
    ],
    edges: [
      { id: 'e1', source: 'sma-fast', sourceHandle: 'value', target: 'crossover', targetHandle: 'input-a' },
      { id: 'e2', source: 'sma-slow', sourceHandle: 'value', target: 'crossover', targetHandle: 'input-b' },
      { id: 'e3', source: 'crossover', sourceHandle: 'output', target: 'buy', targetHandle: 'trigger' },
      { id: 'e4', source: 'buy', sourceHandle: 'next', target: 'trailing-stop', targetHandle: 'trigger' },
    ],
  },
  {
    id: 'inverse-etf-hedging',
    name: 'Inverse ETF Hedging',
    description: 'Profit when underlying declines. Used to hedge broad market exposure.',
    category: 'hedging',
    difficulty: 'intermediate',
    indicators: ['SMA'],
    nodes: [
      {
        id: 'sma',
        type: 'indicator',
        position: { x: 100, y: 150 },
        data: { label: 'SMA (200)', indicatorType: 'sma', timeframe: '1D', params: { period: 200 } },
      },
      {
        id: 'price',
        type: 'environment',
        position: { x: 100, y: 280 },
        data: { label: 'Price', environmentType: 'price', priceType: 'close' },
      },
      {
        id: 'compare',
        type: 'condition',
        position: { x: 350, y: 200 },
        data: { label: 'Price < SMA', conditionType: 'compare', operator: '<' },
      },
      {
        id: 'buy-inverse',
        type: 'action',
        position: { x: 600, y: 200 },
        data: { label: 'Buy Inverse ETF', actionType: 'order', direction: 'long', size: 15, sizeType: 'percent' },
      },
    ],
    edges: [
      { id: 'e1', source: 'price', sourceHandle: 'value', target: 'compare', targetHandle: 'input-a' },
      { id: 'e2', source: 'sma', sourceHandle: 'value', target: 'compare', targetHandle: 'input-b' },
      { id: 'e3', source: 'compare', sourceHandle: 'output', target: 'buy-inverse', targetHandle: 'trigger' },
    ],
  },
];
