/**
 * Action Nodes - Trading execution nodes for the strategy builder
 */
import { NodeCatalogItem } from '../../types';

export const ACTION_NODES: NodeCatalogItem[] = [
    {
        type: 'order',
        nodeType: 'action',
        label: 'Place Order',
        description: 'Execute a trade',
        tooltip: 'Open a long or short position with specified size. Choose market, limit, or stop order type.',
        inputs: ['Trigger', 'Size'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Orders',
        icon: 'ShoppingCart',
        color: '#10b981',
        defaultData: { actionType: 'order', direction: 'long', orderType: 'market', size: 0.1, sizeType: 'lots' },
    },
    {
        type: 'closePosition',
        nodeType: 'action',
        label: 'Close Position',
        description: 'Exit current trade',
        tooltip: 'Close the current open position. Use with conditions to implement exit logic.',
        inputs: ['Trigger'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Orders',
        icon: 'XCircle',
        color: '#ef4444',
        defaultData: { actionType: 'closePosition' },
    },
    {
        type: 'closeAll',
        nodeType: 'action',
        label: 'Close All',
        description: 'Exit all positions',
        tooltip: 'Close all open positions at once. Useful for end-of-day or emergency exits.',
        inputs: ['Trigger'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Orders',
        icon: 'XSquare',
        color: '#ef4444',
        defaultData: { actionType: 'closeAll' },
    },
    {
        type: 'stopLoss',
        nodeType: 'action',
        label: 'Stop Loss',
        description: 'Set exit on loss',
        tooltip: 'Automatically exit if price moves against you. Essential for risk management.',
        inputs: ['Trigger', 'Price'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Risk Management',
        icon: 'Shield',
        color: '#f59e0b',
        defaultData: { actionType: 'stopLoss', stopPrice: 0 },
    },
    {
        type: 'takeProfit',
        nodeType: 'action',
        label: 'Take Profit',
        description: 'Set exit on profit',
        tooltip: 'Automatically exit when price reaches profit target. Lock in gains.',
        inputs: ['Trigger', 'Price'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Risk Management',
        icon: 'Target',
        color: '#22c55e',
        defaultData: { actionType: 'takeProfit', takeProfitPrice: 0 },
    },
    {
        type: 'trailingStop',
        nodeType: 'action',
        label: 'Trailing Stop',
        description: 'Dynamic stop loss',
        tooltip: 'Stop that follows price movement. Locks in profits while allowing upside.',
        inputs: ['Trigger'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Risk Management',
        icon: 'GitBranch',
        color: '#f59e0b',
        defaultData: { actionType: 'trailingStop', trailingDistance: 10 },
    },
    {
        type: 'notification',
        nodeType: 'action',
        label: 'Notification',
        description: 'Send alert',
        tooltip: 'Send alert via Telegram, Discord, or email when conditions are met.',
        inputs: ['Trigger'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Alerts',
        icon: 'Bell',
        color: '#ec4899',
        defaultData: { actionType: 'notification', message: 'Signal triggered', channel: 'telegram' },
    },
    {
        type: 'log',
        nodeType: 'action',
        label: 'Log',
        description: 'Log message',
        tooltip: 'Log a message to console for debugging and strategy analysis.',
        inputs: ['Trigger'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Alerts',
        icon: 'FileText',
        color: '#6b7280',
        defaultData: { actionType: 'log', message: 'Log message' },
    },
    {
        type: 'options_order',
        nodeType: 'action',
        label: 'Options Order',
        description: 'Buy/Sell Calls and Puts',
        tooltip: 'Place an order for options contracts. Used for hedging (protective puts, collars) or speculation.',
        inputs: ['Trigger', 'Size'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Orders',
        icon: 'ShoppingCart',
        color: '#10b981',
        defaultData: { actionType: 'options_order', optionType: 'put', direction: 'buy', strike: 'ATM', expiration: 'next_month', size: 1, sizeType: 'contracts' },
    },
    {
        type: 'portfolio_rebalance',
        nodeType: 'action',
        label: 'Portfolio Rebalance',
        description: 'Rebalance to target weights',
        tooltip: 'Automatically buys and sells assets to restore the portfolio to its target allocation weights.',
        inputs: ['Trigger'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Portfolio',
        icon: 'PieChart',
        color: '#8b5cf6',
        defaultData: { actionType: 'portfolio_rebalance', rebalanceThresholdPercent: 5 },
    },
    {
        type: 'phoneCall',
        nodeType: 'action',
        label: 'Phone Call',
        description: 'Call user with alert',
        tooltip: 'Place an automated phone call to notify you of urgent opportunities or risks. Uses Twilio Voice API. Reads a text-to-speech message with the alert details.',
        inputs: ['Trigger'],
        outputs: ['Signal'],
        category: 'actions',
        subcategory: 'Alerts',
        icon: 'Phone',
        color: '#ef4444',
        defaultData: { actionType: 'phoneCall', phoneNumber: '', message: 'Urgent trading alert', voiceType: 'alice', urgencyLevel: 'high' },
    },
];
