/**
 * Agent Nodes — ADK Agent integration nodes for the strategy canvas.
 * Each node runs a specific ADK agent and outputs its analysis results.
 */
import { NodeCatalogItem } from '../../types';

export const AGENT_NODES: NodeCatalogItem[] = [
    // =========================================================================
    // Analysis Agents
    // =========================================================================
    {
        type: 'newsAgentNode',
        nodeType: 'agent',
        label: 'News Analyst',
        description: 'AI news impact analysis',
        tooltip: 'Analyzes recent news headlines against your portfolio holdings. Uses LLM to assess sentiment, relevance, and impact. Outputs actionable signals (bullish/bearish) with confidence scores.',
        inputs: ['Trigger', 'Symbols'],
        outputs: ['Signal', 'Confidence', 'Findings'],
        category: 'agents',
        subcategory: 'Analysis',
        icon: 'Newspaper',
        color: '#3b82f6',
        backtestEligible: false,
        defaultData: {
            agentNodeType: 'newsAgentNode',
            agentType: 'news_analyst',
            model: 'gemini-2.0-flash',
            symbols: [],
            confidenceThreshold: 0.5,
        },
    },
    {
        type: 'macroAgentNode',
        nodeType: 'agent',
        label: 'Macro Analyst',
        description: 'Macroeconomic analysis',
        tooltip: 'Analyzes macroeconomic indicators (CPI, GDP, rates, employment) and their impact on your portfolio. Classifies the current macro regime and identifies risk/opportunity flags.',
        inputs: ['Trigger', 'Symbols'],
        outputs: ['Signal', 'Confidence', 'Findings'],
        category: 'agents',
        subcategory: 'Analysis',
        icon: 'Globe',
        color: '#8b5cf6',
        backtestEligible: false,
        defaultData: {
            agentNodeType: 'macroAgentNode',
            agentType: 'macro_analyst',
            model: 'gemini-2.0-flash',
            symbols: [],
            confidenceThreshold: 0.5,
        },
    },
    {
        type: 'technicalAgentNode',
        nodeType: 'agent',
        label: 'Technical Analyst',
        description: 'AI technical analysis',
        tooltip: 'Runs comprehensive technical analysis using indicators, candlestick patterns, support/resistance levels, and market regime classification. Provides directional signals with confidence.',
        inputs: ['Trigger', 'Symbols'],
        outputs: ['Signal', 'Confidence', 'Findings'],
        category: 'agents',
        subcategory: 'Analysis',
        icon: 'LineChart',
        color: '#06b6d4',
        backtestEligible: false,
        defaultData: {
            agentNodeType: 'technicalAgentNode',
            agentType: 'technical_analyst',
            model: 'gemini-2.0-flash',
            symbols: [],
            confidenceThreshold: 0.5,
        },
    },
    {
        type: 'socialAgentNode',
        nodeType: 'agent',
        label: 'Social Monitor',
        description: 'Social media sentiment',
        tooltip: 'Monitors social media feeds (Twitter/X, Reddit) for sentiment shifts and trending discussions about your portfolio holdings. Detects viral posts and sentiment extremes.',
        inputs: ['Trigger', 'Symbols'],
        outputs: ['Signal', 'Confidence', 'Findings'],
        category: 'agents',
        subcategory: 'Analysis',
        icon: 'MessageCircle',
        color: '#ec4899',
        backtestEligible: false,
        defaultData: {
            agentNodeType: 'socialAgentNode',
            agentType: 'social_monitor',
            model: 'gemini-2.0-flash',
            symbols: [],
            confidenceThreshold: 0.5,
        },
    },
    // =========================================================================
    // Synthesis Agents
    // =========================================================================
    {
        type: 'synthesisAgentNode',
        nodeType: 'agent',
        label: 'Synthesis Agent',
        description: 'Multi-source synthesis',
        tooltip: 'Combines outputs from multiple analyst agents into a unified recommendation. Weighs conflicting signals, identifies consensus, and produces a final actionable view with confidence scoring.',
        inputs: ['Trigger', 'Symbols', 'Agent Data'],
        outputs: ['Signal', 'Confidence', 'Recommendation'],
        category: 'agents',
        subcategory: 'Synthesis',
        icon: 'Sparkles',
        color: '#f59e0b',
        backtestEligible: false,
        defaultData: {
            agentNodeType: 'synthesisAgentNode',
            agentType: 'synthesis',
            model: 'gemini-2.0-flash',
            symbols: [],
            confidenceThreshold: 0.6,
        },
    },
    {
        type: 'fundamentalsAgentNode',
        nodeType: 'agent',
        label: 'Fundamentals Agent',
        description: 'Financial health analysis',
        tooltip: 'Analyzes company fundamentals: financial ratios, growth metrics, profitability, and balance sheet health. Compares against peers and provides a financial health score.',
        inputs: ['Trigger', 'Symbols'],
        outputs: ['Signal', 'Confidence', 'Findings'],
        category: 'agents',
        subcategory: 'Analysis',
        icon: 'Building2',
        color: '#10b981',
        backtestEligible: false,
        defaultData: {
            agentNodeType: 'fundamentalsAgentNode',
            agentType: 'fundamentals_analyst',
            model: 'gemini-2.0-flash',
            symbols: [],
            confidenceThreshold: 0.5,
        },
    },
    {
        type: 'sentimentAgentNode',
        nodeType: 'agent',
        label: 'Sentiment Agent',
        description: 'Multi-source sentiment fusion',
        tooltip: 'Fuses sentiment from news, social media, and options flow into a composite sentiment score. Detects sentiment divergences and extreme readings that may signal turning points.',
        inputs: ['Trigger', 'Symbols'],
        outputs: ['Signal', 'Confidence', 'Score'],
        category: 'agents',
        subcategory: 'Analysis',
        icon: 'Heart',
        color: '#ef4444',
        backtestEligible: false,
        defaultData: {
            agentNodeType: 'sentimentAgentNode',
            agentType: 'sentiment_analyst',
            model: 'gemini-2.0-flash',
            symbols: [],
            confidenceThreshold: 0.5,
        },
    },
];
