/**
 * Condition Nodes - Logic and comparison nodes for the strategy builder
 */
import { NodeCatalogItem } from '../../types';

export const CONDITION_NODES: NodeCatalogItem[] = [
    {
        type: 'compare',
        nodeType: 'condition',
        label: 'Compare',
        description: 'Compare two values',
        tooltip: 'Compare A vs B using operators (>, <, ==, etc.). Returns true/false for use in If nodes.',
        inputs: ['Number', 'Number'],
        outputs: ['Boolean'],
        category: 'conditions',
        icon: 'GitCompare',
        color: '#f59e0b',
        defaultData: { conditionType: 'compare', operator: '>' },
    },
    {
        type: 'crossover',
        nodeType: 'condition',
        label: 'Crossover',
        description: 'A crosses above B',
        tooltip: 'Triggers when value A crosses above value B. Classic signal for MA crossover strategies.',
        inputs: ['Number', 'Number'],
        outputs: ['Boolean'],
        category: 'conditions',
        icon: 'ArrowUpRight',
        color: '#22c55e',
        defaultData: { conditionType: 'crossover' },
    },
    {
        type: 'crossunder',
        nodeType: 'condition',
        label: 'Crossunder',
        description: 'A crosses below B',
        tooltip: 'Triggers when value A crosses below value B. Used for exit signals or short entries.',
        inputs: ['Number', 'Number'],
        outputs: ['Boolean'],
        category: 'conditions',
        icon: 'ArrowDownRight',
        color: '#ef4444',
        defaultData: { conditionType: 'crossunder' },
    },
    {
        type: 'threshold',
        nodeType: 'condition',
        label: 'Threshold',
        description: 'Check against fixed value',
        tooltip: 'Check if an indicator value is above or below a specific level (e.g., RSI > 70).',
        inputs: ['Number'],
        outputs: ['Boolean'],
        category: 'conditions',
        icon: 'Minus',
        color: '#f59e0b',
        defaultData: { conditionType: 'threshold', operator: '>', value: 70 },
    },
    {
        type: 'range',
        nodeType: 'condition',
        label: 'In Range',
        description: 'Value within min/max',
        tooltip: 'Check if value falls between minimum and maximum bounds. Useful for RSI neutral zones.',
        inputs: ['Number'],
        outputs: ['Boolean'],
        category: 'conditions',
        icon: 'Maximize2',
        color: '#f59e0b',
        defaultData: { conditionType: 'range', minValue: 30, maxValue: 70 },
    },
    {
        type: 'and',
        nodeType: 'condition',
        label: 'AND',
        description: 'Both must be true',
        tooltip: 'Logical AND: Both conditions must be true. Combine multiple signals for confirmation.',
        inputs: ['Boolean', 'Boolean'],
        outputs: ['Boolean'],
        category: 'conditions',
        icon: 'Plus',
        color: '#6366f1',
        defaultData: { conditionType: 'and' },
    },
    {
        type: 'or',
        nodeType: 'condition',
        label: 'OR',
        description: 'Either can be true',
        tooltip: 'Logical OR: Either condition being true triggers. Use for multiple entry criteria.',
        inputs: ['Boolean', 'Boolean'],
        outputs: ['Boolean'],
        category: 'conditions',
        icon: 'Slash',
        color: '#6366f1',
        defaultData: { conditionType: 'or' },
    },
    {
        type: 'not',
        nodeType: 'condition',
        label: 'NOT',
        description: 'Invert condition',
        tooltip: 'Logical NOT: Inverts true to false and vice versa.',
        inputs: ['Boolean'],
        outputs: ['Boolean'],
        category: 'conditions',
        icon: 'X',
        color: '#6366f1',
        defaultData: { conditionType: 'not' },
    },
];
