/**
 * Control Flow Nodes - Logic flow control for the strategy builder
 */
import { NodeCatalogItem } from '../../types';

export const CONTROL_NODES: NodeCatalogItem[] = [
    {
        type: 'if',
        nodeType: 'control',
        label: 'If',
        description: 'Conditional execution',
        tooltip: 'Execute actions only when condition is true. Core building block for strategy logic.',
        inputs: ['Boolean'],
        outputs: ['Signal'],
        category: 'control',
        subcategory: 'Conditionals',
        icon: 'GitBranch',
        color: '#f59e0b',
        defaultData: { controlType: 'if' },
    },
    {
        type: 'ifElse',
        nodeType: 'control',
        label: 'If-Else',
        description: 'Branch based on condition',
        tooltip: 'Execute different actions based on condition. True path vs False path.',
        inputs: ['Boolean'],
        outputs: ['Then', 'Else'],
        category: 'control',
        subcategory: 'Conditionals',
        icon: 'GitMerge',
        color: '#f59e0b',
        defaultData: { controlType: 'ifElse' },
    },
    {
        type: 'repeat',
        nodeType: 'control',
        label: 'Repeat',
        description: 'Loop N times',
        tooltip: 'Repeat actions a specific number of times. Use for grid-based or pyramid entries.',
        inputs: [],
        outputs: ['Signal'],
        category: 'control',
        subcategory: 'Loops',
        icon: 'RefreshCw',
        color: '#06b6d4',
        defaultData: { controlType: 'repeat', repeatCount: 10 },
    },
    {
        type: 'wait',
        nodeType: 'control',
        label: 'Wait',
        description: 'Delay execution',
        tooltip: 'Pause strategy execution for specified seconds. Add time buffers.',
        inputs: ['Trigger'],
        outputs: ['Signal'],
        category: 'control',
        subcategory: 'Timing',
        icon: 'Timer',
        color: '#8b5cf6',
        defaultData: { controlType: 'wait', waitSeconds: 1 },
    },
    {
        type: 'waitUntil',
        nodeType: 'control',
        label: 'Wait Until',
        description: 'Wait for condition',
        tooltip: 'Pause until a condition becomes true. Wait for price levels or time.',
        inputs: ['Boolean'],
        outputs: ['Signal'],
        category: 'control',
        subcategory: 'Timing',
        icon: 'TimerOff',
        color: '#8b5cf6',
        defaultData: { controlType: 'waitUntil' },
    },
    {
        type: 'stop',
        nodeType: 'control',
        label: 'Stop',
        description: 'Halt strategy',
        tooltip: 'Immediately stop strategy execution. Emergency brake.',
        inputs: ['Trigger'],
        outputs: [],
        category: 'control',
        subcategory: 'Flow',
        icon: 'Square',
        color: '#ef4444',
        defaultData: { controlType: 'stop' },
    },
];
