/**
 * Control Flow Nodes - Logic flow control for the strategy builder
 */
import { NodeCatalogItem } from '../../types';

export const CONTROL_NODES: NodeCatalogItem[] = [
    {
        type: 'if',
        nodeType: 'control',
        label: 'If',
        description: 'Conditional execution',
        tooltip: 'Execute actions only when condition is true. Core building block for strategy logic.',
        inputs: ['Boolean'],
        outputs: ['Signal'],
        category: 'control',
        subcategory: 'Conditionals',
        icon: 'GitBranch',
        color: '#f59e0b',
        defaultData: { controlType: 'if' },
    },
    {
        type: 'ifElse',
        nodeType: 'control',
        label: 'If-Else',
        description: 'Branch based on condition',
        tooltip: 'Execute different actions based on condition. True path vs False path.',
        inputs: ['Boolean'],
        outputs: ['Then', 'Else'],
        category: 'control',
        subcategory: 'Conditionals',
        icon: 'GitMerge',
        color: '#f59e0b',
        defaultData: { controlType: 'ifElse' },
    },
    {
        type: 'repeat',
        nodeType: 'control',
        label: 'Repeat',
        description: 'Loop N times',
        tooltip: 'Repeat actions a specific number of times. Use for grid-based or pyramid entries.',
        inputs: [],
        outputs: ['Signal'],
        category: 'control',
        subcategory: 'Loops',
        icon: 'RefreshCw',
        color: '#06b6d4',
        defaultData: { controlType: 'repeat', repeatCount: 10 },
    },
    {
        type: 'wait',
        nodeType: 'control',
        label: 'Wait',
        description: 'Delay execution',
        tooltip: 'Pause strategy execution for specified seconds. Add time buffers.',
        inputs: ['Trigger'],
        outputs: ['Signal'],
        category: 'control',
        subcategory: 'Timing',
        icon: 'Timer',
        color: '#8b5cf6',
        defaultData: { controlType: 'wait', waitSeconds: 1 },
    },
    {
        type: 'waitUntil',
        nodeType: 'control',
        label: 'Wait Until',
        description: 'Wait for condition',
        tooltip: 'Pause until a condition becomes true. Wait for price levels or time.',
        inputs: ['Boolean'],
        outputs: ['Signal'],
        category: 'control',
        subcategory: 'Timing',
        icon: 'TimerOff',
        color: '#8b5cf6',
        defaultData: { controlType: 'waitUntil' },
    },
    {
        type: 'stop',
        nodeType: 'control',
        label: 'Stop',
        description: 'Halt strategy',
        tooltip: 'Immediately stop strategy execution. Emergency brake.',
        inputs: ['Trigger'],
        outputs: [],
        category: 'control',
        subcategory: 'Flow',
        icon: 'Square',
        color: '#ef4444',
        defaultData: { controlType: 'stop' },
    },
    {
        type: 'switch',
        nodeType: 'control',
        label: 'Switch',
        description: 'Route to N branches by case',
        tooltip: 'Evaluate an input value against N case expressions and route the signal to the matching output branch (or "Default" if none match). Inspired by n8n\'s Switch node — use when If/IfElse becomes a chain of nested branches.',
        inputs: ['Value'],
        outputs: ['Case 1', 'Case 2', 'Case 3', 'Default'],
        category: 'control',
        subcategory: 'Conditionals',
        icon: 'GitFork',
        color: '#f59e0b',
        backtestEligible: true,
        defaultData: {
            controlType: 'switch',
            // Each rule: { operator: 'eq'|'gt'|'lt'|'gte'|'lte'|'between'|'in', value: any, outputIndex: number }
            rules: [
                { operator: 'eq', value: 0, outputIndex: 0 },
                { operator: 'gt', value: 0, outputIndex: 1 },
                { operator: 'lt', value: 0, outputIndex: 2 },
            ],
            defaultOutputIndex: 3,
        },
    },
    {
        type: 'splitInBatches',
        nodeType: 'control',
        label: 'Split In Batches',
        description: 'Iterate a list in batches of N',
        tooltip: 'Process a list of items (e.g. tickers from a screener) in batches. Each tick emits one batch of size `batchSize`; downstream nodes process the batch and the loop continues until the list is exhausted. Inspired by n8n\'s Split In Batches — distinct from Split Out which fans out one item per branch.',
        inputs: ['List'],
        outputs: ['Batch', 'Done'],
        category: 'control',
        subcategory: 'Loops',
        icon: 'Layers',
        color: '#06b6d4',
        backtestEligible: true,
        defaultData: {
            controlType: 'splitInBatches',
            batchSize: 10,
            // 'sequential' processes batches one at a time; 'parallel' fans out concurrently.
            mode: 'sequential',
        },
    },
];
