/**
 * Environment Nodes - Market data and time inputs
 */
import { NodeCatalogItem } from '../../types';

export const ENVIRONMENT_NODES: NodeCatalogItem[] = [
    {
        type: 'price',
        nodeType: 'environment',
        label: 'Current Price',
        description: 'Live market price',
        tooltip: 'Get current bid, ask, or mid price. Foundation for most trading logic.',
        inputs: [],
        outputs: ['Number'],
        category: 'environment',
        subcategory: 'Price',
        icon: 'DollarSign',
        color: '#6366f1',
        defaultData: { environmentType: 'price', priceType: 'mid' },
    },
    {
        type: 'spread',
        nodeType: 'environment',
        label: 'Spread',
        description: 'Bid-Ask spread',
        tooltip: 'Current spread in pips. Use to avoid trading during high-spread periods.',
        inputs: [],
        outputs: ['Number'],
        category: 'environment',
        subcategory: 'Price',
        icon: 'ArrowLeftRight',
        color: '#6366f1',
        defaultData: { environmentType: 'spread' },
    },
    {
        type: 'prevCandleOpen',
        nodeType: 'environment',
        label: 'Prev Open',
        description: 'Previous candle open',
        tooltip: 'Get the open price of a previous candle. Shift parameter controls how many bars back.',
        inputs: [],
        outputs: ['Number'],
        category: 'environment',
        subcategory: 'Price',
        icon: 'BarChart2',
        color: '#6366f1',
        defaultData: { environmentType: 'prevCandleOpen', shift: 1 },
    },
    {
        type: 'prevCandleClose',
        nodeType: 'environment',
        label: 'Prev Close',
        description: 'Previous candle close',
        tooltip: 'Get the close price of a previous candle. Essential for confirmation signals.',
        inputs: [],
        outputs: ['Number'],
        category: 'environment',
        subcategory: 'Price',
        icon: 'BarChart2',
        color: '#6366f1',
        defaultData: { environmentType: 'prevCandleClose', shift: 1 },
    },
    {
        type: 'time',
        nodeType: 'environment',
        label: 'Current Time',
        description: 'Current timestamp',
        tooltip: 'Get current time. Use for session-based trading strategies.',
        inputs: [],
        outputs: ['Time'],
        category: 'environment',
        subcategory: 'Time',
        icon: 'Clock',
        color: '#8b5cf6',
        defaultData: { environmentType: 'time' },
    },
    {
        type: 'dayOfWeek',
        nodeType: 'environment',
        label: 'Day of Week',
        description: 'Current weekday (0-6)',
        tooltip: 'Get day of week (0=Sunday). Filter trades to specific days.',
        inputs: [],
        outputs: ['Number'],
        category: 'environment',
        subcategory: 'Time',
        icon: 'Calendar',
        color: '#8b5cf6',
        defaultData: { environmentType: 'dayOfWeek' },
    },
    {
        type: 'newCandleOpen',
        nodeType: 'environment',
        label: 'New Candle',
        description: 'Candle open trigger',
        tooltip: 'Triggers once when a new candle opens. Use to run logic only at bar close.',
        inputs: [],
        outputs: ['Boolean'],
        category: 'environment',
        subcategory: 'Time',
        icon: 'PlayCircle',
        color: '#8b5cf6',
        defaultData: { environmentType: 'newCandleOpen' },
    },
    {
        type: 'isMarketOpen',
        nodeType: 'environment',
        label: 'Market Open',
        description: 'Is market trading?',
        tooltip: 'Check if market is currently open. Prevent trading during closed hours.',
        inputs: [],
        outputs: ['Boolean'],
        category: 'environment',
        subcategory: 'Time',
        icon: 'ToggleLeft',
        color: '#8b5cf6',
        defaultData: { environmentType: 'isMarketOpen' },
    },
];
