/**
 * Indicator Nodes - Technical Analysis indicators for the strategy builder
 */
import { NodeCatalogItem } from '../../types';

export const INDICATOR_NODES: NodeCatalogItem[] = [
    // ═══════════════════════════════════════════════════════════════════════════
    // MOVING AVERAGES
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'sma',
        nodeType: 'indicator',
        label: 'SMA',
        description: 'Simple Moving Average',
        tooltip: 'Calculates the average price over N periods. Use to identify trend direction and potential support/resistance levels.',
        inputs: ['Price Data'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Moving Averages',
        icon: 'TrendingUp',
        color: '#8b5cf6',
        defaultData: { indicatorType: 'sma', timeframe: '60', params: { period: 14, priceType: 'close' } },
    },
    {
        type: 'ema',
        nodeType: 'indicator',
        label: 'EMA',
        description: 'Exponential Moving Average',
        tooltip: 'Weighted average giving more importance to recent prices. More responsive to price changes than SMA.',
        inputs: ['Price Data'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Moving Averages',
        icon: 'TrendingUp',
        color: '#8b5cf6',
        defaultData: { indicatorType: 'ema', timeframe: '60', params: { period: 14, priceType: 'close' } },
    },
    {
        type: 'dema',
        nodeType: 'indicator',
        label: 'DEMA',
        description: 'Double Exponential Moving Average',
        tooltip: 'Reduces lag by applying EMA twice. Faster response to price changes.',
        inputs: ['Price Data'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Moving Averages',
        icon: 'TrendingUp',
        color: '#8b5cf6',
        defaultData: { indicatorType: 'dema', timeframe: '60', params: { period: 14, priceType: 'close' } },
    },
    {
        type: 'tema',
        nodeType: 'indicator',
        label: 'TEMA',
        description: 'Triple Exponential Moving Average',
        tooltip: 'Triple smoothing for minimal lag. Best for fast-moving markets.',
        inputs: ['Price Data'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Moving Averages',
        icon: 'TrendingUp',
        color: '#8b5cf6',
        defaultData: { indicatorType: 'tema', timeframe: '60', params: { period: 14, priceType: 'close' } },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // OSCILLATORS
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'rsi',
        nodeType: 'indicator',
        label: 'RSI',
        description: 'Relative Strength Index',
        tooltip: 'Measures momentum on a 0-100 scale. Above 70 = overbought, below 30 = oversold.',
        inputs: ['Price Data'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Oscillators',
        icon: 'Activity',
        color: '#06b6d4',
        defaultData: { indicatorType: 'rsi', timeframe: '60', params: { period: 14 } },
    },
    {
        type: 'stochastic',
        nodeType: 'indicator',
        label: 'Stochastic',
        description: 'Stochastic Oscillator',
        tooltip: 'Compares closing price to price range. %K and %D lines signal momentum shifts.',
        inputs: ['Price Data'],
        outputs: ['%K', '%D'],
        category: 'indicators',
        subcategory: 'Oscillators',
        icon: 'Activity',
        color: '#06b6d4',
        defaultData: { indicatorType: 'stochastic', timeframe: '60', params: { kPeriod: 5, dPeriod: 3, slowing: 3 } },
    },
    {
        type: 'cci',
        nodeType: 'indicator',
        label: 'CCI',
        description: 'Commodity Channel Index',
        tooltip: 'Measures deviation from average price. +100/-100 indicate overbought/oversold.',
        inputs: ['Price Data'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Oscillators',
        icon: 'Activity',
        color: '#06b6d4',
        defaultData: { indicatorType: 'cci', timeframe: '60', params: { period: 20 } },
    },
    {
        type: 'mfi',
        nodeType: 'indicator',
        label: 'MFI',
        description: 'Money Flow Index',
        tooltip: 'Volume-weighted RSI. Measures buying/selling pressure with volume confirmation.',
        inputs: ['Price Data', 'Volume'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Oscillators',
        icon: 'Activity',
        color: '#06b6d4',
        defaultData: { indicatorType: 'mfi', timeframe: '60', params: { period: 14 } },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // MACD & TREND
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'macd',
        nodeType: 'indicator',
        label: 'MACD',
        description: 'Moving Average Convergence Divergence',
        tooltip: 'Shows relationship between two EMAs. Signal line crossovers indicate momentum shifts.',
        inputs: ['Price Data'],
        outputs: ['Line', 'Signal', 'Histogram'],
        category: 'indicators',
        subcategory: 'Trend',
        icon: 'BarChart2',
        color: '#f59e0b',
        defaultData: { indicatorType: 'macd', timeframe: '60', params: { fastPeriod: 12, slowPeriod: 26, signalPeriod: 9 } },
    },
    {
        type: 'adx',
        nodeType: 'indicator',
        label: 'ADX',
        description: 'Average Directional Index',
        tooltip: 'Measures trend strength (not direction). Above 25 = strong trend, below 20 = weak/ranging.',
        inputs: ['Price Data'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Trend',
        icon: 'TrendingUp',
        color: '#8b5cf6',
        defaultData: { indicatorType: 'adx', timeframe: '60', params: { period: 14 } },
    },
    {
        type: 'sar',
        nodeType: 'indicator',
        label: 'Parabolic SAR',
        description: 'Stop and Reverse',
        tooltip: 'Trailing stop indicator. Dots flip above/below price to signal trend reversals.',
        inputs: ['Price Data'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Trend',
        icon: 'GitCommit',
        color: '#a855f7',
        defaultData: { indicatorType: 'sar', timeframe: '60', params: { step: 0.02, max: 0.2 } },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // BANDS & CHANNELS
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'bb',
        nodeType: 'indicator',
        label: 'Bollinger Bands',
        description: 'Volatility bands around SMA',
        tooltip: 'Price bands based on standard deviation. Squeeze indicates low volatility, expansion signals breakout.',
        inputs: ['Price Data'],
        outputs: ['Upper', 'Middle', 'Lower'],
        category: 'indicators',
        subcategory: 'Bands',
        icon: 'Maximize2',
        color: '#ec4899',
        defaultData: { indicatorType: 'bb', timeframe: '60', params: { period: 20, deviation: 2, band: 'middle' } },
    },
    {
        type: 'keltner',
        nodeType: 'indicator',
        label: 'Keltner Channel',
        description: 'ATR-based price channel',
        tooltip: 'Uses ATR for band width instead of standard deviation. Better for trending markets.',
        inputs: ['Price Data'],
        outputs: ['Upper', 'Middle', 'Lower'],
        category: 'indicators',
        subcategory: 'Bands',
        icon: 'Maximize2',
        color: '#ec4899',
        defaultData: { indicatorType: 'keltner', timeframe: '60', params: { period: 20, multiplier: 2, band: 'middle' } },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // VOLATILITY
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'atr',
        nodeType: 'indicator',
        label: 'ATR',
        description: 'Average True Range',
        tooltip: 'Measures market volatility. Use for position sizing and stop-loss placement.',
        inputs: ['Price Data'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Volatility',
        icon: 'Zap',
        color: '#f97316',
        defaultData: { indicatorType: 'atr', timeframe: '60', params: { period: 14 } },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // VOLUME
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'obv',
        nodeType: 'indicator',
        label: 'OBV',
        description: 'On Balance Volume',
        tooltip: 'Cumulative volume indicator. Rising OBV confirms uptrend, falling confirms downtrend.',
        inputs: ['Price Data', 'Volume'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Volume',
        icon: 'BarChart',
        color: '#3b82f6',
        defaultData: { indicatorType: 'obv', timeframe: '60', params: {} },
    },
    {
        type: 'vwap',
        nodeType: 'indicator',
        label: 'VWAP',
        description: 'Volume Weighted Average Price',
        tooltip: 'Institutional benchmark price. Trading above = bullish, below = bearish.',
        inputs: ['Price Data', 'Volume'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Volume',
        icon: 'BarChart',
        color: '#3b82f6',
        defaultData: { indicatorType: 'vwap', timeframe: '60', params: {} },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // ADVANCED / STATISTICAL
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'hmm_regime',
        nodeType: 'indicator',
        label: 'HMM Regime',
        description: 'Hidden Markov Model Regime',
        tooltip: 'Detects market regimes (e.g., bull/bear/sideways) using Hidden Markov Models.',
        inputs: ['Price Data'],
        outputs: ['RegimeID'],
        category: 'indicators',
        subcategory: 'Statistical',
        icon: 'Activity',
        color: '#8b5cf6',
        defaultData: { indicatorType: 'hmm_regime', timeframe: '1D', params: { n_states: 2, feature: 'returns' } },
    },
    {
        type: 'spread',
        nodeType: 'indicator',
        label: 'Asset Spread',
        description: 'Price ratio or spread between two assets',
        tooltip: 'Calculates the spread (A - B) or ratio (A / B) for statistical arbitrage and pairs trading.',
        inputs: ['Price Data A', 'Price Data B'],
        outputs: ['Number'],
        category: 'indicators',
        subcategory: 'Statistical',
        icon: 'TrendingUp',
        color: '#06b6d4',
        defaultData: { indicatorType: 'spread', timeframe: '60', params: { calculationType: 'ratio' } },
    },
];
