/**
 * Integration Nodes — External service connections (PRD §9.2)
 * Inspired by n8n's integration node pattern — each node connects to a specific service.
 */
import { NodeCatalogItem } from '../../types';

export const INTEGRATION_NODES: NodeCatalogItem[] = [
    // =========================================================================
    // Communication
    // =========================================================================
    {
        type: 'telegramNode',
        nodeType: 'integration',
        label: 'Telegram',
        description: 'Send or receive Telegram messages',
        tooltip: 'Send message or receive reply via Telegram bot. Use for alerts, HITL approvals, or collecting user input during workflow execution.',
        inputs: ['Trigger', 'Data'],
        outputs: ['Signal', 'Response'],
        category: 'integrations',
        subcategory: 'Communication',
        icon: 'Send',
        color: '#0088cc',
        backtestEligible: false,
        defaultData: {
            integrationType: 'telegramNode',
            action: 'sendMessage',
            message: '',
            chatId: '',
            credentialAlias: 'telegram',
        },
    },
    {
        type: 'slackNode',
        nodeType: 'integration',
        label: 'Slack',
        description: 'Post to Slack channel',
        tooltip: 'Post message to a Slack channel or DM. Supports rich formatting with blocks, buttons, and attachments.',
        inputs: ['Trigger', 'Data'],
        outputs: ['Signal'],
        category: 'integrations',
        subcategory: 'Communication',
        icon: 'Hash',
        color: '#4a154b',
        backtestEligible: false,
        defaultData: {
            integrationType: 'slackNode',
            channel: '#trading-alerts',
            message: '',
            credentialAlias: 'slack',
        },
    },
    {
        type: 'emailNode',
        nodeType: 'integration',
        label: 'Email',
        description: 'Send email via SendGrid/SMTP',
        tooltip: 'Send email notifications with HTML templates. Use for daily digests, weekly reports, or urgent alerts.',
        inputs: ['Trigger', 'Data'],
        outputs: ['Signal'],
        category: 'integrations',
        subcategory: 'Communication',
        icon: 'Mail',
        color: '#ea4335',
        backtestEligible: false,
        defaultData: {
            integrationType: 'emailNode',
            to: '',
            subject: 'Strategy Alert',
            body: '',
            credentialAlias: 'sendgrid',
        },
    },
    {
        type: 'smsNode',
        nodeType: 'integration',
        label: 'SMS',
        description: 'Send SMS via Twilio',
        tooltip: 'Send SMS alerts to a phone number. Use for critical, time-sensitive alerts that require immediate attention.',
        inputs: ['Trigger', 'Data'],
        outputs: ['Signal'],
        category: 'integrations',
        subcategory: 'Communication',
        icon: 'Smartphone',
        color: '#f22f46',
        backtestEligible: false,
        defaultData: {
            integrationType: 'smsNode',
            to: '',
            message: '',
            credentialAlias: 'twilio',
        },
    },
    // =========================================================================
    // Data
    // =========================================================================
    {
        type: 'httpRequestNode',
        nodeType: 'integration',
        label: 'HTTP Request',
        description: 'Call any API',
        tooltip: 'Make HTTP requests to any REST API — the most versatile node. Fetch data, send commands, or integrate with any service that has an API. Inspired by n8n\'s HTTP Request node.',
        inputs: ['Trigger', 'Data'],
        outputs: ['Data', 'Signal'],
        category: 'integrations',
        subcategory: 'Data',
        icon: 'Globe',
        color: '#6366f1',
        backtestEligible: false,
        defaultData: {
            integrationType: 'httpRequestNode',
            method: 'GET',
            url: '',
            headers: {},
            body: null,
            authentication: 'none',
            credentialAlias: '',
        },
    },
    {
        type: 'databaseQueryNode',
        nodeType: 'integration',
        label: 'Database Query',
        description: 'Run SQL query',
        tooltip: 'Execute a SQL query against the strategy database. Useful for fetching historical data, custom analytics, or writing computed results.',
        inputs: ['Trigger'],
        outputs: ['Data', 'Signal'],
        category: 'integrations',
        subcategory: 'Data',
        icon: 'Database',
        color: '#0ea5e9',
        backtestEligible: false,
        defaultData: {
            integrationType: 'databaseQueryNode',
            query: 'SELECT * FROM ...',
            parameterized: true,
        },
    },
    // =========================================================================
    // Code
    // =========================================================================
    {
        type: 'codePythonNode',
        nodeType: 'integration',
        label: 'Python Code',
        description: 'Run custom Python',
        tooltip: 'Execute custom Python code within the workflow. Code is sent to the Python compute service for execution. Access to pandas, numpy, ta-lib, and all Python libraries.',
        inputs: ['Trigger', 'Data'],
        outputs: ['Data', 'Signal'],
        category: 'integrations',
        subcategory: 'Code',
        icon: 'Code',
        color: '#3776ab',
        backtestEligible: false,
        defaultData: {
            integrationType: 'codePythonNode',
            code: '# Python code\nimport pandas as pd\n\ndef execute(input_data):\n    return {"result": input_data}',
            language: 'python',
        },
    },
    {
        type: 'codeJavascriptNode',
        nodeType: 'integration',
        label: 'JavaScript Code',
        description: 'Run custom JavaScript',
        tooltip: 'Execute custom JavaScript code within the workflow. Runs in a sandboxed Node.js environment. Great for data transformation, calculations, and custom logic.',
        inputs: ['Trigger', 'Data'],
        outputs: ['Data', 'Signal'],
        category: 'integrations',
        subcategory: 'Code',
        icon: 'FileCode',
        color: '#f7df1e',
        backtestEligible: false,
        defaultData: {
            integrationType: 'codeJavascriptNode',
            code: '// JavaScript code\nmodule.exports = function execute(inputData) {\n  return { result: inputData };\n};',
            language: 'javascript',
        },
    },
    // =========================================================================
    // AI
    // =========================================================================
    {
        type: 'aiAnalysisNode',
        nodeType: 'integration',
        label: 'AI Analysis',
        description: 'AI-powered analysis',
        tooltip: 'Send data to the Python ADK agent for AI-powered analysis. Used for sentiment analysis, regime detection, strategy recommendations, and complex decision-making.',
        inputs: ['Trigger', 'Data'],
        outputs: ['Data', 'Signal'],
        category: 'integrations',
        subcategory: 'AI',
        icon: 'Brain',
        color: '#a855f7',
        backtestEligible: false,
        defaultData: {
            integrationType: 'aiAnalysisNode',
            analysisType: 'general',
            prompt: '',
            context: {},
            model: 'gpt-4o',
        },
    },
    // =========================================================================
    // Flow Control (n8n-inspired)
    // =========================================================================
    {
        type: 'mergeNode',
        nodeType: 'integration',
        label: 'Merge',
        description: 'Combine multiple inputs',
        tooltip: 'Combine outputs from multiple branches into one data stream. Modes: Append (concatenate), Join (match by key), or Wait (wait for all inputs). Inspired by n8n\'s Merge node.',
        inputs: ['Data A', 'Data B'],
        outputs: ['Data'],
        category: 'integrations',
        subcategory: 'Flow',
        icon: 'Merge',
        color: '#06b6d4',
        backtestEligible: true,
        defaultData: {
            integrationType: 'mergeNode',
            mergeMode: 'append',
            joinKey: '',
        },
    },
    {
        type: 'splitNode',
        nodeType: 'integration',
        label: 'Split Out',
        description: 'Split to multiple branches',
        tooltip: 'Split one output to multiple branches. Each item in the input array is sent to a separate output. Useful for processing each ticker in a scan result individually. Inspired by n8n\'s Split Out node.',
        inputs: ['Data'],
        outputs: ['Item', 'Signal'],
        category: 'integrations',
        subcategory: 'Flow',
        icon: 'GitBranch',
        color: '#06b6d4',
        backtestEligible: true,
        defaultData: {
            integrationType: 'splitNode',
            fieldToSplit: 'items',
        },
    },
    {
        type: 'setNode',
        nodeType: 'integration',
        label: 'Set',
        description: 'Transform data fields',
        tooltip: 'Set, rename, or delete fields on the data payload flowing through the workflow. Useful for reshaping data between nodes. Inspired by n8n\'s Set node.',
        inputs: ['Data'],
        outputs: ['Data'],
        category: 'integrations',
        subcategory: 'Flow',
        icon: 'Pencil',
        color: '#06b6d4',
        backtestEligible: true,
        defaultData: {
            integrationType: 'setNode',
            assignments: [],
        },
    },
    {
        type: 'filterNode',
        nodeType: 'integration',
        label: 'Filter',
        description: 'Filter data by condition',
        tooltip: 'Pass through only items that match a condition. Items that don\'t match are discarded or sent to a "rejected" output. Useful for screening tickers or filtering signals. Inspired by n8n\'s Filter node.',
        inputs: ['Data'],
        outputs: ['Passed', 'Rejected'],
        category: 'integrations',
        subcategory: 'Flow',
        icon: 'Filter',
        color: '#06b6d4',
        backtestEligible: true,
        defaultData: {
            integrationType: 'filterNode',
            field: '',
            operator: '>',
            value: 0,
        },
    },
    {
        type: 'aggregateNode',
        nodeType: 'integration',
        label: 'Aggregate',
        description: 'Aggregate data (sum, avg, count)',
        tooltip: 'Aggregate multiple data items into summary statistics: sum, average, count, min, max. Useful for portfolio-level metrics or combining scanner results. Inspired by n8n\'s Aggregate node.',
        inputs: ['Data'],
        outputs: ['Data'],
        category: 'integrations',
        subcategory: 'Flow',
        icon: 'BarChart3',
        color: '#06b6d4',
        backtestEligible: true,
        defaultData: {
            integrationType: 'aggregateNode',
            operation: 'average',
            field: 'value',
        },
    },
    {
        type: 'hitlNode',
        nodeType: 'integration',
        label: 'Human Approval',
        description: 'Wait for human approval',
        tooltip: 'Pauses workflow execution until a human approves or rejects via Telegram, Slack, or the web UI. The orchestrator holds state in Redis until the callback is received. Inspired by n8n\'s Human-in-the-Loop pattern.',
        inputs: ['Trigger', 'Data'],
        outputs: ['Approved', 'Rejected'],
        category: 'integrations',
        subcategory: 'Flow',
        icon: 'UserCheck',
        color: '#f97316',
        backtestEligible: false,
        defaultData: {
            integrationType: 'hitlNode',
            channel: 'telegram',
            message: 'Approve this action?',
            timeoutMinutes: 30,
            credentialAlias: 'telegram',
        },
    },
    // =========================================================================
    // Sub-workflow
    // =========================================================================
    {
        type: 'subWorkflowNode',
        nodeType: 'integration',
        label: 'Sub-Workflow',
        description: 'Execute another saved workflow as a reusable module',
        tooltip: 'Runs a saved workflow as a black-box sub-process. Data from this node\'s inputs is passed as the trigger payload; the sub-workflow\'s final output is returned as this node\'s output. Equivalent to n8n\'s Execute Sub-workflow node.',
        inputs: ['Trigger', 'Data'],
        outputs: ['Result', 'Error'],
        category: 'integrations',
        subcategory: 'Flow',
        icon: 'GitBranch',
        color: '#6366f1',
        backtestEligible: false,
        defaultData: {
            integrationType: 'subWorkflowNode',
            /** ID of the SavedWorkflow to execute */
            subWorkflowId: '',
            /** Human-readable name (resolved at runtime) */
            subWorkflowName: '',
            /** How to handle sub-workflow errors */
            onError: 'stop',
            /** Timeout in seconds (0 = no timeout) */
            timeoutSeconds: 0,
        },
    },
];
