/**
 * Math Nodes - Mathematical operations for the strategy builder
 */
import { NodeCatalogItem } from '../../types';

export const MATH_NODES: NodeCatalogItem[] = [
    {
        type: 'add',
        nodeType: 'math',
        label: 'Add',
        description: 'A + B',
        tooltip: 'Add two values together. Use for combining indicators or calculating targets.',
        inputs: ['Number', 'Number'],
        outputs: ['Number'],
        category: 'math',
        subcategory: 'Operators',
        icon: 'Plus',
        color: '#14b8a6',
        defaultData: { mathType: 'add' },
    },
    {
        type: 'subtract',
        nodeType: 'math',
        label: 'Subtract',
        description: 'A - B',
        tooltip: 'Subtract B from A. Calculate differences or spreads.',
        inputs: ['Number', 'Number'],
        outputs: ['Number'],
        category: 'math',
        subcategory: 'Operators',
        icon: 'Minus',
        color: '#14b8a6',
        defaultData: { mathType: 'subtract' },
    },
    {
        type: 'multiply',
        nodeType: 'math',
        label: 'Multiply',
        description: 'A × B',
        tooltip: 'Multiply two values. Use for position sizing or ATR-based stops.',
        inputs: ['Number', 'Number'],
        outputs: ['Number'],
        category: 'math',
        subcategory: 'Operators',
        icon: 'X',
        color: '#14b8a6',
        defaultData: { mathType: 'multiply' },
    },
    {
        type: 'divide',
        nodeType: 'math',
        label: 'Divide',
        description: 'A ÷ B',
        tooltip: 'Divide A by B. Calculate ratios or normalize values.',
        inputs: ['Number', 'Number'],
        outputs: ['Number'],
        category: 'math',
        subcategory: 'Operators',
        icon: 'Divide',
        color: '#14b8a6',
        defaultData: { mathType: 'divide' },
    },
    {
        type: 'advancedMath',
        nodeType: 'math',
        label: 'Advanced Math',
        description: 'sqrt, abs, sin, cos...',
        tooltip: 'Apply mathematical functions: square root, absolute value, trigonometry.',
        inputs: ['Number'],
        outputs: ['Number'],
        category: 'math',
        subcategory: 'Functions',
        icon: 'Function',
        color: '#a855f7',
        defaultData: { mathType: 'advancedMath', mathFunction: 'sqrt' },
    },
    {
        type: 'expression',
        nodeType: 'math',
        label: 'Expression',
        description: 'Safe Python-DSL expression',
        tooltip: 'Evaluate a restricted Python expression over upstream node outputs. Allow-listed only: arithmetic, comparisons, `x if cond else y`, talib.<allow-list>, np.<allow-list>, abs/min/max, and the incoming-input bindings a/b/c. Parsed via AST walker — no arbitrary code, no imports, no attribute access on user objects. Safe substitute for the legacy Code node.',
        inputs: ['Input A', 'Input B', 'Input C'],
        outputs: ['Value'],
        category: 'math',
        subcategory: 'Functions',
        icon: 'Calculator',
        color: '#a855f7',
        backtestEligible: true,
        defaultData: {
            mathType: 'expression',
            // Bindings: `a`, `b`, `c` are the three input handles.
            // Examples: `1 if a > b else 0`, `max(0, a - 30) / 70`, `abs(a - b)`, `np.sign(a)`.
            expression: 'a',
            // Output data type hint for downstream type checking.
            outputDataType: 'number',
        },
    },
];
