/**
 * Pine Script Nodes - TradingView Pine Script building blocks
 */
import { NodeCatalogItem } from '../../types';

export const PINE_SCRIPT_NODES: NodeCatalogItem[] = [
    // ═══════════════════════════════════════════════════════════════════════════
    // SCRIPT SETUP
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'pine_strategy',
        nodeType: 'pineScript',
        label: 'strategy()',
        description: 'Declares a TradingView strategy script',
        tooltip: 'Root node for strategy scripts. Sets title, overlay, initial capital, and other strategy properties.',
        inputs: [],
        outputs: ['Script'],
        category: 'pineScript',
        subcategory: 'Script Setup',
        icon: 'FileCode2',
        color: '#2962FF',
        defaultData: { pineType: 'pine_strategy', label: 'strategy()', scriptTitle: 'My Strategy', overlay: true },
    },
    {
        type: 'pine_indicator',
        nodeType: 'pineScript',
        label: 'indicator()',
        description: 'Declares a TradingView indicator script',
        tooltip: 'Root node for indicator-only scripts. Use this instead of strategy() when you only want overlays/plots.',
        inputs: [],
        outputs: ['Script'],
        category: 'pineScript',
        subcategory: 'Script Setup',
        icon: 'BarChart3',
        color: '#2962FF',
        defaultData: { pineType: 'pine_indicator', label: 'indicator()', scriptTitle: 'My Indicator', overlay: true },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // INPUTS
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'pine_input_int',
        nodeType: 'pineScript',
        label: 'input.int',
        description: 'Integer input parameter',
        tooltip: 'Creates a user-configurable integer input in the script settings panel.',
        inputs: [],
        outputs: ['Number'],
        category: 'pineScript',
        subcategory: 'Inputs',
        icon: 'Hash',
        color: '#00BCD4',
        defaultData: { pineType: 'pine_input_int', label: 'input.int', inputName: 'Length', inputDefault: 14 },
    },
    {
        type: 'pine_input_float',
        nodeType: 'pineScript',
        label: 'input.float',
        description: 'Float input parameter',
        tooltip: 'Creates a user-configurable decimal number input.',
        inputs: [],
        outputs: ['Number'],
        category: 'pineScript',
        subcategory: 'Inputs',
        icon: 'Hash',
        color: '#00BCD4',
        defaultData: { pineType: 'pine_input_float', label: 'input.float', inputName: 'Multiplier', inputDefault: 2.0 },
    },
    {
        type: 'pine_input_bool',
        nodeType: 'pineScript',
        label: 'input.bool',
        description: 'Boolean input parameter',
        tooltip: 'Creates a toggle checkbox input in the script settings.',
        inputs: [],
        outputs: ['Boolean'],
        category: 'pineScript',
        subcategory: 'Inputs',
        icon: 'ToggleLeft',
        color: '#00BCD4',
        defaultData: { pineType: 'pine_input_bool', label: 'input.bool', inputName: 'Use Filter', inputDefault: true },
    },
    {
        type: 'pine_input_source',
        nodeType: 'pineScript',
        label: 'input.source',
        description: 'Source input (close, open, etc.)',
        tooltip: 'Lets user choose a price source (close, open, high, low, hl2, etc.).',
        inputs: [],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Inputs',
        icon: 'ArrowDownCircle',
        color: '#00BCD4',
        defaultData: { pineType: 'pine_input_source', label: 'input.source', inputName: 'Source', inputDefault: 'close' },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // DATA SERIES
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'pine_close',
        nodeType: 'pineScript',
        label: 'close',
        description: 'Close price series',
        tooltip: 'The closing price of each bar.',
        inputs: [],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Data',
        icon: 'TrendingUp',
        color: '#4CAF50',
        defaultData: { pineType: 'pine_close', label: 'close' },
    },
    {
        type: 'pine_open',
        nodeType: 'pineScript',
        label: 'open',
        description: 'Open price series',
        tooltip: 'The opening price of each bar.',
        inputs: [],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Data',
        icon: 'TrendingUp',
        color: '#4CAF50',
        defaultData: { pineType: 'pine_open', label: 'open' },
    },
    {
        type: 'pine_high',
        nodeType: 'pineScript',
        label: 'high',
        description: 'High price series',
        tooltip: 'The highest price of each bar.',
        inputs: [],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Data',
        icon: 'ArrowUp',
        color: '#4CAF50',
        defaultData: { pineType: 'pine_high', label: 'high' },
    },
    {
        type: 'pine_low',
        nodeType: 'pineScript',
        label: 'low',
        description: 'Low price series',
        tooltip: 'The lowest price of each bar.',
        inputs: [],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Data',
        icon: 'ArrowDown',
        color: '#4CAF50',
        defaultData: { pineType: 'pine_low', label: 'low' },
    },
    {
        type: 'pine_volume',
        nodeType: 'pineScript',
        label: 'volume',
        description: 'Volume series',
        tooltip: 'The trading volume of each bar.',
        inputs: [],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Data',
        icon: 'BarChart',
        color: '#4CAF50',
        defaultData: { pineType: 'pine_volume', label: 'volume' },
    },
    {
        type: 'pine_bar_index',
        nodeType: 'pineScript',
        label: 'bar_index',
        description: 'Current bar index number',
        tooltip: 'Integer index of the current bar, starting from 0.',
        inputs: [],
        outputs: ['Number'],
        category: 'pineScript',
        subcategory: 'Data',
        icon: 'Hash',
        color: '#4CAF50',
        defaultData: { pineType: 'pine_bar_index', label: 'bar_index' },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // INDICATORS (ta.*)
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'pine_ta_sma',
        nodeType: 'pineScript',
        label: 'ta.sma',
        description: 'Simple Moving Average',
        tooltip: 'Calculates Simple Moving Average over the specified length.',
        inputs: ['Series', 'Number'],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Indicators',
        icon: 'TrendingUp',
        color: '#7C4DFF',
        defaultData: { pineType: 'pine_ta_sma', label: 'ta.sma', period: 14, source: 'close' },
    },
    {
        type: 'pine_ta_ema',
        nodeType: 'pineScript',
        label: 'ta.ema',
        description: 'Exponential Moving Average',
        tooltip: 'Calculates Exponential Moving Average, more weight to recent prices.',
        inputs: ['Series', 'Number'],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Indicators',
        icon: 'TrendingUp',
        color: '#7C4DFF',
        defaultData: { pineType: 'pine_ta_ema', label: 'ta.ema', period: 14, source: 'close' },
    },
    {
        type: 'pine_ta_rsi',
        nodeType: 'pineScript',
        label: 'ta.rsi',
        description: 'Relative Strength Index',
        tooltip: 'Momentum oscillator measuring speed and change of price movements (0-100).',
        inputs: ['Series', 'Number'],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Indicators',
        icon: 'Activity',
        color: '#7C4DFF',
        defaultData: { pineType: 'pine_ta_rsi', label: 'ta.rsi', period: 14, source: 'close' },
    },
    {
        type: 'pine_ta_macd',
        nodeType: 'pineScript',
        label: 'ta.macd',
        description: 'MACD indicator (line, signal, histogram)',
        tooltip: 'Returns MACD line, signal line, and histogram as a tuple.',
        inputs: ['Series'],
        outputs: ['MACD', 'Signal', 'Histogram'],
        category: 'pineScript',
        subcategory: 'Indicators',
        icon: 'BarChart2',
        color: '#7C4DFF',
        defaultData: { pineType: 'pine_ta_macd', label: 'ta.macd', source: 'close' },
    },
    {
        type: 'pine_ta_bb',
        nodeType: 'pineScript',
        label: 'ta.bb',
        description: 'Bollinger Bands (basis, upper, lower)',
        tooltip: 'Returns middle, upper, and lower Bollinger Bands.',
        inputs: ['Series', 'Number'],
        outputs: ['Basis', 'Upper', 'Lower'],
        category: 'pineScript',
        subcategory: 'Indicators',
        icon: 'Maximize2',
        color: '#7C4DFF',
        defaultData: { pineType: 'pine_ta_bb', label: 'ta.bb', period: 20, source: 'close' },
    },
    {
        type: 'pine_ta_atr',
        nodeType: 'pineScript',
        label: 'ta.atr',
        description: 'Average True Range',
        tooltip: 'Measures market volatility as the average of true ranges.',
        inputs: ['Number'],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Indicators',
        icon: 'Zap',
        color: '#7C4DFF',
        defaultData: { pineType: 'pine_ta_atr', label: 'ta.atr', period: 14 },
    },
    {
        type: 'pine_ta_stoch',
        nodeType: 'pineScript',
        label: 'ta.stoch',
        description: 'Stochastic oscillator',
        tooltip: 'Compares closing price to price range. Returns %K value.',
        inputs: ['Series', 'Number'],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Indicators',
        icon: 'Activity',
        color: '#7C4DFF',
        defaultData: { pineType: 'pine_ta_stoch', label: 'ta.stoch', period: 14, source: 'close' },
    },
    {
        type: 'pine_ta_vwap',
        nodeType: 'pineScript',
        label: 'ta.vwap',
        description: 'Volume Weighted Average Price',
        tooltip: 'Institutional benchmark price weighted by volume.',
        inputs: ['Series'],
        outputs: ['Series'],
        category: 'pineScript',
        subcategory: 'Indicators',
        icon: 'BarChart',
        color: '#7C4DFF',
        defaultData: { pineType: 'pine_ta_vwap', label: 'ta.vwap', source: 'close' },
    },
    {
        type: 'pine_ta_crossover',
        nodeType: 'pineScript',
        label: 'ta.crossover',
        description: 'Series A crosses above Series B',
        tooltip: 'Returns true when series1 crosses above series2.',
        inputs: ['Series', 'Series'],
        outputs: ['Boolean'],
        category: 'pineScript',
        subcategory: 'Indicators',
        icon: 'ArrowUpRight',
        color: '#7C4DFF',
        defaultData: { pineType: 'pine_ta_crossover', label: 'ta.crossover' },
    },
    {
        type: 'pine_ta_crossunder',
        nodeType: 'pineScript',
        label: 'ta.crossunder',
        description: 'Series A crosses below Series B',
        tooltip: 'Returns true when series1 crosses below series2.',
        inputs: ['Series', 'Series'],
        outputs: ['Boolean'],
        category: 'pineScript',
        subcategory: 'Indicators',
        icon: 'ArrowDownRight',
        color: '#7C4DFF',
        defaultData: { pineType: 'pine_ta_crossunder', label: 'ta.crossunder' },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONDITIONS
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'pine_compare',
        nodeType: 'pineScript',
        label: 'Compare',
        description: 'Compare two values (>, <, ==, etc.)',
        tooltip: 'Comparison operator between two series or values.',
        inputs: ['Series', 'Series'],
        outputs: ['Boolean'],
        category: 'pineScript',
        subcategory: 'Conditions',
        icon: 'GitBranch',
        color: '#FF9800',
        defaultData: { pineType: 'pine_compare', label: 'Compare', operator: '>' },
    },
    {
        type: 'pine_and',
        nodeType: 'pineScript',
        label: 'and',
        description: 'Logical AND',
        tooltip: 'Returns true when both conditions are true.',
        inputs: ['Boolean', 'Boolean'],
        outputs: ['Boolean'],
        category: 'pineScript',
        subcategory: 'Conditions',
        icon: 'GitMerge',
        color: '#FF9800',
        defaultData: { pineType: 'pine_and', label: 'and' },
    },
    {
        type: 'pine_or',
        nodeType: 'pineScript',
        label: 'or',
        description: 'Logical OR',
        tooltip: 'Returns true when either condition is true.',
        inputs: ['Boolean', 'Boolean'],
        outputs: ['Boolean'],
        category: 'pineScript',
        subcategory: 'Conditions',
        icon: 'GitBranch',
        color: '#FF9800',
        defaultData: { pineType: 'pine_or', label: 'or' },
    },
    {
        type: 'pine_not',
        nodeType: 'pineScript',
        label: 'not',
        description: 'Logical NOT',
        tooltip: 'Inverts a boolean value.',
        inputs: ['Boolean'],
        outputs: ['Boolean'],
        category: 'pineScript',
        subcategory: 'Conditions',
        icon: 'XCircle',
        color: '#FF9800',
        defaultData: { pineType: 'pine_not', label: 'not' },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // STRATEGY ACTIONS
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'pine_strategy_entry',
        nodeType: 'pineScript',
        label: 'strategy.entry',
        description: 'Enter a trade (long/short)',
        tooltip: 'Opens a position. Specify id, direction, and optional quantity.',
        inputs: ['Boolean'],
        outputs: ['Signal'],
        category: 'pineScript',
        subcategory: 'Strategy',
        icon: 'LogIn',
        color: '#4CAF50',
        defaultData: { pineType: 'pine_strategy_entry', label: 'strategy.entry', entryId: 'Long', direction: 'long' },
    },
    {
        type: 'pine_strategy_close',
        nodeType: 'pineScript',
        label: 'strategy.close',
        description: 'Close a position by id',
        tooltip: 'Closes an existing position by its entry id.',
        inputs: ['Boolean'],
        outputs: ['Signal'],
        category: 'pineScript',
        subcategory: 'Strategy',
        icon: 'LogOut',
        color: '#F44336',
        defaultData: { pineType: 'pine_strategy_close', label: 'strategy.close', entryId: 'Long' },
    },
    {
        type: 'pine_strategy_exit',
        nodeType: 'pineScript',
        label: 'strategy.exit',
        description: 'Set stop-loss / take-profit exit',
        tooltip: 'Configures SL/TP for an existing position.',
        inputs: ['Boolean'],
        outputs: ['Signal'],
        category: 'pineScript',
        subcategory: 'Strategy',
        icon: 'Shield',
        color: '#FF9800',
        defaultData: { pineType: 'pine_strategy_exit', label: 'strategy.exit', entryId: 'Long' },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // PLOTTING
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'pine_plot',
        nodeType: 'pineScript',
        label: 'plot',
        description: 'Plot a series on the chart',
        tooltip: 'Draws a line on the chart for a given series.',
        inputs: ['Series'],
        outputs: [],
        category: 'pineScript',
        subcategory: 'Plotting',
        icon: 'LineChart',
        color: '#E91E63',
        defaultData: { pineType: 'pine_plot', label: 'plot', plotColor: '#2962FF', plotTitle: 'Plot', plotLineWidth: 2 },
    },
    {
        type: 'pine_plotshape',
        nodeType: 'pineScript',
        label: 'plotshape',
        description: 'Plot shapes on the chart',
        tooltip: 'Draws shapes (triangles, circles, etc.) when condition is true.',
        inputs: ['Boolean'],
        outputs: [],
        category: 'pineScript',
        subcategory: 'Plotting',
        icon: 'Triangle',
        color: '#E91E63',
        defaultData: { pineType: 'pine_plotshape', label: 'plotshape', plotColor: '#4CAF50' },
    },
    {
        type: 'pine_hline',
        nodeType: 'pineScript',
        label: 'hline',
        description: 'Draw a horizontal line',
        tooltip: 'Draws a fixed horizontal line at a specified price level.',
        inputs: ['Number'],
        outputs: [],
        category: 'pineScript',
        subcategory: 'Plotting',
        icon: 'Minus',
        color: '#E91E63',
        defaultData: { pineType: 'pine_hline', label: 'hline', plotColor: '#787B86' },
    },
    {
        type: 'pine_bgcolor',
        nodeType: 'pineScript',
        label: 'bgcolor',
        description: 'Set background color conditionally',
        tooltip: 'Colors the chart background when a condition is met.',
        inputs: ['Boolean'],
        outputs: [],
        category: 'pineScript',
        subcategory: 'Plotting',
        icon: 'Paintbrush',
        color: '#E91E63',
        defaultData: { pineType: 'pine_bgcolor', label: 'bgcolor', plotColor: '#2962FF' },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // ALERTS
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'pine_alertcondition',
        nodeType: 'pineScript',
        label: 'alertcondition',
        description: 'Create an alert condition',
        tooltip: 'Registers a condition that can trigger TradingView alerts.',
        inputs: ['Boolean'],
        outputs: [],
        category: 'pineScript',
        subcategory: 'Alerts',
        icon: 'Bell',
        color: '#FF5722',
        defaultData: { pineType: 'pine_alertcondition', label: 'alertcondition', alertMessage: 'Alert triggered!' },
    },
    {
        type: 'pine_alert',
        nodeType: 'pineScript',
        label: 'alert',
        description: 'Fire an alert',
        tooltip: 'Fires an alert with a custom message when triggered.',
        inputs: ['Boolean'],
        outputs: [],
        category: 'pineScript',
        subcategory: 'Alerts',
        icon: 'BellRing',
        color: '#FF5722',
        defaultData: { pineType: 'pine_alert', label: 'alert', alertMessage: 'Signal detected!' },
    },
];
