/**
 * Portfolio Nodes - Nodes that interact with user portfolio data
 * 
 * These nodes let users read portfolio data, analyze risk,
 * manage allocations, and rebalance within the strategy builder.
 */
import { NodeCatalogItem } from '../../types';

export const PORTFOLIO_NODES: NodeCatalogItem[] = [
    // ─── Data Reading ───────────────────────────────────────
    {
        type: 'portfolio_read_holdings',
        nodeType: 'portfolio',
        label: 'Read Holdings',
        description: 'Get portfolio positions',
        tooltip: 'Read all current holdings from your portfolio. Outputs a list of assets with quantities, prices, and allocations for use in strategy logic.',
        inputs: [],
        outputs: ['Holdings List'],
        category: 'portfolio',
        subcategory: 'Data',
        icon: 'Briefcase',
        color: '#06b6d4',
        defaultData: { portfolioAction: 'readHoldings' },
    },
    {
        type: 'portfolio_total_value',
        nodeType: 'portfolio',
        label: 'Portfolio Value',
        description: 'Total portfolio value',
        tooltip: 'Get the total current value of your portfolio in base currency. Use for position sizing relative to portfolio size.',
        inputs: [],
        outputs: ['Number'],
        category: 'portfolio',
        subcategory: 'Data',
        icon: 'DollarSign',
        color: '#06b6d4',
        defaultData: { portfolioAction: 'totalValue' },
    },
    {
        type: 'portfolio_asset_weight',
        nodeType: 'portfolio',
        label: 'Asset Weight',
        description: 'Current allocation %',
        tooltip: 'Get the current percentage weight of a specific asset in your portfolio. Useful for rebalancing strategies.',
        inputs: ['Symbol'],
        outputs: ['Number'],
        category: 'portfolio',
        subcategory: 'Data',
        icon: 'PieChart',
        color: '#06b6d4',
        defaultData: { portfolioAction: 'assetWeight', symbol: '' },
    },
    {
        type: 'portfolio_asset_pnl',
        nodeType: 'portfolio',
        label: 'Asset P&L',
        description: 'Profit/loss for asset',
        tooltip: 'Get the unrealized P&L for a specific holding. Outputs both absolute and percentage returns.',
        inputs: ['Symbol'],
        outputs: ['Number', 'Percent'],
        category: 'portfolio',
        subcategory: 'Data',
        icon: 'TrendingUp',
        color: '#06b6d4',
        defaultData: { portfolioAction: 'assetPnl', symbol: '' },
    },
    {
        type: 'portfolio_day_change',
        nodeType: 'portfolio',
        label: 'Day Change',
        description: 'Portfolio daily change',
        tooltip: 'Get today\'s portfolio change in value and percentage. Useful for daily loss limit or momentum signals.',
        inputs: [],
        outputs: ['Number', 'Percent'],
        category: 'portfolio',
        subcategory: 'Data',
        icon: 'BarChart3',
        color: '#06b6d4',
        defaultData: { portfolioAction: 'dayChange' },
    },

    // ─── Risk Analysis ──────────────────────────────────────
    {
        type: 'portfolio_concentration_check',
        nodeType: 'portfolio',
        label: 'Concentration Risk',
        description: 'Check overexposure',
        tooltip: 'Check if any single asset exceeds a specified allocation threshold. Returns true if portfolio is over-concentrated.',
        inputs: ['Threshold %'],
        outputs: ['Boolean', 'Symbol'],
        category: 'portfolio',
        subcategory: 'Risk Analysis',
        icon: 'ShieldAlert',
        color: '#f59e0b',
        defaultData: { portfolioAction: 'concentrationCheck', threshold: 30 },
    },
    {
        type: 'portfolio_diversification_score',
        nodeType: 'portfolio',
        label: 'Diversification Score',
        description: 'Measure diversity',
        tooltip: 'Calculate a diversification score (0-100) based on the number of asset classes, sectors, and position sizing. Higher = more diversified.',
        inputs: [],
        outputs: ['Number'],
        category: 'portfolio',
        subcategory: 'Risk Analysis',
        icon: 'Layers',
        color: '#f59e0b',
        defaultData: { portfolioAction: 'diversificationScore' },
    },
    {
        type: 'portfolio_correlation_check',
        nodeType: 'portfolio',
        label: 'Correlation Check',
        description: 'Asset correlation',
        tooltip: 'Check the correlation between two portfolio assets. High correlation means less effective diversification.',
        inputs: ['Symbol A', 'Symbol B'],
        outputs: ['Number'],
        category: 'portfolio',
        subcategory: 'Risk Analysis',
        icon: 'GitBranch',
        color: '#f59e0b',
        defaultData: { portfolioAction: 'correlationCheck', symbolA: '', symbolB: '' },
    },
    {
        type: 'portfolio_drawdown',
        nodeType: 'portfolio',
        label: 'Portfolio Drawdown',
        description: 'Max drawdown measure',
        tooltip: 'Calculate the maximum drawdown of the portfolio from its peak value. Key risk metric for portfolio health.',
        inputs: [],
        outputs: ['Number', 'Percent'],
        category: 'portfolio',
        subcategory: 'Risk Analysis',
        icon: 'TrendingDown',
        color: '#f59e0b',
        defaultData: { portfolioAction: 'drawdown' },
    },

    // ─── Management ─────────────────────────────────────────
    {
        type: 'portfolio_rebalance_signal',
        nodeType: 'portfolio',
        label: 'Rebalance Signal',
        description: 'Drift-based rebalance',
        tooltip: 'Generate a rebalance signal when any asset drifts beyond a threshold from its target allocation. Outputs which assets need buying/selling.',
        inputs: ['Drift Threshold %'],
        outputs: ['Signal', 'Actions List'],
        category: 'portfolio',
        subcategory: 'Management',
        icon: 'RefreshCw',
        color: '#10b981',
        defaultData: { portfolioAction: 'rebalanceSignal', driftThreshold: 5 },
    },
    {
        type: 'portfolio_set_target',
        nodeType: 'portfolio',
        label: 'Set Target Weight',
        description: 'Define target allocation',
        tooltip: 'Set the target percentage allocation for a specific asset. Used together with Rebalance Signal to maintain your ideal portfolio composition.',
        inputs: ['Symbol', 'Target %'],
        outputs: ['Confirmation'],
        category: 'portfolio',
        subcategory: 'Management',
        icon: 'Target',
        color: '#10b981',
        defaultData: { portfolioAction: 'setTarget', symbol: '', targetPct: 0 },
    },
    {
        type: 'portfolio_optimizer',
        nodeType: 'portfolio',
        label: 'Portfolio Optimizer',
        description: 'Optimize allocations',
        tooltip: 'Run mean-variance optimization on your portfolio to suggest optimal weights for maximum Sharpe ratio or minimum variance.',
        inputs: ['Optimization Goal'],
        outputs: ['Weights Map'],
        category: 'portfolio',
        subcategory: 'Management',
        icon: 'Sparkles',
        color: '#10b981',
        defaultData: { portfolioAction: 'optimize', goal: 'maxSharpe' },
    },
    {
        type: 'portfolio_sector_exposure',
        nodeType: 'portfolio',
        label: 'Sector Exposure',
        description: 'By asset class',
        tooltip: 'Break down portfolio exposure by asset class (stocks, crypto, gold, etc.). Useful for sector rotation strategies.',
        inputs: [],
        outputs: ['Breakdown'],
        category: 'portfolio',
        subcategory: 'Management',
        icon: 'BarChart',
        color: '#10b981',
        defaultData: { portfolioAction: 'sectorExposure' },
    },
];
