/**
 * Risk Management Nodes - Position sizing and risk control
 */
import { NodeCatalogItem } from '../../types';

export const RISK_NODES: NodeCatalogItem[] = [
    {
        type: 'risk_max_drawdown',
        nodeType: 'risk',
        label: 'Max Drawdown',
        description: 'Account protection',
        tooltip: 'Stop trading if account drops by X%. Protects capital from catastrophic losses.',
        inputs: [],
        outputs: ['Number'],
        category: 'risk',
        subcategory: 'Account Protection',
        icon: 'ShieldAlert',
        color: '#ef4444',
        defaultData: { riskType: 'maxDrawdown', value: 10 },
    },
    {
        type: 'risk_daily_loss_limit',
        nodeType: 'risk',
        label: 'Daily Loss Limit',
        description: 'Daily stop trading',
        tooltip: 'Stop trading for the day if losses exceed X%. Prevents revenge trading.',
        inputs: [],
        outputs: ['Number'],
        category: 'risk',
        subcategory: 'Account Protection',
        icon: 'ShieldOff',
        color: '#ef4444',
        defaultData: { riskType: 'dailyLossLimit', value: 2 },
    },
    {
        type: 'risk_position_percent',
        nodeType: 'risk',
        label: 'Position %',
        description: 'Size by capital %',
        tooltip: 'Calculate position size as percentage of account. Standard risk management.',
        inputs: [],
        outputs: ['Number'],
        category: 'risk',
        subcategory: 'Sizing',
        icon: 'PieChart',
        color: '#f97316',
        defaultData: { riskType: 'positionPercent', percentage: 2 },
    },
    {
        type: 'risk_kelly_criterion',
        nodeType: 'risk',
        label: 'Kelly Criterion',
        description: 'Optimal bet sizing',
        tooltip: 'Calculate optimal position size based on win rate and reward/risk ratio.',
        inputs: [],
        outputs: ['Number'],
        category: 'risk',
        subcategory: 'Sizing',
        icon: 'Calculator',
        color: '#f97316',
        defaultData: { riskType: 'kellyCriterion' },
    },
    {
        type: 'risk_trailing_stop',
        nodeType: 'risk',
        label: 'Trailing Stop %',
        description: 'Dynamic exit level',
        tooltip: 'Trailing stop that moves with price. Lock in profits automatically.',
        inputs: [],
        outputs: ['Number'],
        category: 'risk',
        subcategory: 'Trade Management',
        icon: 'TrendingUp',
        color: '#f97316',
        defaultData: { riskType: 'trailingStop', value: 20 },
    },
    {
        type: 'portfolio_allocation',
        nodeType: 'risk',
        label: 'Target Allocation',
        description: 'Asset target weights',
        tooltip: 'Define target percentage allocation for an asset in the portfolio. Used by rebalancing actions.',
        inputs: [],
        outputs: ['Target Weight'],
        category: 'risk',
        subcategory: 'Portfolio',
        icon: 'PieChart',
        color: '#f97316',
        defaultData: { riskType: 'portfolioAllocation', targetPercentage: 20 },
    },
];
