/**
 * Trigger Nodes — Event-driven workflow entry points (PRD §9.1)
 * Inspired by n8n's trigger node pattern and OpenClaw's heartbeat daemon.
 */
import { NodeCatalogItem } from '../../types';

export const TRIGGER_NODES: NodeCatalogItem[] = [
    {
        type: 'heartbeatTrigger',
        nodeType: 'trigger',
        label: 'Heartbeat',
        description: 'Schedule-based trigger',
        tooltip: 'Fires workflow on a configurable schedule — every N minutes, at market open/close, or daily at a specific time. Powered by BullMQ repeatable jobs. Inspired by OpenClaw heartbeat daemon.',
        inputs: [],
        outputs: ['Signal'],
        category: 'triggers',
        subcategory: 'Polling',
        icon: 'HeartPulse',
        color: '#8b5cf6',
        backtestEligible: true,
        defaultData: {
            triggerType: 'heartbeatTrigger',
            intervalMinutes: 5,
            atMarketOpen: false,
            atMarketClose: false,
            specificTime: null,
        },
    },
    {
        type: 'webhookTrigger',
        nodeType: 'trigger',
        label: 'Webhook',
        description: 'HTTP POST trigger',
        tooltip: 'Fires instantly when an external HTTP POST is received. Connect TradingView alerts, Zapier, or any service that sends webhooks. HMAC signature verification for security.',
        inputs: [],
        outputs: ['Signal', 'Data'],
        category: 'triggers',
        subcategory: 'Event',
        icon: 'Webhook',
        color: '#3b82f6',
        backtestEligible: false,
        defaultData: {
            triggerType: 'webhookTrigger',
            webhookPath: '',
            hmacSecret: '',
            expectedFields: [],
        },
    },
    {
        type: 'priceAlertTrigger',
        nodeType: 'trigger',
        label: 'Price Alert',
        description: 'Price threshold trigger',
        tooltip: 'Fires when a specific asset crosses a price threshold. Runs as a cheap pre-check in Node.js — no LLM or Python compute required. Extremely fast and cost-effective.',
        inputs: [],
        outputs: ['Signal', 'Price'],
        category: 'triggers',
        subcategory: 'Event',
        icon: 'TrendingUp',
        color: '#22c55e',
        backtestEligible: true,
        defaultData: {
            triggerType: 'priceAlertTrigger',
            symbol: 'AAPL',
            condition: 'crosses_above',
            priceLevel: 0,
        },
    },
    {
        type: 'newsTrigger',
        nodeType: 'trigger',
        label: 'News Event',
        description: 'News keyword trigger',
        tooltip: 'Fires when a keyword or topic is detected in financial news feeds. Monitors NewsAPI, RSS, and SEC filings. Source-filtered to reduce false positives.',
        inputs: [],
        outputs: ['Signal', 'Data'],
        category: 'triggers',
        subcategory: 'Event',
        icon: 'Newspaper',
        color: '#f59e0b',
        backtestEligible: false,
        defaultData: {
            triggerType: 'newsTrigger',
            keywords: [],
            sources: ['newsapi', 'sec'],
            symbols: [],
            minRelevanceScore: 0.7,
        },
    },
    {
        type: 'brokerEventTrigger',
        nodeType: 'trigger',
        label: 'Broker Event',
        description: 'Broker event trigger',
        tooltip: 'Fires on broker events: order filled, margin call, position liquidated, dividend received. Connects to your linked brokerage account via the credential vault.',
        inputs: [],
        outputs: ['Signal', 'Data'],
        category: 'triggers',
        subcategory: 'Event',
        icon: 'Landmark',
        color: '#ef4444',
        backtestEligible: false,
        defaultData: {
            triggerType: 'brokerEventTrigger',
            eventTypes: ['order_filled'],
            credentialAlias: '',
        },
    },
    {
        type: 'manualTrigger',
        nodeType: 'trigger',
        label: 'Manual Trigger',
        description: 'Run on demand',
        tooltip: 'Fires when you explicitly click "Run" in the UI or call the execute API. Inspired by n8n\'s Manual Trigger node. Useful for ad-hoc testing and one-off executions.',
        inputs: [],
        outputs: ['Signal'],
        category: 'triggers',
        subcategory: 'Manual',
        icon: 'Play',
        color: '#10b981',
        backtestEligible: true,
        defaultData: {
            triggerType: 'manualTrigger' as any,
        },
    },
    {
        type: 'cronTrigger',
        nodeType: 'trigger',
        label: 'Schedule (Cron)',
        description: 'Cron expression trigger',
        tooltip: 'Fires workflow on a precise cron schedule. Supports standard cron expressions (e.g., "30 9 * * 1-5" for weekdays at 9:30 AM). Inspired by n8n\'s Schedule Trigger node. Timezone-aware.',
        inputs: [],
        outputs: ['Signal'],
        category: 'triggers',
        subcategory: 'Polling',
        icon: 'Clock',
        color: '#6366f1',
        backtestEligible: true,
        defaultData: {
            triggerType: 'cronTrigger' as any,
            cronExpression: '0 9 * * 1-5',
            timezone: 'America/New_York',
        },
    },
    {
        type: 'conditionTrigger',
        nodeType: 'trigger',
        label: 'Condition Trigger',
        description: 'Fires when an incoming value meets a condition (>, <, =, etc.)',
        tooltip: 'Connect any numeric value (RSI, price, indicator) and define a threshold condition. Fires a signal downstream when satisfied. Wire an indicator output to the Value input, set the operator and threshold.',
        inputs: ['Value'],
        outputs: ['Signal'],
        category: 'triggers',
        subcategory: 'Condition',
        icon: 'GitBranch',
        color: '#f59e0b',
        backtestEligible: true,
        defaultData: {
            triggerType: 'conditionTrigger' as any,
            operator: '<',
            threshold: 30,
        },
    },
];
