import * as Blockly from 'blockly';

export const mqlGenerator = new Blockly.Generator('MQL') as any;

// Order of operation ENUMs
mqlGenerator.ORDER_ATOMIC = 0;           // 0 "" ...
mqlGenerator.ORDER_NEW = 1.1;            // new
mqlGenerator.ORDER_MEMBER = 1.2;         // . []
mqlGenerator.ORDER_FUNCTION_CALL = 2;    // ()
mqlGenerator.ORDER_INCREMENT = 3;        // ++
mqlGenerator.ORDER_DECREMENT = 3;        // --
mqlGenerator.ORDER_BITWISE_NOT = 4.1;    // ~
mqlGenerator.ORDER_UNARY_PLUS = 4.2;     // +
mqlGenerator.ORDER_UNARY_NEGATION = 4.3; // -
mqlGenerator.ORDER_LOGICAL_NOT = 4.4;    // !
mqlGenerator.ORDER_SIZEOF = 4.5;         // sizeof
mqlGenerator.ORDER_DIVISION = 5.1;       // /
mqlGenerator.ORDER_MULTIPLICATION = 5.2; // *
mqlGenerator.ORDER_MODULUS = 5.3;        // %
mqlGenerator.ORDER_SUBTRACTION = 6.1;    // -
mqlGenerator.ORDER_ADDITION = 6.2;       // +
mqlGenerator.ORDER_BITWISE_SHIFT = 7;    // << >>
mqlGenerator.ORDER_RELATIONAL = 8;       // < <= > >=
mqlGenerator.ORDER_EQUALITY = 9;         // == !=
mqlGenerator.ORDER_BITWISE_AND = 10;     // &
mqlGenerator.ORDER_BITWISE_XOR = 11;     // ^
mqlGenerator.ORDER_BITWISE_OR = 12;      // |
mqlGenerator.ORDER_LOGICAL_AND = 13;     // &&
mqlGenerator.ORDER_LOGICAL_OR = 14;      // ||
mqlGenerator.ORDER_CONDITIONAL = 15;     // ?:
mqlGenerator.ORDER_ASSIGNMENT = 16;      // = += -= *= /= %= <<= >>= &= ^= |=
mqlGenerator.ORDER_COMMA = 17;           // ,
mqlGenerator.ORDER_NONE = 99;            // (...)

// Initial setup
mqlGenerator.init = function (workspace: Blockly.Workspace) {
    // Create a list of defined variables
    const variables = Blockly.Variables.allUsedVarModels(workspace);
    const devars = [];
    for (let i = 0; i < variables.length; i++) {
        devars.push('double ' + mqlGenerator.variableDB_.getName(variables[i].getId(),
            Blockly.Names.NameType.VARIABLE) + ';');
    }
    mqlGenerator.definitions_ = {}; // Initialize definitions_
    mqlGenerator.definitions_['variables'] = devars.join('\n');
    mqlGenerator.initializations_ = []; // Store OnInit code
    mqlGenerator.handleCache_ = {}; // Reset handle cache
};

mqlGenerator.finish = function (code: string) {
    // Determine if workspace has actual logic
    const hasCode = code && code.trim().length > 0;

    // If workspace is empty, return simple message instead of boilerplate
    if (!hasCode) {
        return '// Add blocks to your workspace to generate MQL code';
    }

    // Convert global variables to MQL format
    const definitions = [];
    for (let name in mqlGenerator.definitions_) {
        definitions.push(mqlGenerator.definitions_[name]);
    }

    // Basic EA structure with generated code
    return `//+------------------------------------------------------------------+
//|                                             Generated Strategy |
//|                        Generated by PPM                        |
//+------------------------------------------------------------------+
#property copyright "Generated by PPM"
#property link      "https://ppm.example.com"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>

CTrade trade;

${definitions.length > 0 ? definitions.join('\n') + '\n' : ''}

// Helper to get indicator values
double GetIndicatorValue(int handle, int buffer, int shift) {
   double values[];
   if(CopyBuffer(handle, buffer, shift, 1, values) < 0) return 0.0;
   return values[0];
}

// Helper to initialize trade settings
void InitTrade() {
   trade.SetExpertMagicNumber(123456);
   trade.SetDeviationInPoints(10);
   
   // Auto-detect filling mode
   uint filling = (uint)SymbolInfoInteger(Symbol(), SYMBOL_FILLING_MODE);
   if((filling & SYMBOL_FILLING_FOK) == SYMBOL_FILLING_FOK) {
      trade.SetTypeFilling(ORDER_FILLING_FOK);
   } else if((filling & SYMBOL_FILLING_IOC) == SYMBOL_FILLING_IOC) {
      trade.SetTypeFilling(ORDER_FILLING_IOC);
   } else {
      trade.SetTypeFilling(ORDER_FILLING_RETURN);
   }
}

// Helper to normalize lot size
double NormalizeLotSize(double lotSize) {
   double minLot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MAX);
   double stepLot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_STEP);
   
   if(stepLot > 0) {
      lotSize = MathFloor(lotSize / stepLot) * stepLot;
   }
   
   if(lotSize < minLot) lotSize = minLot;
   if(lotSize > maxLot) lotSize = maxLot;
   
   return lotSize;
}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   InitTrade();
${mqlGenerator.initializations_ && mqlGenerator.initializations_.length > 0 ? '   ' + mqlGenerator.initializations_.join('\n   ') : ''}
   return(INIT_SUCCEEDED);
  }
//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
  }
//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
${mqlGenerator.prefixLines(code, mqlGenerator.INDENT)}
  }
//+------------------------------------------------------------------+
`;
};

mqlGenerator.scrub_ = function (block: Blockly.Block, code: string, opt_thisOnly?: boolean) {
    const nextBlock = block.nextConnection && block.nextConnection.targetBlock();
    const nextCode = opt_thisOnly ? '' : mqlGenerator.blockToCode(nextBlock);
    return code + nextCode;
};

// =============================================================================
// STANDARD BLOCKLY BLOCKS
// =============================================================================

// Logic
mqlGenerator.forBlock['controls_if'] = function (block: Blockly.Block) {
    let n = 0;
    let code = '';
    if (mqlGenerator.STATEMENT_PREFIX) {
        code += mqlGenerator.injectId(mqlGenerator.STATEMENT_PREFIX, block);
    }
    do {
        const conditionCode = mqlGenerator.valueToCode(block, 'IF' + n,
            mqlGenerator.ORDER_NONE) || 'false';
        const branchCode = mqlGenerator.statementToCode(block, 'DO' + n);
        code += (n > 0 ? ' else ' : '') +
            'if (' + conditionCode + ') {\n' + branchCode + '}';
        ++n;
    } while (block.getInput('IF' + n));

    if (block.getInput('ELSE') || mqlGenerator.STATEMENT_PREFIX) {
        let branchCode = mqlGenerator.statementToCode(block, 'ELSE');
        if (mqlGenerator.STATEMENT_PREFIX) {
            branchCode = mqlGenerator.prefixLines(
                mqlGenerator.injectId(mqlGenerator.STATEMENT_PREFIX, block),
                mqlGenerator.INDENT) + branchCode;
        }
        code += ' else {\n' + branchCode + '}';
    }
    return code + '\n';
};

mqlGenerator.forBlock['logic_compare'] = function (block: Blockly.Block) {
    const OPERATORS = {
        'EQ': '==',
        'NEQ': '!=',
        'LT': '<',
        'LTE': '<=',
        'GT': '>',
        'GTE': '>='
    };
    const operator = OPERATORS[block.getFieldValue('OP')];
    const order = (operator === '==' || operator === '!=') ?
        mqlGenerator.ORDER_EQUALITY : mqlGenerator.ORDER_RELATIONAL;
    const argument0 = mqlGenerator.valueToCode(block, 'A', order) || '0';
    const argument1 = mqlGenerator.valueToCode(block, 'B', order) || '0';
    const code = argument0 + ' ' + operator + ' ' + argument1;
    return [code, order];
};

mqlGenerator.forBlock['logic_operation'] = function (block: Blockly.Block) {
    const operator = (block.getFieldValue('OP') === 'AND') ? '&&' : '||';
    const order = (operator === '&&') ? mqlGenerator.ORDER_LOGICAL_AND :
        mqlGenerator.ORDER_LOGICAL_OR;
    let argument0 = mqlGenerator.valueToCode(block, 'A', order);
    let argument1 = mqlGenerator.valueToCode(block, 'B', order);
    if (!argument0 && !argument1) {
        argument0 = 'false';
        argument1 = 'false';
    } else {
        const defaultArgument = (operator === '&&') ? 'true' : 'false';
        if (!argument0) argument0 = defaultArgument;
        if (!argument1) argument1 = defaultArgument;
    }
    const code = argument0 + ' ' + operator + ' ' + argument1;
    return [code, order];
};

mqlGenerator.forBlock['logic_boolean'] = function (block: Blockly.Block) {
    const code = (block.getFieldValue('BOOL') === 'TRUE') ? 'true' : 'false';
    return [code, mqlGenerator.ORDER_ATOMIC];
};

// Math
mqlGenerator.forBlock['math_number'] = function (block: Blockly.Block) {
    const code = Number(block.getFieldValue('NUM'));
    const order = code >= 0 ? mqlGenerator.ORDER_ATOMIC :
        mqlGenerator.ORDER_UNARY_NEGATION;
    return [code, order];
};

mqlGenerator.forBlock['math_arithmetic'] = function (block: Blockly.Block) {
    const OPERATORS = {
        'ADD': [' + ', mqlGenerator.ORDER_ADDITION],
        'MINUS': [' - ', mqlGenerator.ORDER_SUBTRACTION],
        'MULTIPLY': [' * ', mqlGenerator.ORDER_MULTIPLICATION],
        'DIVIDE': [' / ', mqlGenerator.ORDER_DIVISION],
        'POWER': [null, mqlGenerator.ORDER_NONE]
    };
    const tuple = OPERATORS[block.getFieldValue('OP')];
    const operator = tuple[0];
    const order = tuple[1];
    const argument0 = mqlGenerator.valueToCode(block, 'A', order) || '0';
    const argument1 = mqlGenerator.valueToCode(block, 'B', order) || '0';
    let code;
    if (!operator) {
        code = 'MathPow(' + argument0 + ', ' + argument1 + ')';
        return [code, mqlGenerator.ORDER_FUNCTION_CALL];
    }
    code = argument0 + operator + argument1;
    return [code, order];
};

// Variables
mqlGenerator.forBlock['variables_get'] = function (block: Blockly.Block) {
    const code = mqlGenerator.variableDB_.getName(block.getFieldValue('VAR'),
        Blockly.Names.NameType.VARIABLE);
    return [code, mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['variables_set'] = function (block: Blockly.Block) {
    const argument0 = mqlGenerator.valueToCode(block, 'VALUE',
        mqlGenerator.ORDER_ASSIGNMENT) || '0';
    const varName = mqlGenerator.variableDB_.getName(block.getFieldValue('VAR'),
        Blockly.Names.NameType.VARIABLE);
    return varName + ' = ' + argument0 + ';\n';
};

mqlGenerator.forBlock['variables_change'] = function (block: Blockly.Block) {
    const delta = mqlGenerator.valueToCode(block, 'DELTA', mqlGenerator.ORDER_ADDITION) || '0';
    const varName = mqlGenerator.variableDB_.getName(block.getFieldValue('VAR'),
        Blockly.Names.NameType.VARIABLE);
    return varName + ' += ' + delta + ';\n';
};

mqlGenerator.forBlock['function_define'] = function (block: Blockly.Block) {
    const funcName = block.getFieldValue('NAME');
    const stack = mqlGenerator.statementToCode(block, 'STACK');
    return `void ${funcName}() {\n${stack}}\n`;
};

mqlGenerator.forBlock['function_call'] = function (block: Blockly.Block) {
    const funcName = block.getFieldValue('NAME');
    return `${funcName}();\n`;
};

mqlGenerator.forBlock['function_return'] = function (block: Blockly.Block) {
    const value = mqlGenerator.valueToCode(block, 'VALUE', mqlGenerator.ORDER_NONE) || '0';
    return `return ${value};\n`;
};

// =============================================================================
// CUSTOM PROJECT BLOCKS
// =============================================================================

// --- Control Blocks ---
mqlGenerator.forBlock['control_forever'] = function (block: Blockly.Block) {
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    // In MQL, OnTick is the loop. We don't need while(true)
    return doCode;
};

mqlGenerator.forBlock['control_if'] = function (block: Blockly.Block) {
    const condition = mqlGenerator.valueToCode(block, 'CONDITION', mqlGenerator.ORDER_NONE) || 'false';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    return `if (${condition}) {\n${doCode}}\n`;
};

mqlGenerator.forBlock['control_if_else'] = function (block: Blockly.Block) {
    const condition = mqlGenerator.valueToCode(block, 'CONDITION', mqlGenerator.ORDER_NONE) || 'false';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    const elseCode = mqlGenerator.statementToCode(block, 'ELSE');
    return `if (${condition}) {\n${doCode}} else {\n${elseCode}}\n`;
};

mqlGenerator.forBlock['control_repeat'] = function (block: Blockly.Block) {
    const times = mqlGenerator.valueToCode(block, 'TIMES', mqlGenerator.ORDER_NONE) || '1';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    return `for (int i = 0; i < ${times}; i++) {\n${doCode}}\n`;
};

mqlGenerator.forBlock['control_wait'] = function (block: Blockly.Block) {
    const seconds = mqlGenerator.valueToCode(block, 'SECONDS', mqlGenerator.ORDER_NONE) || '1';
    return `Sleep(${seconds} * 1000);\n`;
};

mqlGenerator.forBlock['control_repeat_until'] = function (block: Blockly.Block) {
    const condition = mqlGenerator.valueToCode(block, 'CONDITION', mqlGenerator.ORDER_NONE) || 'false';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    return `while (!(${condition})) {\n${doCode}}\n`;
};

mqlGenerator.forBlock['control_wait_until'] = function (block: Blockly.Block) {
    const condition = mqlGenerator.valueToCode(block, 'CONDITION', mqlGenerator.ORDER_NONE) || 'false';
    return `while (!(${condition})) { Sleep(100); }\n`;
};

mqlGenerator.forBlock['control_stop'] = function () {
    return `return;\n`;
};

// --- Operator Blocks ---
mqlGenerator.forBlock['operator_less'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} < ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_greater'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} > ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_EQUALITY) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_EQUALITY) || '0';
    return [`${left} == ${right}`, mqlGenerator.ORDER_EQUALITY];
};

mqlGenerator.forBlock['operator_less_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} <= ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_greater_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} >= ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_add'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_ADDITION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_ADDITION) || '0';
    return [`${left} + ${right}`, mqlGenerator.ORDER_ADDITION];
};

mqlGenerator.forBlock['operator_subtract'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_SUBTRACTION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_SUBTRACTION) || '0';
    return [`${left} - ${right}`, mqlGenerator.ORDER_SUBTRACTION];
};

mqlGenerator.forBlock['operator_multiply'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_MULTIPLICATION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_MULTIPLICATION) || '0';
    return [`${left} * ${right}`, mqlGenerator.ORDER_MULTIPLICATION];
};

mqlGenerator.forBlock['operator_divide'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_DIVISION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_DIVISION) || '1';
    return [`${left} / ${right}`, mqlGenerator.ORDER_DIVISION];
};

mqlGenerator.forBlock['operator_and'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_LOGICAL_AND) || 'false';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_LOGICAL_AND) || 'false';
    return [`${left} && ${right}`, mqlGenerator.ORDER_LOGICAL_AND];
};

mqlGenerator.forBlock['operator_or'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_LOGICAL_OR) || 'false';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_LOGICAL_OR) || 'false';
    return [`${left} || ${right}`, mqlGenerator.ORDER_LOGICAL_OR];
};

mqlGenerator.forBlock['operator_not'] = function (block: Blockly.Block) {
    const value = mqlGenerator.valueToCode(block, 'VALUE', mqlGenerator.ORDER_LOGICAL_NOT) || 'false';
    return [`!(${value})`, mqlGenerator.ORDER_LOGICAL_NOT];
};

mqlGenerator.forBlock['operator_not_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_EQUALITY) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_EQUALITY) || '0';
    return [`${left} != ${right}`, mqlGenerator.ORDER_EQUALITY];
};

mqlGenerator.forBlock['operator_advanced_math'] = function (block: Blockly.Block) {
    const func = block.getFieldValue('FUNCTION');
    const value = mqlGenerator.valueToCode(block, 'VALUE', mqlGenerator.ORDER_NONE) || '0';
    const mqlFuncMap: { [key: string]: string } = {
        'abs': 'MathAbs',
        'sqrt': 'MathSqrt',
        'sin': 'MathSin',
        'cos': 'MathCos',
        'tan': 'MathTan',
        'log': 'MathLog10',
        'ln': 'MathLog',
        'exp': 'MathExp',
        'round': 'MathRound',
        'floor': 'MathFloor',
        'ceil': 'MathCeil'
    };
    return [`${mqlFuncMap[func]}(${value})`, mqlGenerator.ORDER_FUNCTION_CALL];
};

// --- Environment Blocks ---
mqlGenerator.forBlock['environment_price'] = function () {
    return ['SymbolInfoDouble(Symbol(), SYMBOL_BID)', mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['environment_spread'] = function () {
    return ['(SymbolInfoDouble(Symbol(), SYMBOL_ASK) - SymbolInfoDouble(Symbol(), SYMBOL_BID))', mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['environment_prev_candle_open'] = function (block: Blockly.Block) {
    const timeframe = block.getFieldValue('TIMEFRAME');
    const tfMap: { [key: string]: string } = {
        '1m': 'PERIOD_M1', '5m': 'PERIOD_M5', '15m': 'PERIOD_M15',
        '1h': 'PERIOD_H1', '4h': 'PERIOD_H4', '1d': 'PERIOD_D1'
    };
    return [`iOpen(NULL, ${tfMap[timeframe]}, 1)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['environment_prev_ticker_close'] = function (block: Blockly.Block) {
    const timeframe = block.getFieldValue('TIMEFRAME');
    const tfMap: { [key: string]: string } = {
        '1m': 'PERIOD_M1', '5m': 'PERIOD_M5', '15m': 'PERIOD_M15',
        '1h': 'PERIOD_H1', '4h': 'PERIOD_H4', '1d': 'PERIOD_D1'
    };
    return [`iClose(NULL, ${tfMap[timeframe]}, 1)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['environment_is_market_open'] = function () {
    return ['(IsTradeAllowed() && !IsTradeContextBusy())', mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['environment_time'] = function () {
    return ['TimeCurrent()', mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['environment_day_of_week'] = function () {
    return ['DayOfWeek()', mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['environment_new_candle_open'] = function (block: Blockly.Block) {
    const timeframe = block.getFieldValue('TIMEFRAME') || 'PERIOD_CURRENT';
    const tfMap: { [key: string]: string } = {
        '1m': 'PERIOD_M1', '5m': 'PERIOD_M5', '15m': 'PERIOD_M15', '30m': 'PERIOD_M30',
        '1h': 'PERIOD_H1', '4h': 'PERIOD_H4', '1d': 'PERIOD_D1', '1w': 'PERIOD_W1'
    };
    const period = tfMap[timeframe] || 'PERIOD_CURRENT';

    // Add static variable for time tracking
    const varName = `last_time_${period}`;
    if (!mqlGenerator.definitions_[varName]) {
        mqlGenerator.definitions_[varName] = `datetime ${varName} = 0;`;
    }

    return [`(${varName} != iTime(NULL, ${period}, 0) && (${varName} = iTime(NULL, ${period}, 0)) > 0)`, mqlGenerator.ORDER_ATOMIC];
};

// --- Trading Blocks ---
mqlGenerator.forBlock['trade_order'] = function (block: Blockly.Block) {
    const direction = block.getFieldValue('DIRECTION'); // 'long' or 'short'
    const size = block.getFieldValue('SIZE') || '0.1';

    // MQL5 uses CTrade
    const action = direction === 'long' ? 'Buy' : 'Sell';
    const tradeId = block.getFieldValue('TRADE_ID') || 'trade1';

    return `if(PositionsTotal() == 0) {
    double lotSize = NormalizeLotSize(${size});
    if(!trade.${action}(lotSize, Symbol(), 0, 0, 0, "${tradeId}")) {
        Print("Trade ${action} failed. Return Code: ", trade.ResultRetcode(), ", Desc: ", trade.ResultRetcodeDescription());
    }
}
`;
};

mqlGenerator.forBlock['trade_take_profit'] = function (block: Blockly.Block) {
    const price = mqlGenerator.valueToCode(block, 'PRICE', mqlGenerator.ORDER_NONE) || '0';
    return `for(int i=PositionsTotal()-1; i>=0; i--) {
   ulong ticket = PositionGetTicket(i);
   if(PositionGetString(POSITION_SYMBOL) == Symbol()) {
      double currentTP = PositionGetDouble(POSITION_TP);
      double newTP = ${price};
      long type = PositionGetInteger(POSITION_TYPE);
      double currentPrice = (type == POSITION_TYPE_BUY) ? SymbolInfoDouble(Symbol(), SYMBOL_BID) : SymbolInfoDouble(Symbol(), SYMBOL_ASK);
      int stopsLevel = (int)SymbolInfoInteger(Symbol(), SYMBOL_TRADE_STOPS_LEVEL);
      double minDistance = stopsLevel * _Point;

      bool isValid = false;
      if (type == POSITION_TYPE_BUY) {
          isValid = (newTP > currentPrice + minDistance);
      } else {
          isValid = (newTP < currentPrice - minDistance);
      }

      if(isValid && MathAbs(currentTP - newTP) > _Point) {
          if(!trade.PositionModify(ticket, PositionGetDouble(POSITION_SL), newTP)) {
              Print("Modify TP failed. Code: ", trade.ResultRetcode(), ", Desc: ", trade.ResultRetcodeDescription());
          }
      }
   }
}
`;
};

mqlGenerator.forBlock['trade_stop_loss'] = function (block: Blockly.Block) {
    const price = mqlGenerator.valueToCode(block, 'PRICE', mqlGenerator.ORDER_NONE) || '0';
    return `for(int i=PositionsTotal()-1; i>=0; i--) {
   ulong ticket = PositionGetTicket(i);
   if(PositionGetString(POSITION_SYMBOL) == Symbol()) {
      double currentSL = PositionGetDouble(POSITION_SL);
      double newSL = ${price};
      long type = PositionGetInteger(POSITION_TYPE);
      double currentPrice = (type == POSITION_TYPE_BUY) ? SymbolInfoDouble(Symbol(), SYMBOL_BID) : SymbolInfoDouble(Symbol(), SYMBOL_ASK);
      int stopsLevel = (int)SymbolInfoInteger(Symbol(), SYMBOL_TRADE_STOPS_LEVEL);
      double minDistance = stopsLevel * _Point;

      bool isValid = false;
      if (type == POSITION_TYPE_BUY) {
          isValid = (newSL < currentPrice - minDistance);
      } else {
          isValid = (newSL > currentPrice + minDistance);
      }

      if(isValid && MathAbs(currentSL - newSL) > _Point) {
          if(!trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP))) {
              Print("Modify SL failed. Code: ", trade.ResultRetcode(), ", Desc: ", trade.ResultRetcodeDescription());
          }
      }
   }
}
`;
};

mqlGenerator.forBlock['trade_entry_price'] = function (block: Blockly.Block) {
    // Returns the entry price of the current position (assuming single position for simplicity)
    return [`PositionGetDouble(POSITION_PRICE_OPEN)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['trade_pnl_of'] = function (block: Blockly.Block) {
    return [`PositionGetDouble(POSITION_PROFIT)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['trade_position_size'] = function (block: Blockly.Block) {
    return [`PositionGetDouble(POSITION_VOLUME)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['trade_close'] = function (block: Blockly.Block) {
    const percent = mqlGenerator.valueToCode(block, 'PERCENT', mqlGenerator.ORDER_NONE) || '100';
    const tradeId = block.getFieldValue('TRADE_ID') || 'trade1';

    return `for(int i=PositionsTotal()-1; i>=0; i--) {
   ulong ticket = PositionGetTicket(i);
   if(PositionSelectByTicket(ticket)) {
      if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == 123456 && PositionGetString(POSITION_COMMENT) == "${tradeId}") {
         bool res = false;
         if(${percent} >= 100) {
            res = trade.PositionClose(ticket);
         } else {
            double vol = PositionGetDouble(POSITION_VOLUME) * ${percent} / 100.0;
            res = trade.PositionClosePartial(ticket, vol);
         }
         if(!res) {
             Print("Close failed. Code: ", trade.ResultRetcode(), ", Desc: ", trade.ResultRetcodeDescription());
         }
      }
   }
}
`;
};

mqlGenerator.forBlock['trade_close_all'] = function (block: Blockly.Block) {
    return `for(int i=PositionsTotal()-1; i>=0; i--) {
   ulong ticket = PositionGetTicket(i);
   if(PositionSelectByTicket(ticket)) {
      if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == 123456) {
         if(!trade.PositionClose(ticket)) {
             Print("Close failed. Code: ", trade.ResultRetcode(), ", Desc: ", trade.ResultRetcodeDescription());
         }
      }
   }
}
`;
};

// --- Risk Management Blocks ---
mqlGenerator.forBlock['risk_fixed_amount'] = function (block: Blockly.Block) {
    const amount = mqlGenerator.valueToCode(block, 'AMOUNT', mqlGenerator.ORDER_NONE) || '100';
    return [amount, mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['risk_trailing_stop'] = function (block: Blockly.Block) {
    const percent = mqlGenerator.valueToCode(block, 'PERCENT', mqlGenerator.ORDER_NONE) || '2';
    return `for(int i=PositionsTotal()-1; i>=0; i--) {
   ulong ticket = PositionGetTicket(i);
   if(PositionGetString(POSITION_SYMBOL) == Symbol()) {
      double trailDistance = SymbolInfoDouble(Symbol(), SYMBOL_BID) * ${percent} / 100.0;
      double sl = PositionGetDouble(POSITION_SL);
      double tp = PositionGetDouble(POSITION_TP);
      double open = PositionGetDouble(POSITION_PRICE_OPEN);
      double current = PositionGetDouble(POSITION_PRICE_CURRENT);
      long type = PositionGetInteger(POSITION_TYPE);
      
      double newSL = 0;
      
      if(type == POSITION_TYPE_BUY && current - open > trailDistance) {
         newSL = current - trailDistance;
         if(newSL > sl) {
            if(!trade.PositionModify(ticket, newSL, tp)) {
                Print("Trailing Stop failed. Code: ", trade.ResultRetcode());
            }
         }
      } else if(type == POSITION_TYPE_SELL && open - current > trailDistance) {
         newSL = current + trailDistance;
         if(newSL < sl || sl == 0) {
            if(!trade.PositionModify(ticket, newSL, tp)) {
                Print("Trailing Stop failed. Code: ", trade.ResultRetcode());
            }
         }
      }
   }
}
`;
};

mqlGenerator.forBlock['risk_scale_in'] = function (block: Blockly.Block) {
    const amount = mqlGenerator.valueToCode(block, 'AMOUNT', mqlGenerator.ORDER_NONE) || '50';
    const intervals = mqlGenerator.valueToCode(block, 'INTERVALS', mqlGenerator.ORDER_NONE) || '3';
    return `// Scale in: Add ${amount} units over ${intervals} intervals\n`;
};

mqlGenerator.forBlock['risk_scale_out'] = function (block: Blockly.Block) {
    const amount = mqlGenerator.valueToCode(block, 'AMOUNT', mqlGenerator.ORDER_NONE) || '50';
    const intervals = mqlGenerator.valueToCode(block, 'INTERVALS', mqlGenerator.ORDER_NONE) || '3';
    return `// Scale out: Remove ${amount} units over ${intervals} intervals\n`;
};

mqlGenerator.forBlock['risk_max_drawdown'] = function (block: Blockly.Block) {
    const percent = mqlGenerator.valueToCode(block, 'PERCENT', mqlGenerator.ORDER_NONE) || '20';
    return `if(AccountEquity() / AccountBalance() < (1 - ${percent}/100.0)) {
   Print("Max drawdown reached, stopping trading");
   return;
}
`;
};

mqlGenerator.forBlock['risk_daily_loss_limit'] = function (block: Blockly.Block) {
    const amount = mqlGenerator.valueToCode(block, 'AMOUNT', mqlGenerator.ORDER_NONE) || '500';
    return `// Daily loss limit check: ${amount}\n`;
};

mqlGenerator.forBlock['risk_position_percent'] = function (block: Blockly.Block) {
    const percent = mqlGenerator.valueToCode(block, 'PERCENT', mqlGenerator.ORDER_NONE) || '10';
    return [`(AccountBalance() * ${percent} / 100.0 / SymbolInfoDouble(Symbol(), SYMBOL_BID))`, mqlGenerator.ORDER_DIVISION];
};

mqlGenerator.forBlock['risk_kelly_criterion'] = function (block: Blockly.Block) {
    const winRate = mqlGenerator.valueToCode(block, 'WIN_RATE', mqlGenerator.ORDER_NONE) || '0.6';
    const winLossRatio = mqlGenerator.valueToCode(block, 'WIN_LOSS_RATIO', mqlGenerator.ORDER_NONE) || '2';
    return [`((${winRate} * ${winLossRatio} - (1 - ${winRate})) / ${winLossRatio})`, mqlGenerator.ORDER_DIVISION];
};

// --- Indicator Blocks ---
// Helper to get param value with fallback
const getIndicatorParam = (block: Blockly.Block, paramName: string, defaultValue: any) => {
    return (block as any).indicatorParams?.[paramName] ?? defaultValue;
};

const getIndicatorPeriod = (block: Blockly.Block) => {
    return (block as any).indicatorParams?.['period'] ?? 0; // Default to 0 (PERIOD_CURRENT)
};

mqlGenerator.forBlock['ta_rsi'] = function (block: Blockly.Block) {
    const period = getIndicatorPeriod(block);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_rsi_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iRSI(NULL, ${period}, ${maPeriod}, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_sma'] = function (block: Blockly.Block) {
    const period = getIndicatorPeriod(block);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const shift = getIndicatorParam(block, 'shift', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    // Create a unique key for these parameters
    const paramKey = `sma_${period}_${maPeriod}_${shift}_${appliedPrice}`;

    // Check if we already have a handle for these parameters
    let handleName = mqlGenerator.handleCache_[paramKey];

    if (!handleName) {
        handleName = 'handle_sma_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
        mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
        mqlGenerator.initializations_.push(`${handleName} = iMA(NULL, ${period}, ${maPeriod}, ${shift}, MODE_SMA, ${appliedPrice});`);
        mqlGenerator.handleCache_[paramKey] = handleName;
    }

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_ema'] = function (block: Blockly.Block) {
    const period = getIndicatorPeriod(block);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const shift = getIndicatorParam(block, 'shift', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_ema_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iMA(NULL, ${period}, ${maPeriod}, ${shift}, MODE_EMA, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_bb'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 20);
    const deviation = getIndicatorParam(block, 'deviation', 2.0);
    const shift = getIndicatorParam(block, 'shift', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    const component = block.getFieldValue('COMPONENT') || 'middle';

    const handleName = 'handle_bb_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iBands(NULL, ${period}, ${maPeriod}, ${shift}, ${deviation}, ${appliedPrice});`);

    let buffer = 0; // BASE_LINE
    if (component === 'upper') buffer = 1; // UPPER_BAND
    if (component === 'lower') buffer = 2; // LOWER_BAND

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_macd'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const fastEMA = getIndicatorParam(block, 'fastEMA', 12);
    const slowEMA = getIndicatorParam(block, 'slowEMA', 26);
    const signalSMA = getIndicatorParam(block, 'signalSMA', 9);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    const component = block.getFieldValue('COMPONENT') || 'line';

    const handleName = 'handle_macd_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iMACD(NULL, ${period}, ${fastEMA}, ${slowEMA}, ${signalSMA}, ${appliedPrice});`);

    let buffer = 0; // MAIN_LINE
    if (component === 'signal') buffer = 1; // SIGNAL_LINE

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_atr'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);

    const handleName = 'handle_atr_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iATR(NULL, ${period}, ${maPeriod});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_stochastic'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const kPeriod = getIndicatorParam(block, 'kPeriod', 5);
    const dPeriod = getIndicatorParam(block, 'dPeriod', 3);
    const slowing = getIndicatorParam(block, 'slowing', 3);
    const method = getIndicatorParam(block, 'method', 0);
    const priceField = getIndicatorParam(block, 'price', 0);
    const component = block.getFieldValue('COMPONENT') || 'k';

    const handleName = 'handle_stoch_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iStochastic(NULL, ${period}, ${kPeriod}, ${dPeriod}, ${slowing}, ${method}, ${priceField});`);

    let buffer = 0; // MAIN_LINE (%K)
    if (component === 'd' || component === 'signal') buffer = 1; // SIGNAL_LINE (%D)

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

// Additional indicator blocks
mqlGenerator.forBlock['ta_cci'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_cci_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iCCI(NULL, ${period}, ${maPeriod}, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_adx'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0); // Not used in MQL5 iADX? Check docs. MQL5 iADX(symbol, period, adx_period). No applied_price.
    // Wait, MQL5 iADX signature: iADX(symbol, timeframe, adx_period).
    // MQL4 iADX: iADX(symbol, timeframe, period, applied_price, mode, shift).
    // It seems MQL5 iADX does not take applied_price.

    const handleName = 'handle_adx_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iADX(NULL, ${period}, ${maPeriod});`);

    const component = block.getFieldValue('COMPONENT') || 'main';
    let buffer = 0; // MAIN_LINE
    if (component === 'plus') buffer = 1; // PLUSDI_LINE
    if (component === 'minus') buffer = 2; // MINUSDI_LINE

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_mfi'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const volumeType = 1; // VOLUME_TICK

    const handleName = 'handle_mfi_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iMFI(NULL, ${period}, ${maPeriod}, ${volumeType});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_williams_r'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);

    const handleName = 'handle_wpr_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iWPR(NULL, ${period}, ${maPeriod});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_smma'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const shift = getIndicatorParam(block, 'shift', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_smma_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iMA(NULL, ${period}, ${maPeriod}, ${shift}, MODE_SMMA, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_lwma'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const shift = getIndicatorParam(block, 'shift', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_lwma_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iMA(NULL, ${period}, ${maPeriod}, ${shift}, MODE_LWMA, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['dema'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);

    const handleName = 'handle_dema_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iDEMA(NULL, ${period}, ${maPeriod}, 0, PRICE_CLOSE);`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['tema'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);

    const handleName = 'handle_tema_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iTEMA(NULL, ${period}, ${maPeriod}, 0, PRICE_CLOSE);`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ac'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);

    const handleName = 'handle_ac_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iAC(NULL, ${period});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ao'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);

    const handleName = 'handle_ao_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iAO(NULL, ${period});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['sar'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const step = getIndicatorParam(block, 'step', 0.02);
    const maximum = getIndicatorParam(block, 'maximum', 0.2);

    const handleName = 'handle_sar_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iSAR(NULL, ${period}, ${step}, ${maximum});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['momentum'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_mom_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iMomentum(NULL, ${period}, ${maPeriod}, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['osma'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const fastEMA = getIndicatorParam(block, 'fastEMA', 12);
    const slowEMA = getIndicatorParam(block, 'slowEMA', 26);
    const signalSMA = getIndicatorParam(block, 'signalSMA', 9);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_osma_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iOsMA(NULL, ${period}, ${fastEMA}, ${slowEMA}, ${signalSMA}, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['obv'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);

    const handleName = 'handle_obv_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iOBV(NULL, ${period}, PRICE_CLOSE);`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['stddev'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 20);
    const shift = getIndicatorParam(block, 'shift', 0);
    const method = getIndicatorParam(block, 'method', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_stddev_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iStdDev(NULL, ${period}, ${maPeriod}, ${shift}, ${method}, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['envelopes'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const deviation = getIndicatorParam(block, 'deviation', 0.1);
    const method = getIndicatorParam(block, 'method', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    const component = block.getFieldValue('COMPONENT') || 'upper';

    const handleName = 'handle_env_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iEnvelopes(NULL, ${period}, ${maPeriod}, 0, ${method}, ${appliedPrice}, ${deviation});`);

    let buffer = 0; // UPPER_BAND
    if (component === 'lower') buffer = 1; // LOWER_BAND

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['donchian'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 20);
    const component = block.getFieldValue('COMPONENT') || 'upper';

    const handleName = 'handle_donch_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iCustom(NULL, ${period}, "Donchian", ${maPeriod});`);

    let buffer = 0; // UPPER
    if (component === 'middle') buffer = 1;
    if (component === 'lower') buffer = 2;

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['fractals'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const component = block.getFieldValue('COMPONENT') || 'upper';

    const handleName = 'handle_fract_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iFractals(NULL, ${period});`);

    let buffer = 0; // UPPER
    if (component === 'lower') buffer = 1;

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['alligator'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const jawPeriod = getIndicatorParam(block, 'jawPeriod', 13);
    const teethPeriod = getIndicatorParam(block, 'teethPeriod', 8);
    const lipsPeriod = getIndicatorParam(block, 'lipsPeriod', 5);
    const jawShift = getIndicatorParam(block, 'jawShift', 8);
    const teethShift = getIndicatorParam(block, 'teethShift', 5);
    const lipsShift = getIndicatorParam(block, 'lipsShift', 3);
    const component = block.getFieldValue('COMPONENT') || 'jaw';

    const handleName = 'handle_alli_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iAlligator(NULL, ${period}, ${jawPeriod}, ${jawShift}, ${teethPeriod}, ${teethShift}, ${lipsPeriod}, ${lipsShift}, MODE_SMMA, PRICE_MEDIAN);`);

    let buffer = 0; // JAW
    if (component === 'teeth') buffer = 1;
    if (component === 'lips') buffer = 2;

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ichimoku'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const tenkan = getIndicatorParam(block, 'tenkan', 9);
    const kijun = getIndicatorParam(block, 'kijun', 26);
    const senkou = getIndicatorParam(block, 'senkou', 52);
    const component = block.getFieldValue('COMPONENT') || 'tenkan';

    const handleName = 'handle_ichi_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iIchimoku(NULL, ${period}, ${tenkan}, ${kijun}, ${senkou});`);

    let buffer = 0; // TENKAN
    if (component === 'kijun') buffer = 1;
    if (component === 'senkou_a') buffer = 2;
    if (component === 'senkou_b') buffer = 3;
    if (component === 'chikou') buffer = 4;

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['bearsPower'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 13);

    const handleName = 'handle_bears_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iBearsPower(NULL, ${period}, ${maPeriod}, PRICE_CLOSE);`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['bullsPower'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 13);
    return [`iBullsPower(NULL, ${period}, ${maPeriod}, PRICE_CLOSE, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['force'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 13);
    const method = getIndicatorParam(block, 'method', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_force_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iForce(NULL, ${period}, ${maPeriod}, ${method}, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['bwmfi'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);

    const handleName = 'handle_bwmfi_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iBWMFI(NULL, ${period}, 1);`); // 1 = VOLUME_TICK

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['gator'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const jawPeriod = getIndicatorParam(block, 'jawPeriod', 13);
    const teethPeriod = getIndicatorParam(block, 'teethPeriod', 8);
    const lipsPeriod = getIndicatorParam(block, 'lipsPeriod', 5);
    const jawShift = getIndicatorParam(block, 'jawShift', 8);
    const teethShift = getIndicatorParam(block, 'teethShift', 5);
    const lipsShift = getIndicatorParam(block, 'lipsShift', 3);
    const component = block.getFieldValue('COMPONENT') || 'upper';

    const handleName = 'handle_gator_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iGator(NULL, ${period}, ${jawPeriod}, ${jawShift}, ${teethPeriod}, ${teethShift}, ${lipsPeriod}, ${lipsShift}, MODE_SMMA, PRICE_MEDIAN);`);

    let buffer = 0; // UPPER
    if (component === 'lower') buffer = 1;

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['chaikin'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const fastEMA = getIndicatorParam(block, 'fastEMA', 3);
    const slowEMA = getIndicatorParam(block, 'slowEMA', 10);

    const handleName = 'handle_chaikin_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iCustom(NULL, ${period}, "Chaikin", ${fastEMA}, ${slowEMA});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['demarker'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);

    const handleName = 'handle_demarker_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iDeMarker(NULL, ${period}, ${maPeriod});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['rvi'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 10);
    const component = block.getFieldValue('COMPONENT') || 'main';

    const handleName = 'handle_rvi_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iRVI(NULL, ${period}, ${maPeriod});`);

    let buffer = 0; // MAIN
    if (component === 'signal') buffer = 1;

    return [`GetIndicatorValue(${handleName}, ${buffer}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['volumes'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);

    const handleName = 'handle_vols_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iVolumes(NULL, ${period}, VOLUME_TICK);`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_vwap'] = function (block: Blockly.Block) {
    // VWAP in MQL5 usually requires a custom indicator or manual calculation.
    // For simplicity, we will assume a "VWAP" custom indicator exists or use a simplified calculation.
    // Rewriting the inline calculation for MQL5 is complex due to array handling.
    // We will use iCustom("VWAP") as a placeholder or standard implementation.

    const period = getIndicatorParam(block, 'period', 5);

    const handleName = 'handle_vwap_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iCustom(NULL, ${period}, "VWAP");`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ad'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);

    const handleName = 'handle_ad_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iAD(NULL, ${period}, VOLUME_TICK);`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['trix'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_trix_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iCustom(NULL, ${period}, "TRIX", ${maPeriod}, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['vidya'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);

    const handleName = 'handle_vidya_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iCustom(NULL, ${period}, "VIDYA", ${maPeriod});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ama'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 10);

    const handleName = 'handle_ama_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iCustom(NULL, ${period}, "AMA", ${maPeriod});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['frama'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);

    const handleName = 'handle_frama_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iCustom(NULL, ${period}, "FRAMA", ${maPeriod});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['keltner'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 20);
    const atrPeriod = getIndicatorParam(block, 'atrPeriod', 10);
    const multiplier = getIndicatorParam(block, 'multiplier', 2);

    const handleName = 'handle_keltner_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iCustom(NULL, ${period}, "Keltner", ${maPeriod}, ${atrPeriod}, ${multiplier});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['adxWilder'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);

    const handleName = 'handle_adxw_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iADXWilder(NULL, ${period}, ${maPeriod});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['dmi'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);

    const handleName = 'handle_dmi_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iADXWilder(NULL, ${period}, ${maPeriod});`);

    return [`GetIndicatorValue(${handleName}, 1, 0)`, mqlGenerator.ORDER_FUNCTION_CALL]; // PLUSDI
};

mqlGenerator.forBlock['macd_value'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const fastEMA = getIndicatorParam(block, 'fastEMA', 12);
    const slowEMA = getIndicatorParam(block, 'slowEMA', 26);
    const signalSMA = getIndicatorParam(block, 'signalSMA', 9);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);

    const handleName = 'handle_macd_val_' + block.id.replace(/[^a-zA-Z0-9]/g, '_');
    mqlGenerator.definitions_[handleName] = `int ${handleName} = INVALID_HANDLE;`;
    mqlGenerator.initializations_.push(`${handleName} = iMACD(NULL, ${period}, ${fastEMA}, ${slowEMA}, ${signalSMA}, ${appliedPrice});`);

    return [`GetIndicatorValue(${handleName}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};
