import * as Blockly from 'blockly';

export const mqlGenerator = new Blockly.Generator('MQL') as any;

// Order of operation ENUMs
mqlGenerator.ORDER_ATOMIC = 0;           // 0 "" ...
mqlGenerator.ORDER_NEW = 1.1;            // new
mqlGenerator.ORDER_MEMBER = 1.2;         // . []
mqlGenerator.ORDER_FUNCTION_CALL = 2;    // ()
mqlGenerator.ORDER_INCREMENT = 3;        // ++
mqlGenerator.ORDER_DECREMENT = 3;        // --
mqlGenerator.ORDER_BITWISE_NOT = 4.1;    // ~
mqlGenerator.ORDER_UNARY_PLUS = 4.2;     // +
mqlGenerator.ORDER_UNARY_NEGATION = 4.3; // -
mqlGenerator.ORDER_LOGICAL_NOT = 4.4;    // !
mqlGenerator.ORDER_SIZEOF = 4.5;         // sizeof
mqlGenerator.ORDER_DIVISION = 5.1;       // /
mqlGenerator.ORDER_MULTIPLICATION = 5.2; // *
mqlGenerator.ORDER_MODULUS = 5.3;        // %
mqlGenerator.ORDER_SUBTRACTION = 6.1;    // -
mqlGenerator.ORDER_ADDITION = 6.2;       // +
mqlGenerator.ORDER_BITWISE_SHIFT = 7;    // << >>
mqlGenerator.ORDER_RELATIONAL = 8;       // < <= > >=
mqlGenerator.ORDER_EQUALITY = 9;         // == !=
mqlGenerator.ORDER_BITWISE_AND = 10;     // &
mqlGenerator.ORDER_BITWISE_XOR = 11;     // ^
mqlGenerator.ORDER_BITWISE_OR = 12;      // |
mqlGenerator.ORDER_LOGICAL_AND = 13;     // &&
mqlGenerator.ORDER_LOGICAL_OR = 14;      // ||
mqlGenerator.ORDER_CONDITIONAL = 15;     // ?:
mqlGenerator.ORDER_ASSIGNMENT = 16;      // = += -= *= /= %= <<= >>= &= ^= |=
mqlGenerator.ORDER_COMMA = 17;           // ,
mqlGenerator.ORDER_NONE = 99;            // (...)

// Initial setup
mqlGenerator.init = function (workspace: Blockly.Workspace) {
    // Create a list of defined variables
    const variables = Blockly.Variables.allUsedVarModels(workspace);
    const devars = [];
    for (let i = 0; i < variables.length; i++) {
        devars.push('double ' + mqlGenerator.variableDB_.getName(variables[i].getId(),
            Blockly.Names.NameType.VARIABLE) + ';');
    }
    mqlGenerator.definitions_['variables'] = devars.join('\n');
};

mqlGenerator.finish = function (code: string) {
    // Determine if workspace has actual logic
    const hasCode = code && code.trim().length > 0;

    // If workspace is empty, return simple message instead of boilerplate
    if (!hasCode) {
        return '// Add blocks to your workspace to generate MQL code';
    }

    // Convert global variables to MQL format
    const definitions = [];
    for (let name in mqlGenerator.definitions_) {
        definitions.push(mqlGenerator.definitions_[name]);
    }

    // Basic EA structure with generated code
    return `//+------------------------------------------------------------------+
//|                                             Generated Strategy |
//|                        Generated by PPM                        |
//+------------------------------------------------------------------+
#property copyright "Generated by PPM"
#property link      "https://ppm.example.com"
#property version   "1.00"
#property strict

${definitions.length > 0 ? definitions.join('\n') + '\n' : ''}
//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   return(INIT_SUCCEEDED);
  }
//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
  }
//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
${mqlGenerator.prefixLines(code, mqlGenerator.INDENT)}
  }
//+------------------------------------------------------------------+
`;
};

mqlGenerator.scrub_ = function (block: Blockly.Block, code: string, opt_thisOnly?: boolean) {
    const nextBlock = block.nextConnection && block.nextConnection.targetBlock();
    const nextCode = opt_thisOnly ? '' : mqlGenerator.blockToCode(nextBlock);
    return code + nextCode;
};

// =============================================================================
// STANDARD BLOCKLY BLOCKS
// =============================================================================

// Logic
mqlGenerator.forBlock['controls_if'] = function (block: Blockly.Block) {
    let n = 0;
    let code = '';
    if (mqlGenerator.STATEMENT_PREFIX) {
        code += mqlGenerator.injectId(mqlGenerator.STATEMENT_PREFIX, block);
    }
    do {
        const conditionCode = mqlGenerator.valueToCode(block, 'IF' + n,
            mqlGenerator.ORDER_NONE) || 'false';
        const branchCode = mqlGenerator.statementToCode(block, 'DO' + n);
        code += (n > 0 ? ' else ' : '') +
            'if (' + conditionCode + ') {\n' + branchCode + '}';
        ++n;
    } while (block.getInput('IF' + n));

    if (block.getInput('ELSE') || mqlGenerator.STATEMENT_PREFIX) {
        let branchCode = mqlGenerator.statementToCode(block, 'ELSE');
        if (mqlGenerator.STATEMENT_PREFIX) {
            branchCode = mqlGenerator.prefixLines(
                mqlGenerator.injectId(mqlGenerator.STATEMENT_PREFIX, block),
                mqlGenerator.INDENT) + branchCode;
        }
        code += ' else {\n' + branchCode + '}';
    }
    return code + '\n';
};

mqlGenerator.forBlock['logic_compare'] = function (block: Blockly.Block) {
    const OPERATORS = {
        'EQ': '==',
        'NEQ': '!=',
        'LT': '<',
        'LTE': '<=',
        'GT': '>',
        'GTE': '>='
    };
    const operator = OPERATORS[block.getFieldValue('OP')];
    const order = (operator === '==' || operator === '!=') ?
        mqlGenerator.ORDER_EQUALITY : mqlGenerator.ORDER_RELATIONAL;
    const argument0 = mqlGenerator.valueToCode(block, 'A', order) || '0';
    const argument1 = mqlGenerator.valueToCode(block, 'B', order) || '0';
    const code = argument0 + ' ' + operator + ' ' + argument1;
    return [code, order];
};

mqlGenerator.forBlock['logic_operation'] = function (block: Blockly.Block) {
    const operator = (block.getFieldValue('OP') === 'AND') ? '&&' : '||';
    const order = (operator === '&&') ? mqlGenerator.ORDER_LOGICAL_AND :
        mqlGenerator.ORDER_LOGICAL_OR;
    let argument0 = mqlGenerator.valueToCode(block, 'A', order);
    let argument1 = mqlGenerator.valueToCode(block, 'B', order);
    if (!argument0 && !argument1) {
        argument0 = 'false';
        argument1 = 'false';
    } else {
        const defaultArgument = (operator === '&&') ? 'true' : 'false';
        if (!argument0) argument0 = defaultArgument;
        if (!argument1) argument1 = defaultArgument;
    }
    const code = argument0 + ' ' + operator + ' ' + argument1;
    return [code, order];
};

mqlGenerator.forBlock['logic_boolean'] = function (block: Blockly.Block) {
    const code = (block.getFieldValue('BOOL') === 'TRUE') ? 'true' : 'false';
    return [code, mqlGenerator.ORDER_ATOMIC];
};

// Math
mqlGenerator.forBlock['math_number'] = function (block: Blockly.Block) {
    const code = Number(block.getFieldValue('NUM'));
    const order = code >= 0 ? mqlGenerator.ORDER_ATOMIC :
        mqlGenerator.ORDER_UNARY_NEGATION;
    return [code, order];
};

mqlGenerator.forBlock['math_arithmetic'] = function (block: Blockly.Block) {
    const OPERATORS = {
        'ADD': [' + ', mqlGenerator.ORDER_ADDITION],
        'MINUS': [' - ', mqlGenerator.ORDER_SUBTRACTION],
        'MULTIPLY': [' * ', mqlGenerator.ORDER_MULTIPLICATION],
        'DIVIDE': [' / ', mqlGenerator.ORDER_DIVISION],
        'POWER': [null, mqlGenerator.ORDER_NONE]
    };
    const tuple = OPERATORS[block.getFieldValue('OP')];
    const operator = tuple[0];
    const order = tuple[1];
    const argument0 = mqlGenerator.valueToCode(block, 'A', order) || '0';
    const argument1 = mqlGenerator.valueToCode(block, 'B', order) || '0';
    let code;
    if (!operator) {
        code = 'MathPow(' + argument0 + ', ' + argument1 + ')';
        return [code, mqlGenerator.ORDER_FUNCTION_CALL];
    }
    code = argument0 + operator + argument1;
    return [code, order];
};

// Variables
mqlGenerator.forBlock['variables_get'] = function (block: Blockly.Block) {
    const code = mqlGenerator.variableDB_.getName(block.getFieldValue('VAR'),
        Blockly.Names.NameType.VARIABLE);
    return [code, mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['variables_set'] = function (block: Blockly.Block) {
    const argument0 = mqlGenerator.valueToCode(block, 'VALUE',
        mqlGenerator.ORDER_ASSIGNMENT) || '0';
    const varName = mqlGenerator.variableDB_.getName(block.getFieldValue('VAR'),
        Blockly.Names.NameType.VARIABLE);
    return varName + ' = ' + argument0 + ';\n';
};

mqlGenerator.forBlock['variables_change'] = function (block: Blockly.Block) {
    const delta = mqlGenerator.valueToCode(block, 'DELTA', mqlGenerator.ORDER_ADDITION) || '0';
    const varName = mqlGenerator.variableDB_.getName(block.getFieldValue('VAR'),
        Blockly.Names.NameType.VARIABLE);
    return varName + ' += ' + delta + ';\n';
};

mqlGenerator.forBlock['function_define'] = function (block: Blockly.Block) {
    const funcName = block.getFieldValue('NAME');
    const stack = mqlGenerator.statementToCode(block, 'STACK');
    return `void ${funcName}() {\n${stack}}\n`;
};

mqlGenerator.forBlock['function_call'] = function (block: Blockly.Block) {
    const funcName = block.getFieldValue('NAME');
    return `${funcName}();\n`;
};

mqlGenerator.forBlock['function_return'] = function (block: Blockly.Block) {
    const value = mqlGenerator.valueToCode(block, 'VALUE', mqlGenerator.ORDER_NONE) || '0';
    return `return ${value};\n`;
};

// =============================================================================
// CUSTOM PROJECT BLOCKS
// =============================================================================

// --- Control Blocks ---
mqlGenerator.forBlock['control_forever'] = function (block: Blockly.Block) {
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    // In MQL, OnTick is the loop. We don't need while(true)
    return doCode;
};

mqlGenerator.forBlock['control_if'] = function (block: Blockly.Block) {
    const condition = mqlGenerator.valueToCode(block, 'CONDITION', mqlGenerator.ORDER_NONE) || 'false';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    return `if (${condition}) {\n${doCode}}\n`;
};

mqlGenerator.forBlock['control_if_else'] = function (block: Blockly.Block) {
    const condition = mqlGenerator.valueToCode(block, 'CONDITION', mqlGenerator.ORDER_NONE) || 'false';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    const elseCode = mqlGenerator.statementToCode(block, 'ELSE');
    return `if (${condition}) {\n${doCode}} else {\n${elseCode}}\n`;
};

mqlGenerator.forBlock['control_repeat'] = function (block: Blockly.Block) {
    const times = mqlGenerator.valueToCode(block, 'TIMES', mqlGenerator.ORDER_NONE) || '1';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    return `for (int i = 0; i < ${times}; i++) {\n${doCode}}\n`;
};

mqlGenerator.forBlock['control_wait'] = function (block: Blockly.Block) {
    const seconds = mqlGenerator.valueToCode(block, 'SECONDS', mqlGenerator.ORDER_NONE) || '1';
    return `Sleep(${seconds} * 1000);\n`;
};

mqlGenerator.forBlock['control_repeat_until'] = function (block: Blockly.Block) {
    const condition = mqlGenerator.valueToCode(block, 'CONDITION', mqlGenerator.ORDER_NONE) || 'false';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    return `while (!(${condition})) {\n${doCode}}\n`;
};

mqlGenerator.forBlock['control_wait_until'] = function (block: Blockly.Block) {
    const condition = mqlGenerator.valueToCode(block, 'CONDITION', mqlGenerator.ORDER_NONE) || 'false';
    return `while (!(${condition})) { Sleep(100); }\n`;
};

mqlGenerator.forBlock['control_stop'] = function () {
    return `return;\n`;
};

// --- Operator Blocks ---
mqlGenerator.forBlock['operator_less'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} < ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_greater'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} > ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_EQUALITY) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_EQUALITY) || '0';
    return [`${left} == ${right}`, mqlGenerator.ORDER_EQUALITY];
};

mqlGenerator.forBlock['operator_less_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} <= ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_greater_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} >= ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_add'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_ADDITION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_ADDITION) || '0';
    return [`${left} + ${right}`, mqlGenerator.ORDER_ADDITION];
};

mqlGenerator.forBlock['operator_subtract'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_SUBTRACTION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_SUBTRACTION) || '0';
    return [`${left} - ${right}`, mqlGenerator.ORDER_SUBTRACTION];
};

mqlGenerator.forBlock['operator_multiply'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_MULTIPLICATION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_MULTIPLICATION) || '0';
    return [`${left} * ${right}`, mqlGenerator.ORDER_MULTIPLICATION];
};

mqlGenerator.forBlock['operator_divide'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_DIVISION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_DIVISION) || '1';
    return [`${left} / ${right}`, mqlGenerator.ORDER_DIVISION];
};

mqlGenerator.forBlock['operator_and'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_LOGICAL_AND) || 'false';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_LOGICAL_AND) || 'false';
    return [`${left} && ${right}`, mqlGenerator.ORDER_LOGICAL_AND];
};

mqlGenerator.forBlock['operator_or'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_LOGICAL_OR) || 'false';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_LOGICAL_OR) || 'false';
    return [`${left} || ${right}`, mqlGenerator.ORDER_LOGICAL_OR];
};

mqlGenerator.forBlock['operator_not'] = function (block: Blockly.Block) {
    const value = mqlGenerator.valueToCode(block, 'VALUE', mqlGenerator.ORDER_LOGICAL_NOT) || 'false';
    return [`!(${value})`, mqlGenerator.ORDER_LOGICAL_NOT];
};

mqlGenerator.forBlock['operator_not_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_EQUALITY) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_EQUALITY) || '0';
    return [`${left} != ${right}`, mqlGenerator.ORDER_EQUALITY];
};

mqlGenerator.forBlock['operator_advanced_math'] = function (block: Blockly.Block) {
    const func = block.getFieldValue('FUNCTION');
    const value = mqlGenerator.valueToCode(block, 'VALUE', mqlGenerator.ORDER_NONE) || '0';
    const mqlFuncMap: { [key: string]: string } = {
        'abs': 'MathAbs',
        'sqrt': 'MathSqrt',
        'sin': 'MathSin',
        'cos': 'MathCos',
        'tan': 'MathTan',
        'log': 'MathLog10',
        'ln': 'MathLog',
        'exp': 'MathExp',
        'round': 'MathRound',
        'floor': 'MathFloor',
        'ceil': 'MathCeil'
    };
    return [`${mqlFuncMap[func]}(${value})`, mqlGenerator.ORDER_FUNCTION_CALL];
};

// --- Environment Blocks ---
mqlGenerator.forBlock['environment_price'] = function () {
    return ['Close[0]', mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['environment_spread'] = function () {
    return ['(Ask - Bid)', mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['environment_prev_candle_open'] = function (block: Blockly.Block) {
    const timeframe = block.getFieldValue('TIMEFRAME');
    const tfMap: { [key: string]: string } = {
        '1m': 'PERIOD_M1', '5m': 'PERIOD_M5', '15m': 'PERIOD_M15',
        '1h': 'PERIOD_H1', '4h': 'PERIOD_H4', '1d': 'PERIOD_D1'
    };
    return [`iOpen(NULL, ${tfMap[timeframe]}, 1)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['environment_prev_ticker_close'] = function (block: Blockly.Block) {
    const timeframe = block.getFieldValue('TIMEFRAME');
    const tfMap: { [key: string]: string } = {
        '1m': 'PERIOD_M1', '5m': 'PERIOD_M5', '15m': 'PERIOD_M15',
        '1h': 'PERIOD_H1', '4h': 'PERIOD_H4', '1d': 'PERIOD_D1'
    };
    return [`iClose(NULL, ${tfMap[timeframe]}, 1)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['environment_is_market_open'] = function () {
    return ['(IsTradeAllowed() && !IsTradeContextBusy())', mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['environment_time'] = function () {
    return ['TimeCurrent()', mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['environment_day_of_week'] = function () {
    return ['DayOfWeek()', mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['environment_new_candle_open'] = function (block: Blockly.Block) {
    const timeframe = block.getFieldValue('TIMEFRAME');
    const tfMap: { [key: string]: string } = {
        '1m': 'PERIOD_M1', '5m': 'PERIOD_M5', '15m': 'PERIOD_M15',
        '1h': 'PERIOD_H1', '4h': 'PERIOD_H4', '1d': 'PERIOD_D1'
    };
    return [`(iTime(NULL, ${tfMap[timeframe]}, 0) != iTime(NULL, ${tfMap[timeframe]}, 1))`, mqlGenerator.ORDER_RELATIONAL];
};

// --- Trading Blocks ---
mqlGenerator.forBlock['trade_order'] = function (block: Blockly.Block) {
    const direction = block.getFieldValue('DIRECTION'); // 'long' or 'short'
    const size = block.getFieldValue('SIZE') || '0.1';
    const cmd = direction === 'long' ? 'OP_BUY' : 'OP_SELL';
    const price = direction === 'long' ? 'Ask' : 'Bid';
    const color = direction === 'long' ? 'clrGreen' : 'clrRed';

    return `if(OrdersTotal() == 0) {
   int ticket = OrderSend(Symbol(), ${cmd}, ${size}, ${price}, 3, 0, 0, "PPM Strategy", 12345, 0, ${color});
   if(ticket < 0) Print("OrderSend failed with error #", GetLastError());
}
`;
};

mqlGenerator.forBlock['trade_take_profit'] = function (block: Blockly.Block) {
    const price = mqlGenerator.valueToCode(block, 'PRICE', mqlGenerator.ORDER_NONE) || '0';
    return `for(int i=OrdersTotal()-1; i>=0; i--) {
   if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
      if(OrderSymbol() == Symbol() && OrderMagicNumber() == 12345) {
         if(!OrderModify(OrderTicket(), OrderOpenPrice(), OrderStopLoss(), ${price}, 0, clrNONE)) {
            Print("OrderModify TP failed error #", GetLastError());
         }
      }
   }
}
`;
};

mqlGenerator.forBlock['trade_stop_loss'] = function (block: Blockly.Block) {
    const price = mqlGenerator.valueToCode(block, 'PRICE', mqlGenerator.ORDER_NONE) || '0';
    return `for(int i=OrdersTotal()-1; i>=0; i--) {
   if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
      if(OrderSymbol() == Symbol() && OrderMagicNumber() == 12345) {
         if(!OrderModify(OrderTicket(), OrderOpenPrice(), ${price}, OrderTakeProfit(), 0, clrNONE)) {
            Print("OrderModify SL failed error #", GetLastError());
         }
      }
   }
}
`;
};

mqlGenerator.forBlock['trade_entry_price'] = function (block: Blockly.Block) {
    // Returns the entry price of the current position
    return [`OrderOpenPrice()`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['trade_pnl_of'] = function (block: Blockly.Block) {
    return [`OrderProfit()`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['trade_position_size'] = function (block: Blockly.Block) {
    return [`OrderLots()`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['trade_close'] = function (block: Blockly.Block) {
    const percent = mqlGenerator.valueToCode(block, 'PERCENT', mqlGenerator.ORDER_NONE) || '100';
    return `for(int i=OrdersTotal()-1; i>=0; i--) {
   if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
      if(OrderSymbol() == Symbol() && OrderMagicNumber() == 12345) {
         double lotsToClose = OrderLots() * ${percent} / 100.0;
         if(OrderType() == OP_BUY) {
            if(!OrderClose(OrderTicket(), lotsToClose, Bid, 3, clrNONE)) {
               Print("OrderClose failed error #", GetLastError());
            }
         } else if(OrderType() == OP_SELL) {
            if(!OrderClose(OrderTicket(), lotsToClose, Ask, 3, clrNONE)) {
               Print("OrderClose failed error #", GetLastError());
            }
         }
      }
   }
}
`;
};

// --- Risk Management Blocks ---
mqlGenerator.forBlock['risk_fixed_amount'] = function (block: Blockly.Block) {
    const amount = mqlGenerator.valueToCode(block, 'AMOUNT', mqlGenerator.ORDER_NONE) || '100';
    return [amount, mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['risk_trailing_stop'] = function (block: Blockly.Block) {
    const percent = mqlGenerator.valueToCode(block, 'PERCENT', mqlGenerator.ORDER_NONE) || '2';
    return `for(int i=OrdersTotal()-1; i>=0; i--) {
   if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
      if(OrderSymbol() == Symbol() && OrderMagicNumber() == 12345) {
         double trailDistance = Close[0] * ${percent} / 100.0;
         double newSL = 0;
         if(OrderType() == OP_BUY && Close[0] - OrderOpenPrice() > trailDistance) {
            newSL = Close[0] - trailDistance;
            if(newSL > OrderStopLoss()) {
               OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrNONE);
            }
         } else if(OrderType() == OP_SELL && OrderOpenPrice() - Close[0] > trailDistance) {
            newSL = Close[0] + trailDistance;
            if(newSL < OrderStopLoss() || OrderStopLoss() == 0) {
               OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrNONE);
            }
         }
      }
   }
}
`;
};

mqlGenerator.forBlock['risk_scale_in'] = function (block: Blockly.Block) {
    const amount = mqlGenerator.valueToCode(block, 'AMOUNT', mqlGenerator.ORDER_NONE) || '50';
    const intervals = mqlGenerator.valueToCode(block, 'INTERVALS', mqlGenerator.ORDER_NONE) || '3';
    return `// Scale in: Add ${amount} units over ${intervals} intervals\n`;
};

mqlGenerator.forBlock['risk_scale_out'] = function (block: Blockly.Block) {
    const amount = mqlGenerator.valueToCode(block, 'AMOUNT', mqlGenerator.ORDER_NONE) || '50';
    const intervals = mqlGenerator.valueToCode(block, 'INTERVALS', mqlGenerator.ORDER_NONE) || '3';
    return `// Scale out: Remove ${amount} units over ${intervals} intervals\n`;
};

mqlGenerator.forBlock['risk_max_drawdown'] = function (block: Blockly.Block) {
    const percent = mqlGenerator.valueToCode(block, 'PERCENT', mqlGenerator.ORDER_NONE) || '20';
    return `if(AccountEquity() / AccountBalance() < (1 - ${percent}/100.0)) {
   Print("Max drawdown reached, stopping trading");
   return;
}
`;
};

mqlGenerator.forBlock['risk_daily_loss_limit'] = function (block: Blockly.Block) {
    const amount = mqlGenerator.valueToCode(block, 'AMOUNT', mqlGenerator.ORDER_NONE) || '500';
    return `// Daily loss limit check: ${amount}\n`;
};

mqlGenerator.forBlock['risk_position_percent'] = function (block: Blockly.Block) {
    const percent = mqlGenerator.valueToCode(block, 'PERCENT', mqlGenerator.ORDER_NONE) || '10';
    return [`(AccountBalance() * ${percent} / 100.0 / Close[0])`, mqlGenerator.ORDER_DIVISION];
};

mqlGenerator.forBlock['risk_kelly_criterion'] = function (block: Blockly.Block) {
    const winRate = mqlGenerator.valueToCode(block, 'WIN_RATE', mqlGenerator.ORDER_NONE) || '0.6';
    const winLossRatio = mqlGenerator.valueToCode(block, 'WIN_LOSS_RATIO', mqlGenerator.ORDER_NONE) || '2';
    return [`((${winRate} * ${winLossRatio} - (1 - ${winRate})) / ${winLossRatio})`, mqlGenerator.ORDER_DIVISION];
};

// --- Indicator Blocks ---
// Helper to get param value with fallback
const getIndicatorParam = (block: Blockly.Block, paramName: string, defaultValue: any) => {
    return (block as any).indicatorParams?.[paramName] ?? defaultValue;
};

mqlGenerator.forBlock['ta_rsi'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    // iRSI(symbol, timeframe, period, applied_price, shift)
    return [`iRSI(NULL, ${period}, ${maPeriod}, ${appliedPrice}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_sma'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const shift = getIndicatorParam(block, 'shift', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    // iMA(symbol, timeframe, period, ma_shift, ma_method, applied_price, shift)
    return [`iMA(NULL, ${period}, ${maPeriod}, ${shift}, MODE_SMA, ${appliedPrice}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_ema'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const shift = getIndicatorParam(block, 'shift', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    // iMA(symbol, timeframe, period, ma_shift, ma_method, applied_price, shift)
    return [`iMA(NULL, ${period}, ${maPeriod}, ${shift}, MODE_EMA, ${appliedPrice}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_bb'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 20);
    const deviation = getIndicatorParam(block, 'deviation', 2.0);
    const shift = getIndicatorParam(block, 'shift', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    // iBands(symbol, timeframe, period, deviation, bands_shift, applied_price, mode, shift)
    // Note: Assuming middle band - blocks should specify which band they want
    return [`iBands(NULL, ${period}, ${maPeriod}, ${deviation}, ${shift}, ${appliedPrice}, MODE_MAIN, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_macd'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const fastEMA = getIndicatorParam(block, 'fastEMA', 12);
    const slowEMA = getIndicatorParam(block, 'slowEMA', 26);
    const signalSMA = getIndicatorParam(block, 'signalSMA', 9);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    // iMACD(symbol, timeframe, fast_ema, slow_ema, signal_sma, applied_price, mode, shift)
    // Note: Assuming main line - blocks should specify which line they want
    return [`iMACD(NULL, ${period}, ${fastEMA}, ${slowEMA}, ${signalSMA}, ${appliedPrice}, MODE_MAIN, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_atr'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    // iATR(symbol, timeframe, period, shift)
    return [`iATR(NULL, ${period}, ${maPeriod}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_stochastic'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const kPeriod = getIndicatorParam(block, 'kPeriod', 5);
    const dPeriod = getIndicatorParam(block, 'dPeriod', 3);
    const slowing = getIndicatorParam(block, 'slowing', 3);
    const method = getIndicatorParam(block, 'method', 0);
    const priceField = getIndicatorParam(block, 'price', 0);
    // iStochastic(symbol, timeframe, %K, %D, slowing, method, price_field, mode, shift)
    // Note: Assuming main line - blocks should specify which line they want
    return [`iStochastic(NULL, ${period}, ${kPeriod}, ${dPeriod}, ${slowing}, ${method}, ${priceField}, MODE_MAIN, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

// Additional indicator blocks
mqlGenerator.forBlock['ta_cci'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iCCI(NULL, ${period}, ${maPeriod}, ${appliedPrice}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_adx'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iADX(NULL, ${period}, ${maPeriod}, ${appliedPrice}, MODE_MAIN, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_mfi'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    return [`iMFI(NULL, ${period}, ${maPeriod}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_williams_r'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    return [`iWPR(NULL, ${period}, ${maPeriod}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_smma'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const shift = getIndicatorParam(block, 'shift', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iMA(NULL, ${period}, ${maPeriod}, ${shift}, MODE_SMMA, ${appliedPrice}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_lwma'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const shift = getIndicatorParam(block, 'shift', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iMA(NULL, ${period}, ${maPeriod}, ${shift}, MODE_LWMA, ${appliedPrice}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['dema'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    return [`iDEMA(NULL, ${period}, ${maPeriod}, 0, PRICE_CLOSE, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['tema'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    return [`iTEMA(NULL, ${period}, ${maPeriod}, 0, PRICE_CLOSE, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ac'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    return [`iAC(NULL, ${period}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ao'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    return [`iAO(NULL, ${period}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['sar'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const step = getIndicatorParam(block, 'step', 0.02);
    const maximum = getIndicatorParam(block, 'maximum', 0.2);
    return [`iSAR(NULL, ${period}, ${step}, ${maximum}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['momentum'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iMomentum(NULL, ${period}, ${maPeriod}, ${appliedPrice}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['osma'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const fastEMA = getIndicatorParam(block, 'fastEMA', 12);
    const slowEMA = getIndicatorParam(block, 'slowEMA', 26);
    const signalSMA = getIndicatorParam(block, 'signalSMA', 9);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iOsMA(NULL, ${period}, ${fastEMA}, ${slowEMA}, ${signalSMA}, ${appliedPrice}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['obv'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    return [`iOBV(NULL, ${period}, PRICE_CLOSE, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['stddev'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 20);
    const shift = getIndicatorParam(block, 'shift', 0);
    const method = getIndicatorParam(block, 'method', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iStdDev(NULL, ${period}, ${maPeriod}, ${shift}, ${method}, ${appliedPrice}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['envelopes'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const deviation = getIndicatorParam(block, 'deviation', 0.1);
    const method = getIndicatorParam(block, 'method', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iEnvelopes(NULL, ${period}, ${maPeriod}, 0, ${method}, ${appliedPrice}, ${deviation}, MODE_UPPER, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['donchian'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 20);
    return [`iCustom(NULL, ${period}, "Donchian", ${maPeriod}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['fractals'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    return [`iFractals(NULL, ${period}, MODE_UPPER, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['alligator'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const jawPeriod = getIndicatorParam(block, 'jawPeriod', 13);
    const teethPeriod = getIndicatorParam(block, 'teethPeriod', 8);
    const lipsPeriod = getIndicatorParam(block, 'lipsPeriod', 5);
    const jawShift = getIndicatorParam(block, 'jawShift', 8);
    const teethShift = getIndicatorParam(block, 'teethShift', 5);
    const lipsShift = getIndicatorParam(block, 'lipsShift', 3);
    return [`iAlligator(NULL, ${period}, ${jawPeriod}, ${jawShift}, ${teethPeriod}, ${teethShift}, ${lipsPeriod}, ${lipsShift}, MODE_SMMA, PRICE_MEDIAN, MODE_GATORJAW, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ichimoku'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const tenkan = getIndicatorParam(block, 'tenkan', 9);
    const kijun = getIndicatorParam(block, 'kijun', 26);
    const senkou = getIndicatorParam(block, 'senkou', 52);
    return [`iIchimoku(NULL, ${period}, ${tenkan}, ${kijun}, ${senkou}, MODE_TENKANSEN, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['bearsPower'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 13);
    return [`iBearsPower(NULL, ${period}, ${maPeriod}, PRICE_CLOSE, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['bullsPower'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 13);
    return [`iBullsPower(NULL, ${period}, ${maPeriod}, PRICE_CLOSE, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['force'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 13);
    const method = getIndicatorParam(block, 'method', 0);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iForce(NULL, ${period}, ${maPeriod}, ${method}, ${appliedPrice}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['bwmfi'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    return [`iBWMFI(NULL, ${period}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['gator'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const jawPeriod = getIndicatorParam(block, 'jawPeriod', 13);
    const teethPeriod = getIndicatorParam(block, 'teethPeriod', 8);
    const lipsPeriod = getIndicatorParam(block, 'lipsPeriod', 5);
    return [`iGator(NULL, ${period}, ${jawPeriod}, 8, ${teethPeriod}, 5, ${lipsPeriod}, 3, MODE_SMMA, PRICE_MEDIAN, MODE_UPPER, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['chaikin'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const fastEMA = getIndicatorParam(block, 'fastEMA', 3);
    const slowEMA = getIndicatorParam(block, 'slowEMA', 10);
    return [`iCustom(NULL, ${period}, "Chaikin", ${fastEMA}, ${slowEMA}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['demarker'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    return [`iDeMarker(NULL, ${period}, ${maPeriod}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['rvi'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 10);
    return [`iRVI(NULL, ${period}, ${maPeriod}, MODE_MAIN, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['volumes'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    return [`iVolume(NULL, ${period}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_vwap'] = function (block: Blockly.Block) {
    // Add VWAP calculation function to definitions if not already present
    if (!mqlGenerator.definitions_['vwap_function']) {
        mqlGenerator.definitions_['vwap_function'] = `
// VWAP Calculation Function
double CalculateVWAP(int shift = 0)
{
   datetime currentBarTime = iTime(NULL, 0, shift);
   datetime dayStart = currentBarTime - (currentBarTime % 86400); // Start of current day
   
   double cumulativeTPV = 0; // Cumulative (Typical Price * Volume)
   double cumulativeVolume = 0;
   
   // Find the bar index at the start of the day
   int dayStartBar = iBarShift(NULL, 0, dayStart);
   
   // Calculate from start of day to current bar
   for(int i = dayStartBar; i >= shift; i--)
   {
      double typicalPrice = (iHigh(NULL, 0, i) + iLow(NULL, 0, i) + iClose(NULL, 0, i)) / 3.0;
      double volume = iVolume(NULL, 0, i);
      
      cumulativeTPV += typicalPrice * volume;
      cumulativeVolume += volume;
   }
   
   // Avoid division by zero
   if(cumulativeVolume > 0)
      return cumulativeTPV / cumulativeVolume;
   else
      return iClose(NULL, 0, shift); // Return close price if no volume data
}`;
    }
    
    return [`CalculateVWAP(0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ad'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    return [`iAD(NULL, ${period}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['trix'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iCustom(NULL, ${period}, "TRIX", ${maPeriod}, ${appliedPrice}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['vidya'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    return [`iCustom(NULL, ${period}, "VIDYA", ${maPeriod}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ama'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 10);
    return [`iCustom(NULL, ${period}, "AMA", ${maPeriod}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['frama'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    return [`iCustom(NULL, ${period}, "FRAMA", ${maPeriod}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['keltner'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 20);
    const atrPeriod = getIndicatorParam(block, 'atrPeriod', 10);
    const multiplier = getIndicatorParam(block, 'multiplier', 2);
    return [`iCustom(NULL, ${period}, "Keltner", ${maPeriod}, ${atrPeriod}, ${multiplier}, 0, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['adxWilder'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    return [`iADX(NULL, ${period}, ${maPeriod}, PRICE_CLOSE, MODE_MAIN, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['dmi'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const maPeriod = getIndicatorParam(block, 'ma_period', 14);
    return [`iADX(NULL, ${period}, ${maPeriod}, PRICE_CLOSE, MODE_PLUSDI, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['macd_value'] = function (block: Blockly.Block) {
    const period = getIndicatorParam(block, 'period', 5);
    const fastEMA = getIndicatorParam(block, 'fastEMA', 12);
    const slowEMA = getIndicatorParam(block, 'slowEMA', 26);
    const signalSMA = getIndicatorParam(block, 'signalSMA', 9);
    const appliedPrice = getIndicatorParam(block, 'applied_price', 0);
    return [`iMACD(NULL, ${period}, ${fastEMA}, ${slowEMA}, ${signalSMA}, ${appliedPrice}, MODE_MAIN, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};
