import * as Blockly from 'blockly';

export const mqlGenerator = new Blockly.Generator('MQL') as any;

// Order of operation ENUMs
mqlGenerator.ORDER_ATOMIC = 0;           // 0 "" ...
mqlGenerator.ORDER_NEW = 1.1;            // new
mqlGenerator.ORDER_MEMBER = 1.2;         // . []
mqlGenerator.ORDER_FUNCTION_CALL = 2;    // ()
mqlGenerator.ORDER_INCREMENT = 3;        // ++
mqlGenerator.ORDER_DECREMENT = 3;        // --
mqlGenerator.ORDER_BITWISE_NOT = 4.1;    // ~
mqlGenerator.ORDER_UNARY_PLUS = 4.2;     // +
mqlGenerator.ORDER_UNARY_NEGATION = 4.3; // -
mqlGenerator.ORDER_LOGICAL_NOT = 4.4;    // !
mqlGenerator.ORDER_SIZEOF = 4.5;         // sizeof
mqlGenerator.ORDER_DIVISION = 5.1;       // /
mqlGenerator.ORDER_MULTIPLICATION = 5.2; // *
mqlGenerator.ORDER_MODULUS = 5.3;        // %
mqlGenerator.ORDER_SUBTRACTION = 6.1;    // -
mqlGenerator.ORDER_ADDITION = 6.2;       // +
mqlGenerator.ORDER_BITWISE_SHIFT = 7;    // << >>
mqlGenerator.ORDER_RELATIONAL = 8;       // < <= > >=
mqlGenerator.ORDER_EQUALITY = 9;         // == !=
mqlGenerator.ORDER_BITWISE_AND = 10;     // &
mqlGenerator.ORDER_BITWISE_XOR = 11;     // ^
mqlGenerator.ORDER_BITWISE_OR = 12;      // |
mqlGenerator.ORDER_LOGICAL_AND = 13;     // &&
mqlGenerator.ORDER_LOGICAL_OR = 14;      // ||
mqlGenerator.ORDER_CONDITIONAL = 15;     // ?:
mqlGenerator.ORDER_ASSIGNMENT = 16;      // = += -= *= /= %= <<= >>= &= ^= |=
mqlGenerator.ORDER_COMMA = 17;           // ,
mqlGenerator.ORDER_NONE = 99;            // (...)

// Initial setup
mqlGenerator.init = function (workspace: Blockly.Workspace) {
    // Create a list of defined variables
    const variables = Blockly.Variables.allUsedVarModels(workspace);
    const devars = [];
    for (let i = 0; i < variables.length; i++) {
        devars.push('double ' + mqlGenerator.variableDB_.getName(variables[i].getId(),
            Blockly.Names.NameType.VARIABLE) + ';');
    }
    mqlGenerator.definitions_['variables'] = devars.join('\n');
};

mqlGenerator.finish = function (code: string) {
    // Determine if workspace has actual logic
    const hasCode = code && code.trim().length > 0;

    // If workspace is empty, return simple message instead of boilerplate
    if (!hasCode) {
        return '// Add blocks to your workspace to generate MQL code';
    }

    // Convert global variables to MQL format
    const definitions = [];
    for (let name in mqlGenerator.definitions_) {
        definitions.push(mqlGenerator.definitions_[name]);
    }

    // Basic EA structure with generated code
    return `//+------------------------------------------------------------------+
//|                                             Generated Strategy |
//|                        Generated by PPM                        |
//+------------------------------------------------------------------+
#property copyright "Generated by PPM"
#property link      "https://ppm.example.com"
#property version   "1.00"
#property strict

${definitions.length > 0 ? definitions.join('\n') + '\n' : ''}
//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   return(INIT_SUCCEEDED);
  }
//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
  }
//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
${mqlGenerator.prefixLines(code, mqlGenerator.INDENT)}
  }
//+------------------------------------------------------------------+
`;
};

mqlGenerator.scrub_ = function (block: Blockly.Block, code: string, opt_thisOnly?: boolean) {
    const nextBlock = block.nextConnection && block.nextConnection.targetBlock();
    const nextCode = opt_thisOnly ? '' : mqlGenerator.blockToCode(nextBlock);
    return code + nextCode;
};

// =============================================================================
// STANDARD BLOCKLY BLOCKS
// =============================================================================

// Logic
mqlGenerator.forBlock['controls_if'] = function (block: Blockly.Block) {
    let n = 0;
    let code = '';
    if (mqlGenerator.STATEMENT_PREFIX) {
        code += mqlGenerator.injectId(mqlGenerator.STATEMENT_PREFIX, block);
    }
    do {
        const conditionCode = mqlGenerator.valueToCode(block, 'IF' + n,
            mqlGenerator.ORDER_NONE) || 'false';
        const branchCode = mqlGenerator.statementToCode(block, 'DO' + n);
        code += (n > 0 ? ' else ' : '') +
            'if (' + conditionCode + ') {\n' + branchCode + '}';
        ++n;
    } while (block.getInput('IF' + n));

    if (block.getInput('ELSE') || mqlGenerator.STATEMENT_PREFIX) {
        let branchCode = mqlGenerator.statementToCode(block, 'ELSE');
        if (mqlGenerator.STATEMENT_PREFIX) {
            branchCode = mqlGenerator.prefixLines(
                mqlGenerator.injectId(mqlGenerator.STATEMENT_PREFIX, block),
                mqlGenerator.INDENT) + branchCode;
        }
        code += ' else {\n' + branchCode + '}';
    }
    return code + '\n';
};

mqlGenerator.forBlock['logic_compare'] = function (block: Blockly.Block) {
    const OPERATORS = {
        'EQ': '==',
        'NEQ': '!=',
        'LT': '<',
        'LTE': '<=',
        'GT': '>',
        'GTE': '>='
    };
    const operator = OPERATORS[block.getFieldValue('OP')];
    const order = (operator === '==' || operator === '!=') ?
        mqlGenerator.ORDER_EQUALITY : mqlGenerator.ORDER_RELATIONAL;
    const argument0 = mqlGenerator.valueToCode(block, 'A', order) || '0';
    const argument1 = mqlGenerator.valueToCode(block, 'B', order) || '0';
    const code = argument0 + ' ' + operator + ' ' + argument1;
    return [code, order];
};

mqlGenerator.forBlock['logic_operation'] = function (block: Blockly.Block) {
    const operator = (block.getFieldValue('OP') === 'AND') ? '&&' : '||';
    const order = (operator === '&&') ? mqlGenerator.ORDER_LOGICAL_AND :
        mqlGenerator.ORDER_LOGICAL_OR;
    let argument0 = mqlGenerator.valueToCode(block, 'A', order);
    let argument1 = mqlGenerator.valueToCode(block, 'B', order);
    if (!argument0 && !argument1) {
        argument0 = 'false';
        argument1 = 'false';
    } else {
        const defaultArgument = (operator === '&&') ? 'true' : 'false';
        if (!argument0) argument0 = defaultArgument;
        if (!argument1) argument1 = defaultArgument;
    }
    const code = argument0 + ' ' + operator + ' ' + argument1;
    return [code, order];
};

mqlGenerator.forBlock['logic_boolean'] = function (block: Blockly.Block) {
    const code = (block.getFieldValue('BOOL') === 'TRUE') ? 'true' : 'false';
    return [code, mqlGenerator.ORDER_ATOMIC];
};

// Math
mqlGenerator.forBlock['math_number'] = function (block: Blockly.Block) {
    const code = Number(block.getFieldValue('NUM'));
    const order = code >= 0 ? mqlGenerator.ORDER_ATOMIC :
        mqlGenerator.ORDER_UNARY_NEGATION;
    return [code, order];
};

mqlGenerator.forBlock['math_arithmetic'] = function (block: Blockly.Block) {
    const OPERATORS = {
        'ADD': [' + ', mqlGenerator.ORDER_ADDITION],
        'MINUS': [' - ', mqlGenerator.ORDER_SUBTRACTION],
        'MULTIPLY': [' * ', mqlGenerator.ORDER_MULTIPLICATION],
        'DIVIDE': [' / ', mqlGenerator.ORDER_DIVISION],
        'POWER': [null, mqlGenerator.ORDER_NONE]
    };
    const tuple = OPERATORS[block.getFieldValue('OP')];
    const operator = tuple[0];
    const order = tuple[1];
    const argument0 = mqlGenerator.valueToCode(block, 'A', order) || '0';
    const argument1 = mqlGenerator.valueToCode(block, 'B', order) || '0';
    let code;
    if (!operator) {
        code = 'MathPow(' + argument0 + ', ' + argument1 + ')';
        return [code, mqlGenerator.ORDER_FUNCTION_CALL];
    }
    code = argument0 + operator + argument1;
    return [code, order];
};

// Variables
mqlGenerator.forBlock['variables_get'] = function (block: Blockly.Block) {
    const code = mqlGenerator.variableDB_.getName(block.getFieldValue('VAR'),
        Blockly.Names.NameType.VARIABLE);
    return [code, mqlGenerator.ORDER_ATOMIC];
};

mqlGenerator.forBlock['variables_set'] = function (block: Blockly.Block) {
    const argument0 = mqlGenerator.valueToCode(block, 'VALUE',
        mqlGenerator.ORDER_ASSIGNMENT) || '0';
    const varName = mqlGenerator.variableDB_.getName(block.getFieldValue('VAR'),
        Blockly.Names.NameType.VARIABLE);
    return varName + ' = ' + argument0 + ';\n';
};

// =============================================================================
// CUSTOM PROJECT BLOCKS
// =============================================================================

// --- Control Blocks ---
mqlGenerator.forBlock['control_forever'] = function (block: Blockly.Block) {
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    // In MQL, OnTick is the loop. We don't need while(true)
    return doCode;
};

mqlGenerator.forBlock['control_if'] = function (block: Blockly.Block) {
    const condition = mqlGenerator.valueToCode(block, 'CONDITION', mqlGenerator.ORDER_NONE) || 'false';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    return `if (${condition}) {\n${doCode}}\n`;
};

mqlGenerator.forBlock['control_if_else'] = function (block: Blockly.Block) {
    const condition = mqlGenerator.valueToCode(block, 'CONDITION', mqlGenerator.ORDER_NONE) || 'false';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    const elseCode = mqlGenerator.statementToCode(block, 'ELSE');
    return `if (${condition}) {\n${doCode}} else {\n${elseCode}}\n`;
};

mqlGenerator.forBlock['control_repeat'] = function (block: Blockly.Block) {
    const times = mqlGenerator.valueToCode(block, 'TIMES', mqlGenerator.ORDER_NONE) || '1';
    const doCode = mqlGenerator.statementToCode(block, 'DO');
    return `for (int i = 0; i < ${times}; i++) {\n${doCode}}\n`;
};

// --- Operator Blocks ---
mqlGenerator.forBlock['operator_less'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} < ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_greater'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} > ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_EQUALITY) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_EQUALITY) || '0';
    return [`${left} == ${right}`, mqlGenerator.ORDER_EQUALITY];
};

mqlGenerator.forBlock['operator_less_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} <= ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_greater_equals'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_RELATIONAL) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_RELATIONAL) || '0';
    return [`${left} >= ${right}`, mqlGenerator.ORDER_RELATIONAL];
};

mqlGenerator.forBlock['operator_add'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_ADDITION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_ADDITION) || '0';
    return [`${left} + ${right}`, mqlGenerator.ORDER_ADDITION];
};

mqlGenerator.forBlock['operator_subtract'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_SUBTRACTION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_SUBTRACTION) || '0';
    return [`${left} - ${right}`, mqlGenerator.ORDER_SUBTRACTION];
};

mqlGenerator.forBlock['operator_multiply'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_MULTIPLICATION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_MULTIPLICATION) || '0';
    return [`${left} * ${right}`, mqlGenerator.ORDER_MULTIPLICATION];
};

mqlGenerator.forBlock['operator_divide'] = function (block: Blockly.Block) {
    const left = mqlGenerator.valueToCode(block, 'LEFT', mqlGenerator.ORDER_DIVISION) || '0';
    const right = mqlGenerator.valueToCode(block, 'RIGHT', mqlGenerator.ORDER_DIVISION) || '1';
    return [`${left} / ${right}`, mqlGenerator.ORDER_DIVISION];
};

// --- Environment Blocks ---
mqlGenerator.forBlock['environment_price'] = function () {
    return ['Close[0]', mqlGenerator.ORDER_ATOMIC];
};

// --- Trading Blocks ---
mqlGenerator.forBlock['trade_order'] = function (block: Blockly.Block) {
    const direction = block.getFieldValue('DIRECTION'); // 'long' or 'short'
    const size = block.getFieldValue('SIZE') || '0.1';
    const cmd = direction === 'long' ? 'OP_BUY' : 'OP_SELL';
    const price = direction === 'long' ? 'Ask' : 'Bid';
    const color = direction === 'long' ? 'clrGreen' : 'clrRed';

    return `if(OrdersTotal() == 0) {
   int ticket = OrderSend(Symbol(), ${cmd}, ${size}, ${price}, 3, 0, 0, "PPM Strategy", 12345, 0, ${color});
   if(ticket < 0) Print("OrderSend failed with error #", GetLastError());
}
`;
};

mqlGenerator.forBlock['trade_take_profit'] = function (block: Blockly.Block) {
    const price = mqlGenerator.valueToCode(block, 'PRICE', mqlGenerator.ORDER_NONE) || '0';
    return `for(int i=OrdersTotal()-1; i>=0; i--) {
   if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
      if(OrderSymbol() == Symbol() && OrderMagicNumber() == 12345) {
         if(!OrderModify(OrderTicket(), OrderOpenPrice(), OrderStopLoss(), ${price}, 0, clrNONE)) {
            Print("OrderModify TP failed error #", GetLastError());
         }
      }
   }
}
`;
};

mqlGenerator.forBlock['trade_stop_loss'] = function (block: Blockly.Block) {
    const price = mqlGenerator.valueToCode(block, 'PRICE', mqlGenerator.ORDER_NONE) || '0';
    return `for(int i=OrdersTotal()-1; i>=0; i--) {
   if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
      if(OrderSymbol() == Symbol() && OrderMagicNumber() == 12345) {
         if(!OrderModify(OrderTicket(), OrderOpenPrice(), ${price}, OrderTakeProfit(), 0, clrNONE)) {
            Print("OrderModify SL failed error #", GetLastError());
         }
      }
   }
}
`;
};

// --- Indicator Blocks ---
mqlGenerator.forBlock['ta_rsi'] = function (block: Blockly.Block) {
    const period = mqlGenerator.valueToCode(block, 'PERIOD', mqlGenerator.ORDER_NONE) || '14';
    // iRSI(symbol, timeframe, period, applied_price, shift)
    return [`iRSI(NULL, 0, ${period}, PRICE_CLOSE, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_sma'] = function (block: Blockly.Block) {
    const period = mqlGenerator.valueToCode(block, 'PERIOD', mqlGenerator.ORDER_NONE) || '14';
    // iMA(symbol, timeframe, period, ma_shift, ma_method, applied_price, shift)
    return [`iMA(NULL, 0, ${period}, 0, MODE_SMA, PRICE_CLOSE, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_ema'] = function (block: Blockly.Block) {
    const period = mqlGenerator.valueToCode(block, 'PERIOD', mqlGenerator.ORDER_NONE) || '14';
    return [`iMA(NULL, 0, ${period}, 0, MODE_EMA, PRICE_CLOSE, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_bb'] = function (block: Blockly.Block) {
    const period = mqlGenerator.valueToCode(block, 'PERIOD', mqlGenerator.ORDER_NONE) || '20';
    const deviation = mqlGenerator.valueToCode(block, 'DEVIATION', mqlGenerator.ORDER_NONE) || '2';
    const band = block.getFieldValue('BAND') || 'MIDDLE';
    const bandMode = band === 'UPPER' ? 'MODE_UPPER' : (band === 'LOWER' ? 'MODE_LOWER' : 'MODE_MAIN');
    // iBands(symbol, timeframe, period, deviation, bands_shift, applied_price, mode, shift)
    return [`iBands(NULL, 0, ${period}, ${deviation}, 0, PRICE_CLOSE, ${bandMode}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_macd'] = function (block: Blockly.Block) {
    const mode = block.getFieldValue('MODE') || 'MAIN';
    const modeValue = mode === 'SIGNAL' ? 'MODE_SIGNAL' : 'MODE_MAIN';
    // iMACD(symbol, timeframe, fast_ema, slow_ema, signal_sma, applied_price, mode, shift)
    return [`iMACD(NULL, 0, 12, 26, 9, PRICE_CLOSE, ${modeValue}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_atr'] = function (block: Blockly.Block) {
    const period = mqlGenerator.valueToCode(block, 'PERIOD', mqlGenerator.ORDER_NONE) || '14';
    // iATR(symbol, timeframe, period, shift)
    return [`iATR(NULL, 0, ${period}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};

mqlGenerator.forBlock['ta_stochastic'] = function (block: Blockly.Block) {
    const mode = block.getFieldValue('MODE') || 'MAIN';
    const modeValue = mode === 'SIGNAL' ? 'MODE_SIGNAL' : 'MODE_MAIN';
    // iStochastic(symbol, timeframe, %K, %D, slowing, method, price_field, mode, shift)
    return [`iStochastic(NULL, 0, 5, 3, 3, MODE_SMA, 0, ${modeValue}, 0)`, mqlGenerator.ORDER_FUNCTION_CALL];
};
