"""Agent-authored tool · compute_var_95

Empirical 5%-quantile.

Generated by Phase-G developer flow. Calls go through the sandbox.
"""

def compute_var_95(returns: list[float]) -> dict:
    """Empirical 5%-quantile."""
    if not returns: return {"var": 0.0, "n": 0}
    s = sorted(returns); idx = max(0, int(0.05*len(s))-1)
    return {"var": float(s[idx]), "n": len(s)}
