/**
 * PlotCard — renders a plot generated by the AI.
 *
 * v1: lightweight SVG renderer (no chart library dep). Click → expand modal.
 * Backend contract:
 *   payload: {
 *     kind: 'line' | 'bar' | 'scatter',
 *     title?: string, xLabel?: string, yLabel?: string,
 *     series: [{ name, points: [{x: number, y: number}], color? }],
 *   }
 */

import { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { LineChart, Maximize2 } from 'lucide-react';
import { PinButton } from '../components/PinButton';

interface Series {
  name: string;
  points: { x: number; y: number }[];
  color?: string;
}
interface Props {
  payload: {
    kind?: 'line' | 'bar' | 'scatter';
    title?: string;
    xLabel?: string;
    yLabel?: string;
    series: Series[];
  };
}

const DEFAULT_COLORS = ['#a78bfa', '#34d399', '#fbbf24', '#f87171', '#60a5fa'];

export function PlotCard({ payload }: Props) {
  const [expanded, setExpanded] = useState(false);
  const { title, xLabel, yLabel, series = [] } = payload;

  const { width, height, points, xRange, yRange } = useMemo(() => {
    const w = expanded ? 720 : 420;
    const h = expanded ? 360 : 200;
    const allPts = series.flatMap((s) => s.points);
    if (allPts.length === 0) return { width: w, height: h, points: [], xRange: [0, 1], yRange: [0, 1] };
    const xs = allPts.map((p) => p.x);
    const ys = allPts.map((p) => p.y);
    const xMin = Math.min(...xs);
    const xMax = Math.max(...xs);
    const yMin = Math.min(...ys);
    const yMax = Math.max(...ys);
    const xPad = (xMax - xMin) * 0.02 || 1;
    const yPad = (yMax - yMin) * 0.05 || 1;
    return {
      width: w,
      height: h,
      points: allPts,
      xRange: [xMin - xPad, xMax + xPad],
      yRange: [yMin - yPad, yMax + yPad],
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [series, expanded]);

  const padding = { top: 16, right: 16, bottom: 28, left: 36 };
  const innerW = width - padding.left - padding.right;
  const innerH = height - padding.top - padding.bottom;

  const xScale = (x: number) =>
    padding.left + ((x - xRange[0]) / (xRange[1] - xRange[0])) * innerW;
  const yScale = (y: number) =>
    padding.top + (1 - (y - yRange[0]) / (yRange[1] - yRange[0])) * innerH;

  const renderSeries = (s: Series, idx: number) => {
    const color = s.color || DEFAULT_COLORS[idx % DEFAULT_COLORS.length];
    const path = s.points
      .map((p, i) => `${i === 0 ? 'M' : 'L'}${xScale(p.x)},${yScale(p.y)}`)
      .join(' ');
    return (
      <g key={s.name + idx}>
        <path d={path} fill="none" stroke={color} strokeWidth={1.5} />
      </g>
    );
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.97 }}
      animate={{ opacity: 1, scale: 1 }}
      className="mt-2 rounded-lg border border-purple-500/20 bg-purple-500/5 overflow-hidden"
    >
      <div className="flex items-center justify-between px-3 py-2 border-b border-purple-500/10">
        <div className="flex items-center gap-2 text-xs text-purple-300">
          <LineChart className="w-3.5 h-3.5" />
          <span className="font-medium">{title ?? 'Chart'}</span>
        </div>
        <div className="flex items-center gap-1">
          <PinButton cardType="plot" payload={payload} title={title} />
          <button
            onClick={() => setExpanded((v) => !v)}
            className="text-white/40 hover:text-white p-1"
            aria-label="Expand"
          >
            <Maximize2 className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>
      <div className="p-2 overflow-auto">
        <svg width={width} height={height} className="block">
          {/* axes */}
          <line
            x1={padding.left}
            y1={height - padding.bottom}
            x2={width - padding.right}
            y2={height - padding.bottom}
            stroke="rgba(255,255,255,0.1)"
          />
          <line
            x1={padding.left}
            y1={padding.top}
            x2={padding.left}
            y2={height - padding.bottom}
            stroke="rgba(255,255,255,0.1)"
          />
          {series.map(renderSeries)}
        </svg>
      </div>
      {(xLabel || yLabel) && (
        <div className="px-3 pb-2 text-[10px] text-white/40 flex justify-between">
          {yLabel && <span>{yLabel}</span>}
          {xLabel && <span className="ml-auto">{xLabel}</span>}
        </div>
      )}
    </motion.div>
  );
}
