"""On-disk registry of agent-authored Python tools.

Files live at  `agents/tools/dynamic/<name>.py`
Index lives at `agents/tools/dynamic/_index.json` — list of `DynamicToolMeta`.

Validation invariants (`_validate_module`):
  • module compiles
  • exports a function with the same name as `<name>` (snake_case)
  • that function has type annotations on every parameter and a return type
  • function carries a non-empty docstring
  • function does not import any module on `_FORBIDDEN_IMPORTS`

Calls always go through the Phase-G sandbox so the backend process never
imports the agent's code; this keeps a misbehaving generated tool from
crashing the server.
"""
from __future__ import annotations

import ast
import inspect
import json
import re
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from sandbox import ExecuteRequest, execute_python

REPO_ROOT = Path(__file__).resolve().parents[2]
DYNAMIC_TOOLS_DIR = REPO_ROOT / "agents" / "tools" / "dynamic"
INDEX_FILE = DYNAMIC_TOOLS_DIR / "_index.json"

_NAME_RE = re.compile(r"^[a-z][a-z0-9_]{1,63}$")

# These imports are *suspicious* in agent-authored code — not a security
# boundary (the sandbox already provides that), but a sanity rail so an
# obviously-wrong tool (`rm -rf` via os.system, network calls in a "compute
# variance" tool) doesn't slip through review.
_FORBIDDEN_IMPORTS = {
    "subprocess", "ctypes", "socket", "asyncio", "fcntl",
    "shutil",  # tools shouldn't move files; the sandbox handles that
}


@dataclass
class DynamicToolMeta:
    name: str
    description: str
    signature: str  # human-readable, e.g. "compute_var(returns: list[float], alpha: float = 0.95) -> float"
    created_at: float
    updated_at: float
    source_path: str
    inputs: list[dict[str, Any]] = field(default_factory=list)
    return_annotation: str | None = None


# ── public API ────────────────────────────────────────────────────────


def list_dynamic_tools() -> list[DynamicToolMeta]:
    if not INDEX_FILE.exists():
        return []
    raw = json.loads(INDEX_FILE.read_text() or "[]")
    return [DynamicToolMeta(**r) for r in raw]


def read_dynamic_tool_source(name: str) -> str | None:
    p = DYNAMIC_TOOLS_DIR / f"{name}.py"
    return p.read_text(encoding="utf-8") if p.exists() else None


def delete_dynamic_tool(name: str) -> bool:
    if not _NAME_RE.match(name):
        return False
    p = DYNAMIC_TOOLS_DIR / f"{name}.py"
    if not p.exists():
        return False
    p.unlink()
    _rewrite_index([m for m in list_dynamic_tools() if m.name != name])
    return True


def create_dynamic_tool(
    name: str,
    code: str,
    description: str = "",
) -> dict[str, Any]:
    """Validate `code`, write it to disk, append to the index.

    Returns `{ok, meta?, errors?}`. On failure nothing is persisted.
    """
    errors: list[str] = []
    if not _NAME_RE.match(name):
        errors.append(
            f"Tool name '{name}' must be snake_case, start with a letter, "
            "and be 2..64 chars long."
        )
    DYNAMIC_TOOLS_DIR.mkdir(parents=True, exist_ok=True)

    if not errors:
        v = _validate_module(name, code)
        errors.extend(v["errors"])

    if errors:
        return {"ok": False, "errors": errors}

    sig = v["signature"]
    inputs = v["inputs"]
    ret_anno = v["return_annotation"]
    doc = v["doc"] or description or ""

    target = DYNAMIC_TOOLS_DIR / f"{name}.py"
    header = (
        f'"""Agent-authored tool · {name}\n\n'
        f'{doc.strip()}\n\n'
        f'Generated by Phase-G developer flow. Calls go through the sandbox.\n'
        f'"""\n'
    )
    target.write_text(header + "\n" + code.strip() + "\n", encoding="utf-8")

    now = time.time()
    existing = [m for m in list_dynamic_tools() if m.name != name]
    meta = DynamicToolMeta(
        name=name,
        description=(description or doc).strip()[:500],
        signature=sig,
        created_at=(min((m.created_at for m in existing if m.name == name), default=now)),
        updated_at=now,
        source_path=str(target),
        inputs=inputs,
        return_annotation=ret_anno,
    )
    existing.append(meta)
    _rewrite_index(existing)

    return {"ok": True, "meta": asdict(meta)}


def call_dynamic_tool(name: str, kwargs: dict[str, Any] | None = None,
                      timeout_s: float = 8.0) -> dict[str, Any]:
    """Run the tool inside the sandbox and return its parsed result.

    The tool function is expected to return a JSON-serialisable value;
    we wrap the call in a tiny harness that prints
        ===RESULT===\n<json>\n===END===
    on stdout, then parse it back.
    """
    if not _NAME_RE.match(name):
        return {"ok": False, "error": f"bad tool name '{name}'"}
    src_path = DYNAMIC_TOOLS_DIR / f"{name}.py"
    if not src_path.exists():
        return {"ok": False, "error": f"unknown tool '{name}'"}

    code = src_path.read_text(encoding="utf-8")
    harness = (
        f"{code}\n\n"
        f"if __name__ == '__main__':\n"
        f"    import json, sys\n"
        f"    _kwargs = json.loads(sys.argv[1] if len(sys.argv) > 1 else '{{}}')\n"
        f"    _out = {name}(**_kwargs)\n"
        f"    print('===RESULT===')\n"
        f"    print(json.dumps(_out, default=str))\n"
        f"    print('===END===')\n"
    )
    payload = json.dumps(kwargs or {})

    res = execute_python(ExecuteRequest(code=harness, timeout_s=timeout_s,
                                        extra_argv=[payload]))
    if not res.success:
        return {
            "ok": False,
            "error": (res.error
                      or (res.stderr or "").strip().splitlines()[-1] if (res.stderr or "").strip()
                      else f"exit={res.exit_code}"),
            "stdout": res.stdout,
            "stderr": res.stderr,
            "duration_ms": res.duration_ms,
        }

    parsed = _parse_harness_output(res.stdout)
    return {
        "ok": parsed["ok"],
        "result": parsed.get("value"),
        "error": parsed.get("error"),
        "stdout": res.stdout,
        "duration_ms": res.duration_ms,
    }


# ── internals ────────────────────────────────────────────────────────


def _rewrite_index(metas: list[DynamicToolMeta]) -> None:
    DYNAMIC_TOOLS_DIR.mkdir(parents=True, exist_ok=True)
    INDEX_FILE.write_text(
        json.dumps([asdict(m) for m in metas], indent=2),
        encoding="utf-8",
    )


def _parse_harness_output(stdout: str) -> dict[str, Any]:
    if "===RESULT===" not in stdout or "===END===" not in stdout:
        return {"ok": False, "error": "no result block emitted"}
    body = stdout.split("===RESULT===", 1)[1].split("===END===", 1)[0].strip()
    try:
        return {"ok": True, "value": json.loads(body)}
    except json.JSONDecodeError as e:
        return {"ok": False, "error": f"bad JSON from tool: {e}"}


def _validate_module(name: str, code: str) -> dict[str, Any]:
    """Static + dynamic validation. Importing happens in a sandbox."""
    errors: list[str] = []
    inputs: list[dict[str, Any]] = []
    signature = ""
    return_annotation: str | None = None
    doc = ""

    # Static parse — catches syntax errors and forbidden imports cheaply.
    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        return {"errors": [f"SyntaxError: {e}"], "signature": "", "inputs": [],
                "return_annotation": None, "doc": ""}

    fn_node = None
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == name:
            fn_node = node
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            mods = ([n.name.split(".")[0] for n in node.names]
                    if isinstance(node, ast.Import)
                    else [(node.module or "").split(".")[0]])
            bad = [m for m in mods if m in _FORBIDDEN_IMPORTS]
            if bad:
                errors.append(f"Forbidden import(s): {', '.join(bad)}")

    if fn_node is None:
        errors.append(f"Module must define a function named `{name}`.")
        return {"errors": errors, "signature": "", "inputs": [],
                "return_annotation": None, "doc": ""}

    if fn_node.returns is None:
        errors.append(f"Function `{name}` must declare a return type annotation.")

    args = fn_node.args
    all_args = args.posonlyargs + args.args + args.kwonlyargs
    for a in all_args:
        if a.annotation is None:
            errors.append(f"Argument `{a.arg}` must have a type annotation.")
        else:
            inputs.append({
                "name": a.arg,
                "annotation": ast.unparse(a.annotation),
            })

    if fn_node.returns is not None:
        return_annotation = ast.unparse(fn_node.returns)

    doc_node = ast.get_docstring(fn_node, clean=True) or ""
    if not doc_node.strip():
        errors.append(f"Function `{name}` must have a docstring describing what it does.")
    doc = doc_node

    # Build a printable signature.
    arg_strs = []
    for a in args.args:
        anno = ast.unparse(a.annotation) if a.annotation else "Any"
        arg_strs.append(f"{a.arg}: {anno}")
    for i, dflt in enumerate(args.defaults):
        # apply defaults to the *trailing* args.args entries
        idx = len(args.args) - len(args.defaults) + i
        if 0 <= idx < len(arg_strs):
            arg_strs[idx] += f" = {ast.unparse(dflt)}"
    signature = f"{name}({', '.join(arg_strs)}) -> {return_annotation or 'Any'}"

    if errors:
        return {"errors": errors, "signature": signature, "inputs": inputs,
                "return_annotation": return_annotation, "doc": doc}

    # Dynamic check: importing in the sandbox must succeed and the
    # function must be callable. We run a short probe that imports + asserts
    # the symbol is callable.
    probe = (
        code
        + "\n\nif __name__ == '__main__':\n"
        + f"    assert callable({name}), 'symbol exists but is not callable'\n"
        + "    print('OK')\n"
    )
    res = execute_python(ExecuteRequest(code=probe, timeout_s=4.0))
    if not res.success or "OK" not in res.stdout:
        last = (res.stderr or "").strip().splitlines()[-1:] or ["(no stderr)"]
        errors.append(f"Sandbox import/probe failed: {last[0]}")

    return {"errors": errors, "signature": signature, "inputs": inputs,
            "return_annotation": return_annotation, "doc": doc}
